// ═══════════════════════════════════════════════════════════════
// FAALUL LUQMAN — Nakshatra Sulamani Results (FULL REPLACEMENT)
// Source: Nakshatra Sulamani Luqman (28-letter system)
// Used ONLY by FaalHasrathPage (Luqman subsection).
// All 28 results replaced with Nakshatra Sulamani source texts.
// Zero shared data with Faal Ali or any other module.
// ═══════════════════════════════════════════════════════════════

export const LUQMAN_CELLS = [
  {
    lq_id: 101,
    symbol: "ا",
    symbolName: "Alif",
    ml: {
      shortTitle: "ഫലം വൈകും",
      result: "കാര്യം സാധിക്കും, പക്ഷേ വൈകും",
      body: "ഈ ഫാൽ പ്രകാരം ആഗ്രഹിക്കുന്ന കാര്യം സഫലമാകും. എന്നാൽ അല്പം കാലതാമസം ഉണ്ടാകും. ക്ഷമയോടെ കാത്തിരിക്കുക.",
      remedy: "ദിവസവും ബിസ്മില്ല ചൊല്ലി കാര്യം ആരംഭിക്കുക.",
    },
    en: {
      shortTitle: "Delayed Success",
      result: "Will succeed, but delayed",
      body: "The desired matter will be fulfilled according to this omen. However, there will be some delay. Wait with patience.",
      remedy: "Begin every matter daily by reciting Bismillah.",
    },
  },
  {
    lq_id: 102,
    symbol: "ب",
    symbolName: "Ba",
    ml: {
      shortTitle: "ആശങ്ക അകലും",
      result: "ആശങ്ക അകലും, കാര്യം നടക്കും",
      body: "മനസ്സിലെ ആശങ്കകൾ അകലും. ഉദ്ദേശിക്കുന്ന കാര്യം വിജയകരമായി നടക്കും. ശുഭകരമായ ഫലം.",
      remedy: "ദരിദ്രർക്ക് ഭക്ഷണം നൽകുക.",
    },
    en: {
      shortTitle: "Fear Removed",
      result: "Fear will vanish, matter will succeed",
      body: "Mental anxieties will disappear. The intended matter will proceed successfully. Auspicious result.",
      remedy: "Feed the poor.",
    },
  },
  {
    lq_id: 103,
    symbol: "ت",
    symbolName: "Ta",
    ml: {
      shortTitle: "ഫലം ഇല്ല",
      result: "പ്രയോജനമില്ല, ഇപ്പോൾ ഫലം ഇല്ല",
      body: "ഈ സമയത്ത് ഈ കാര്യത്തിൽ പ്രയോജനം ഇല്ല. ഇപ്പോൾ ഫലം ലഭിക്കില്ല. മറ്റൊരു സമയം പരിശോധിക്കുക.",
      remedy: "ആയത്തുൽ കുർസി ദിവസം നാൽപ്പതു വട്ടം ഓതുക.",
    },
    en: {
      shortTitle: "No Benefit Now",
      result: "No benefit, no result at present",
      body: "At this time there is no benefit in this matter. No result will be obtained now. Try again at another time.",
      remedy: "Recite Ayatul Kursi forty times daily.",
    },
  },
  {
    lq_id: 104,
    symbol: "ث",
    symbolName: "Tha",
    ml: {
      shortTitle: "ജാഗ്രത വേണം",
      result: "ശത്രുക്കളിൽ നിന്ന് ജാഗ്രത പാലിക്കുക",
      body: "ശത്രുക്കളിൽ നിന്ന് ഉപദ്രവം ഉണ്ടാകാം. അതിനാൽ ജാഗ്രത പാലിക്കുക. സൂക്ഷ്മതയോടെ ഇടപെടുക.",
      remedy: "ഇസ്തിഗ്ഫാർ കൂടുതൽ ചൊല്ലുക.",
    },
    en: {
      shortTitle: "Stay Vigilant",
      result: "Beware of enemies",
      body: "Harm may come from enemies. Therefore stay vigilant. Deal with caution.",
      remedy: "Recite Istighfar abundantly.",
    },
  },
  {
    lq_id: 105,
    symbol: "ج",
    symbolName: "Jim",
    ml: {
      shortTitle: "സമയം എടുക്കും",
      result: "ഈ കാര്യത്തിന് അല്പം സമയം എടുക്കും",
      body: "ഈ കാര്യം സഫലമാകാൻ അല്പം സമയം എടുക്കും. ക്ഷമയോടെ കാത്തിരിക്കുക. ഫലം ലഭിക്കും.",
      remedy: "സൂറത്ത് യൂനുസ് ഓതുക.",
    },
    en: {
      shortTitle: "Takes Time",
      result: "This matter will take some time",
      body: "This matter will take some time to be fulfilled. Wait with patience. Result will come.",
      remedy: "Recite Surah Yunus.",
    },
  },
  {
    lq_id: 106,
    symbol: "ح",
    symbolName: "Ha",
    ml: {
      shortTitle: "കാത്തിരിക്കുക",
      result: "ഈ കാര്യം ഇപ്പോൾ നടക്കില്ല, കാത്തിരിക്കുക",
      body: "ഈ കാര്യം ഇപ്പോൾ നടക്കില്ല. അല്പം കാത്തിരിക്കുക. ശരിയായ സമയത്ത് ഫലം ലഭിക്കും.",
      remedy: "ഒരു ദരിദ്ര കുടുംബത്തെ സഹായിക്കുക.",
    },
    en: {
      shortTitle: "Wait",
      result: "Will not happen now, wait",
      body: "This matter will not happen now. Wait a little. Result will come at the right time.",
      remedy: "Help a needy family.",
    },
  },
  {
    lq_id: 107,
    symbol: "خ",
    symbolName: "Kha",
    ml: {
      shortTitle: "ദൈവവിശ്വാസം",
      result: "ആശങ്ക ഒഴിവാക്കി ദൈവവിശ്വാസം വെക്കുക",
      body: "ആശങ്കകൾ ഒഴിവാക്കി അല്ലാഹുവിങ്കൽ വിശ്വാസം വെക്കുക. ഫലം ശുഭകരമാകും.",
      remedy: "സൂറത്ത് ഇഖ്ലാസ് ഇരുനൂറ് തവണ ഓതി ദുആ ചെയ്യുക.",
    },
    en: {
      shortTitle: "Trust in Allah",
      result: "Avoid anxiety, trust in Allah",
      body: "Avoid anxieties and place trust in Allah. The result will be favorable.",
      remedy: "Recite Surah Ikhlas two hundred times and supplicate.",
    },
  },
  {
    lq_id: 108,
    symbol: "د",
    symbolName: "Dal",
    ml: {
      shortTitle: "പരിഹാരം തേടുക",
      result: "ശത്രുക്കളുണ്ട്, പരിഹാരം തേടുക",
      body: "ശത്രുക്കൾ ഉണ്ട്. അവരിൽ നിന്ന് രക്ഷനേടാൻ പരിഹാരം തേടുക. ജാഗ്രത പാലിക്കുക.",
      remedy: "നഫിൽ നിസ്കാരം നിർവഹിക്കുക.",
    },
    en: {
      shortTitle: "Seek Remedy",
      result: "Enemies exist, seek remedy",
      body: "Enemies are present. Seek remedy to be safe from them. Stay vigilant.",
      remedy: "Perform voluntary prayers.",
    },
  },
  {
    lq_id: 109,
    symbol: "ذ",
    symbolName: "Dhal",
    ml: {
      shortTitle: "ആശങ്ക നീങ്ങും",
      result: "ആശങ്കകൾ നീങ്ങും",
      body: "മനസ്സിലെ ആശങ്കകൾ നീങ്ങും. സമാധാനം ലഭിക്കും. കാര്യം സഫലമാകും.",
      remedy: "ദൈനംദിനം ദുറൂദ് ഓതുക.",
    },
    en: {
      shortTitle: "Anxiety Removed",
      result: "Anxieties will disappear",
      body: "Mental anxieties will disappear. Peace will be attained. The matter will be fulfilled.",
      remedy: "Recite Durood daily.",
    },
  },
  {
    lq_id: 110,
    symbol: "ر",
    symbolName: "Ra",
    ml: {
      shortTitle: "കാര്യം സാധിക്കും",
      result: "കാര്യം സാധിക്കും, ദുആയും സലാത്തും ചൊല്ലുക",
      body: "ആഗ്രഹിക്കുന്ന കാര്യം സാധിക്കും. ദുആയും സലാത്തും കൂടുതൽ ചൊല്ലുക. ഫലം ലഭിക്കും.",
      remedy: "ഒരു അനാഥ കുട്ടിക്ക് ഭക്ഷണം നൽകുക.",
    },
    en: {
      shortTitle: "Will Succeed",
      result: "Will succeed, recite Dua and Salath",
      body: "The desired matter will succeed. Recite more Dua and Salath. Result will come.",
      remedy: "Feed an orphaned child.",
    },
  },
  {
    lq_id: 111,
    symbol: "ز",
    symbolName: "Zayn",
    ml: {
      shortTitle: "ഉത്തമ ഫലം",
      result: "ഉത്തമ ഫലം, മംഗളമാകും",
      body: "ഉത്തമമായ ഫലം ലഭിക്കും. കാര്യം മംഗളകരമായി നടക്കും. സന്തോഷം ഉണ്ടാകും.",
      remedy: "ദിവസേന ഒരു ജുസ്ഉ് ഖുർആൻ ഓതുക.",
    },
    en: {
      shortTitle: "Excellent Result",
      result: "Excellent result, will be blessed",
      body: "Excellent result will be obtained. The matter will proceed auspiciously. Happiness will come.",
      remedy: "Recite one Juz of the Quran daily.",
    },
  },
  {
    lq_id: 112,
    symbol: "س",
    symbolName: "Sin",
    ml: {
      shortTitle: "ദുആ ചെയ്യുക",
      result: "ആശങ്കകൾ മാറില്ല, ദുആ ചെയ്യുക",
      body: "ആശങ്കകൾ മാറില്ല. അല്ലാഹുവിനോട് ദുആ ചെയ്യുക. പരിഹാരം ലഭിക്കും.",
      remedy: "ഖബ്ർ സിയാറത്ത് ചെയ്ത് ദുആ ചെയ്യുക.",
    },
    en: {
      shortTitle: "Make Dua",
      result: "Anxieties won't go, make Dua",
      body: "Anxieties will not disappear. Supplicate to Allah. Remedy will be found.",
      remedy: "Visit a grave and supplicate.",
    },
  },
  {
    lq_id: 113,
    symbol: "ش",
    symbolName: "Shin",
    ml: {
      shortTitle: "നല്ല വാർത്ത",
      result: "നല്ല വാർത്ത ലഭിക്കും",
      body: "ദൂരത്ത് നിന്ന് നല്ല വാർത്ത ലഭിക്കും. സന്തോഷകരമായ വിവരം വരും.",
      remedy: "മൂന്ന് ദിവസം നോമ്പ് അനുഷ്ഠിക്കുക.",
    },
    en: {
      shortTitle: "Good News",
      result: "Good news will arrive",
      body: "Good news will arrive from afar. Happy information will come.",
      remedy: "Observe a fast for three days.",
    },
  },
  {
    lq_id: 114,
    symbol: "ص",
    symbolName: "Swad",
    ml: {
      shortTitle: "ശുഭ ഫലം",
      result: "ശുഭപ്രദമായ ഫലം",
      body: "ശുഭപ്രദമായ ഫലം ലഭിക്കും. കാര്യം വിജയകരമാകും. സന്തോഷം ഉണ്ടാകും.",
      remedy: "സദഖ ചെയ്യുക. സ്വാബ് ചെയ്യുക.",
    },
    en: {
      shortTitle: "Auspicious Result",
      result: "Auspicious result",
      body: "Auspicious result will be obtained. The matter will be successful. Happiness will come.",
      remedy: "Give charity and perform good deeds.",
    },
  },
  {
    lq_id: 115,
    symbol: "ض",
    symbolName: "Dhwad",
    ml: {
      shortTitle: "ഏറ്റുമുട്ടൽ സാധ്യത",
      result: "ശത്രുക്കളുമായി ഏറ്റുമുട്ടൽ സാധ്യത",
      body: "ശത്രുക്കളുമായി ഏറ്റുമുട്ടൽ ഉണ്ടാകാം. ജാഗ്രത പാലിക്കുക. സൂക്ഷ്മതയോടെ ഇടപെടുക.",
      remedy: "നോമ്പ് അനുഷ്ഠിക്കുക. ഇസ്ലാഹ് ഗ്രന്ഥങ്ങൾ വായിക്കുക.",
    },
    en: {
      shortTitle: "Confrontation Likely",
      result: "Likely confrontation with enemies",
      body: "Confrontation with enemies may occur. Stay vigilant. Deal with caution.",
      remedy: "Observe fasts and read books of spiritual reform.",
    },
  },
  {
    lq_id: 116,
    symbol: "ط",
    symbolName: "Tta",
    ml: {
      shortTitle: "ആവേശം ഒഴിവാക്കുക",
      result: "ആവേശം ഒഴിവാക്കുക",
      body: "ആവേശം ഒഴിവാക്കുക. ശാന്തമായി ചിന്തിക്കുക. തീരുമാനങ്ങൾ ബുദ്ധിപൂർവ്വം എടുക്കുക.",
      remedy: "ഖുർആൻ ഒരു ഖത്മ് ഓതി ഹദ്‌യ ചെയ്യുക.",
    },
    en: {
      shortTitle: "Avoid Passion",
      result: "Avoid passion",
      body: "Avoid passion. Think calmly. Make decisions wisely.",
      remedy: "Complete a Khatm of the Quran and dedicate the reward.",
    },
  },
  {
    lq_id: 117,
    symbol: "ظ",
    symbolName: "Dha",
    ml: {
      shortTitle: "ഇഷ്ടം നടക്കില്ല",
      result: "ഇഷ്ടപ്പെട്ട പോലെ നടക്കില്ല",
      body: "ഇഷ്ടപ്പെട്ട പോലെ കാര്യങ്ങൾ നടക്കില്ല. മറ്റൊരു വഴി തേടുക.",
      remedy: "ശുക്കർ നമ്പർ സദഖ നൽകുക.",
    },
    en: {
      shortTitle: "Won't Go as Wished",
      result: "Will not go as wished",
      body: "Matters will not go as wished. Seek another path.",
      remedy: "Give gratitude charity.",
    },
  },
  {
    lq_id: 118,
    symbol: "ع",
    symbolName: "Ain",
    ml: {
      shortTitle: "എല്ലാം നല്ലതാകും",
      result: "എല്ലാം നല്ലതാകും",
      body: "എല്ലാ കാര്യങ്ങളും നല്ലതാകും. ശുഭകരമായ ഫലം ലഭിക്കും. സന്തോഷം ഉണ്ടാകും.",
      remedy: "ഒരു ഔലിയായുടെ ദർഗ്ഗ സിയാറത്ത് ചെയ്യുക.",
    },
    en: {
      shortTitle: "All Will Be Well",
      result: "All will be well",
      body: "All matters will be well. Favorable result will be obtained. Happiness will come.",
      remedy: "Visit the shrine of a saint.",
    },
  },
  {
    lq_id: 119,
    symbol: "غ",
    symbolName: "Ghain",
    ml: {
      shortTitle: "പ്രയോജനമില്ല",
      result: "പ്രയോജനമില്ല",
      body: "ഈ കാര്യത്തിൽ പ്രയോജനം ഇല്ല. മറ്റൊരു വഴി തേടുക.",
      remedy: "രണ്ട് റക്അത്ത് ഹാജത്ത് നിസ്കാരം നിർവഹിക്കുക.",
    },
    en: {
      shortTitle: "No Benefit",
      result: "No benefit",
      body: "There is no benefit in this matter. Seek another path.",
      remedy: "Perform two units of the prayer of need (Salatul Hajah).",
    },
  },
  {
    lq_id: 120,
    symbol: "ف",
    symbolName: "Fa",
    ml: {
      shortTitle: "ആഗ്രഹം സഫലം",
      result: "ആഗ്രഹം സഫലമാകും",
      body: "ആഗ്രഹിക്കുന്ന കാര്യം സഫലമാകും. വിജയം ലഭിക്കും. സന്തോഷം ഉണ്ടാകും.",
      remedy: "സൂറത്ത് ഫലഖ്, നാസ് ദിവസേന ഓതുക.",
    },
    en: {
      shortTitle: "Desire Fulfilled",
      result: "Desire will be fulfilled",
      body: "The desired matter will be fulfilled. Victory will be attained. Happiness will come.",
      remedy: "Recite Surah Al-Falaq and An-Nas daily.",
    },
  },
  {
    lq_id: 121,
    symbol: "ق",
    symbolName: "Qaf",
    ml: {
      shortTitle: "ആശങ്കയും താമസവും",
      result: "ആശങ്കയും താമസവും",
      body: "ആശങ്കയും താമസവും ഉണ്ടാകും. ക്ഷമയോടെ കാത്തിരിക്കുക.",
      remedy: "ഏഴ് ദിവസം കൂൾ ഓതി വെള്ളത്തിൽ ഊതി കുടിക്കുക.",
    },
    en: {
      shortTitle: "Anxiety and Delay",
      result: "Anxiety and delay",
      body: "Anxiety and delay will occur. Wait with patience.",
      remedy: "Recite Al-Fatiha for seven days, blow into water, and drink.",
    },
  },
  {
    lq_id: 122,
    symbol: "ك",
    symbolName: "Kaf",
    ml: {
      shortTitle: "ആത്മശുദ്ധി വേണം",
      result: "ആത്മശുദ്ധി ആവശ്യമാണ്",
      body: "ആത്മശുദ്ധി ആവശ്യമാണ്. പാപങ്ങളിൽ നിന്ന് വിട്ടുനിൽക്കുക.",
      remedy: "ഇസ്ലാഹ് ഗ്രന്ഥം വായിക്കുക.",
    },
    en: {
      shortTitle: "Self-Purification Needed",
      result: "Self-purification is necessary",
      body: "Self-purification is necessary. Stay away from sins.",
      remedy: "Read a book of spiritual guidance.",
    },
  },
  {
    lq_id: 123,
    symbol: "ل",
    symbolName: "Lam",
    ml: {
      shortTitle: "രോഗശമനം",
      result: "രോഗശമനവും നല്ല വാർത്തയും",
      body: "രോഗം ശമിക്കും. നല്ല വാർത്ത ലഭിക്കും. ശുഭകരമായ ഫലം.",
      remedy: "ഖസ്ബ് ഓതി അഭയം തേടുക.",
    },
    en: {
      shortTitle: "Healing and Good News",
      result: "Recovery and good news",
      body: "Illness will heal. Good news will arrive. Favorable result.",
      remedy: "Recite protective prayers and seek refuge.",
    },
  },
  {
    lq_id: 124,
    symbol: "م",
    symbolName: "Mim",
    ml: {
      shortTitle: "കാര്യം നടക്കും",
      result: "കാര്യം നടക്കും",
      body: "ആഗ്രഹിക്കുന്ന കാര്യം നടക്കും. വിജയം ലഭിക്കും.",
      remedy: "ഒരാഴ്ച ദിനരാത്ര ദിക്ർ ചൊല്ലുക.",
    },
    en: {
      shortTitle: "Will Happen",
      result: "The matter will happen",
      body: "The desired matter will happen. Victory will be attained.",
      remedy: "Engage in Dhikr morning and evening for one week.",
    },
  },
  {
    lq_id: 125,
    symbol: "ن",
    symbolName: "Nun",
    ml: {
      shortTitle: "കഷ്ടപ്പാട് സാധ്യത",
      result: "നഷ്ടം അല്ലെങ്കിൽ കഷ്ടപ്പാട് സാധ്യത",
      body: "നഷ്ടം അല്ലെങ്കിൽ കഷ്ടപ്പാട് ഉണ്ടാകാം. സൂക്ഷിക്കുക.",
      remedy: "ഉടൻ സദഖ ചെയ്ത് ദോഷ നിവൃത്തി ചോദിക്കുക.",
    },
    en: {
      shortTitle: "Hardship Likely",
      result: "Loss or hardship likely",
      body: "Loss or hardship may occur. Be cautious.",
      remedy: "Immediately give charity and seek removal of harm.",
    },
  },
  {
    lq_id: 126,
    symbol: "و",
    symbolName: "Waw",
    ml: {
      shortTitle: "നല്ല ഫലം",
      result: "നല്ല ഫലം",
      body: "നല്ല ഫലം ലഭിക്കും. കാര്യം സഫലമാകും.",
      remedy: "മസ്ജിദിൽ ഇഅ്തിക്കാഫ് ഇരിക്കുക.",
    },
    en: {
      shortTitle: "Good Result",
      result: "Good result",
      body: "Good result will be obtained. The matter will be fulfilled.",
      remedy: "Perform I'tikaf in the mosque.",
    },
  },
  {
    lq_id: 127,
    symbol: "ه",
    symbolName: "Ha",
    ml: {
      shortTitle: "സമയത്ത് നടക്കും",
      result: "കാര്യം സമയത്ത് നടക്കും",
      body: "കാര്യം സമയത്ത് നടക്കും. താമസം ഉണ്ടാകില്ല.",
      remedy: "ഒരു ആഴ്ച ഓരോ ദിവസവും 99 ഇസ്മ് ജബ്ർ ചൊല്ലി ദുആ ചെയ്യുക.",
    },
    en: {
      shortTitle: "Will Happen on Time",
      result: "The matter will happen on time",
      body: "The matter will happen on time. No delay will occur.",
      remedy: "Recite Ya Jabbar 99 times daily for one week and supplicate.",
    },
  },
  {
    lq_id: 128,
    symbol: "ي",
    symbolName: "Ya",
    ml: {
      shortTitle: "ദുആയിൽ ശ്രദ്ധിക്കുക",
      result: "നിസ്കാരത്തിലും ദുആയിലും ശ്രദ്ധിക്കുക",
      body: "നിസ്കാരത്തിലും ദുആയിലും ശ്രദ്ധിക്കുക. ഫലം ലഭിക്കും.",
      remedy: "ദിവസവും ബിസ്മില്ല ചൊല്ലി കാര്യം ആരംഭിക്കുക.",
    },
    en: {
      shortTitle: "Focus on Prayer",
      result: "Focus on Salah and Dua",
      body: "Focus on Salah and Dua. Result will be obtained.",
      remedy: "Begin every matter daily by reciting Bismillah.",
    },
  },
];