// ═══════════════════════════════════════════════════════════════
// HOLY NAME KNOWLEDGE — CANONICAL SEED (99 Names of Allah)
// ═══════════════════════════════════════════════════════════════
// Reference KEYS ONLY for the independent Holy Names PDF Knowledge
// database. These are the matching targets — NOT imported PDF
// content. ALL descriptive info (Malayalam meaning, benefits,
// usage, method, warnings, references, notes) comes ONLY from
// uploaded PDFs (stored as HolyNameImportedSection child records).
//
// Sent to the seedHolyNameKnowledge backend function by the admin
// "Initialize 99 Names" button. The backend computes arabic_normalized
// and persists the records. Idempotent (skips existing name_ids).
// ═══════════════════════════════════════════════════════════════

// Each entry: { order, arabic_name, transliteration, meaning_en }
export const HOLY_NAME_SEED = [
  { order: 1, arabic_name: "الرَّحْمَنُ", transliteration: "Ar-Rahman", meaning_en: "The Beneficent" },
  { order: 2, arabic_name: "الرَّحِيمُ", transliteration: "Ar-Raheem", meaning_en: "The Merciful" },
  { order: 3, arabic_name: "الْمَلِكُ", transliteration: "Al-Malik", meaning_en: "The King" },
  { order: 4, arabic_name: "الْقُدُّوسُ", transliteration: "Al-Quddus", meaning_en: "The Most Holy" },
  { order: 5, arabic_name: "السَّلَامُ", transliteration: "As-Salam", meaning_en: "The Source of Peace" },
  { order: 6, arabic_name: "الْمُؤْمِنُ", transliteration: "Al-Mu'min", meaning_en: "The Guardian of Faith" },
  { order: 7, arabic_name: "الْمُهَيْمِنُ", transliteration: "Al-Muhaymin", meaning_en: "The Protector" },
  { order: 8, arabic_name: "الْعَزِيزُ", transliteration: "Al-Aziz", meaning_en: "The Almighty" },
  { order: 9, arabic_name: "الْجَبَّارُ", transliteration: "Al-Jabbar", meaning_en: "The Compeller" },
  { order: 10, arabic_name: "الْمُتَكَبِّرُ", transliteration: "Al-Mutakabbir", meaning_en: "The Majestic" },
  { order: 11, arabic_name: "الْخَالِقُ", transliteration: "Al-Khaliq", meaning_en: "The Creator" },
  { order: 12, arabic_name: "الْبَارِئُ", transliteration: "Al-Bari'", meaning_en: "The Maker" },
  { order: 13, arabic_name: "الْمُصَوِّرُ", transliteration: "Al-Musawwir", meaning_en: "The Fashioner" },
  { order: 14, arabic_name: "الْغَفَّارُ", transliteration: "Al-Ghaffar", meaning_en: "The Forgiver" },
  { order: 15, arabic_name: "الْقَهَّارُ", transliteration: "Al-Qahhar", meaning_en: "The Subduer" },
  { order: 16, arabic_name: "الْوَهَّابُ", transliteration: "Al-Wahhab", meaning_en: "The Bestower" },
  { order: 17, arabic_name: "الرَّزَّاقُ", transliteration: "Ar-Razzaq", meaning_en: "The Provider" },
  { order: 18, arabic_name: "الْفَتَّاحُ", transliteration: "Al-Fattah", meaning_en: "The Opener" },
  { order: 19, arabic_name: "الْعَلِيمُ", transliteration: "Al-'Alim", meaning_en: "The All-Knowing" },
  { order: 20, arabic_name: "الْقَابِضُ", transliteration: "Al-Qabid", meaning_en: "The Constrictor" },
  { order: 21, arabic_name: "الْبَاسِطُ", transliteration: "Al-Basit", meaning_en: "The Expander" },
  { order: 22, arabic_name: "الْخَافِضُ", transliteration: "Al-Khafid", meaning_en: "The Abaser" },
  { order: 23, arabic_name: "الرَّافِعُ", transliteration: "Ar-Rafi'", meaning_en: "The Exalter" },
  { order: 24, arabic_name: "الْمُعِزُّ", transliteration: "Al-Mu'izz", meaning_en: "The Honorer" },
  { order: 25, arabic_name: "الْمُذِلُّ", transliteration: "Al-Mudhill", meaning_en: "The Humiliator" },
  { order: 26, arabic_name: "السَّمِيعُ", transliteration: "As-Sami'", meaning_en: "The All-Hearing" },
  { order: 27, arabic_name: "الْبَصِيرُ", transliteration: "Al-Basir", meaning_en: "The All-Seeing" },
  { order: 28, arabic_name: "الْحَكَمُ", transliteration: "Al-Hakam", meaning_en: "The Judge" },
  { order: 29, arabic_name: "الْعَدْلُ", transliteration: "Al-'Adl", meaning_en: "The Just" },
  { order: 30, arabic_name: "اللَّطِيفُ", transliteration: "Al-Latif", meaning_en: "The Subtle One" },
  { order: 31, arabic_name: "الْخَبِيرُ", transliteration: "Al-Khabir", meaning_en: "The All-Aware" },
  { order: 32, arabic_name: "الْحَلِيمُ", transliteration: "Al-Halim", meaning_en: "The Forbearing" },
  { order: 33, arabic_name: "الْعَظِيمُ", transliteration: "Al-'Azim", meaning_en: "The Magnificent" },
  { order: 34, arabic_name: "الْغَفُورُ", transliteration: "Al-Ghafur", meaning_en: "The Forgiving" },
  { order: 35, arabic_name: "الشَّكُورُ", transliteration: "Ash-Shakur", meaning_en: "The Appreciative" },
  { order: 36, arabic_name: "الْعَلِيُّ", transliteration: "Al-'Ali", meaning_en: "The Most High" },
  { order: 37, arabic_name: "الْكَبِيرُ", transliteration: "Al-Kabir", meaning_en: "The Greatest" },
  { order: 38, arabic_name: "الْحَفِيظُ", transliteration: "Al-Hafiz", meaning_en: "The Preserver" },
  { order: 39, arabic_name: "الْمُقِيتُ", transliteration: "Al-Muqit", meaning_en: "The Maintainer" },
  { order: 40, arabic_name: "الْحَسِيبُ", transliteration: "Al-Hasib", meaning_en: "The Reckoner" },
  { order: 41, arabic_name: "الْجَلِيلُ", transliteration: "Al-Jalil", meaning_en: "The Majestic" },
  { order: 42, arabic_name: "الْكَرِيمُ", transliteration: "Al-Karim", meaning_en: "The Generous" },
  { order: 43, arabic_name: "الرَّقِيبُ", transliteration: "Ar-Raqib", meaning_en: "The Watchful" },
  { order: 44, arabic_name: "الْمُجِيبُ", transliteration: "Al-Mujib", meaning_en: "The Responsive" },
  { order: 45, arabic_name: "الْوَاسِعُ", transliteration: "Al-Wasi'", meaning_en: "The All-Encompassing" },
  { order: 46, arabic_name: "الْحَكِيمُ", transliteration: "Al-Hakim", meaning_en: "The Wise" },
  { order: 47, arabic_name: "الْوَدُودُ", transliteration: "Al-Wadud", meaning_en: "The Loving" },
  { order: 48, arabic_name: "الْمَجِيدُ", transliteration: "Al-Majid", meaning_en: "The Glorious" },
  { order: 49, arabic_name: "الْبَاعِثُ", transliteration: "Al-Ba'ith", meaning_en: "The Resurrector" },
  { order: 50, arabic_name: "الشَّهِيدُ", transliteration: "Ash-Shahid", meaning_en: "The Witness" },
  { order: 51, arabic_name: "الْحَقُّ", transliteration: "Al-Haqq", meaning_en: "The Truth" },
  { order: 52, arabic_name: "الْوَكِيلُ", transliteration: "Al-Wakil", meaning_en: "The Trustee" },
  { order: 53, arabic_name: "الْقَوِيُّ", transliteration: "Al-Qawiyy", meaning_en: "The Strong" },
  { order: 54, arabic_name: "الْمَتِينُ", transliteration: "Al-Matin", meaning_en: "The Firm" },
  { order: 55, arabic_name: "الْوَلِيُّ", transliteration: "Al-Waliyy", meaning_en: "The Protecting Friend" },
  { order: 56, arabic_name: "الْحَمِيدُ", transliteration: "Al-Hamid", meaning_en: "The Praiseworthy" },
  { order: 57, arabic_name: "الْمُحْصِي", transliteration: "Al-Muhsi", meaning_en: "The Appraiser" },
  { order: 58, arabic_name: "الْمُبْدِئُ", transliteration: "Al-Mubdi'", meaning_en: "The Originator" },
  { order: 59, arabic_name: "الْمُعِيدُ", transliteration: "Al-Mu'id", meaning_en: "The Restorer" },
  { order: 60, arabic_name: "الْمُحْيِي", transliteration: "Al-Muhyi", meaning_en: "The Giver of Life" },
  { order: 61, arabic_name: "الْمُمِيتُ", transliteration: "Al-Mumit", meaning_en: "The Bringer of Death" },
  { order: 62, arabic_name: "الْحَيُّ", transliteration: "Al-Hayy", meaning_en: "The Living" },
  { order: 63, arabic_name: "الْقَيُّومُ", transliteration: "Al-Qayyum", meaning_en: "The Self-Subsisting" },
  { order: 64, arabic_name: "الْوَاجِدُ", transliteration: "Al-Wajid", meaning_en: "The Perceiver" },
  { order: 65, arabic_name: "الْمَاجِدُ", transliteration: "Al-Majid", meaning_en: "The Illustrious" },
  { order: 66, arabic_name: "الْوَاحِدُ", transliteration: "Al-Wahid", meaning_en: "The One" },
  { order: 67, arabic_name: "الْأَحَدُ", transliteration: "Al-Ahad", meaning_en: "The Unique" },
  { order: 68, arabic_name: "الصَّمَدُ", transliteration: "As-Samad", meaning_en: "The Eternal" },
  { order: 69, arabic_name: "الْقَادِرُ", transliteration: "Al-Qadir", meaning_en: "The Capable" },
  { order: 70, arabic_name: "الْمُقْتَدِرُ", transliteration: "Al-Muqtadir", meaning_en: "The Powerful" },
  { order: 71, arabic_name: "الْمُقَدِّمُ", transliteration: "Al-Muqaddim", meaning_en: "The Expediter" },
  { order: 72, arabic_name: "الْمُؤَخِّرُ", transliteration: "Al-Mu'akhkhir", meaning_en: "The Delayer" },
  { order: 73, arabic_name: "الْأَوَّلُ", transliteration: "Al-Awwal", meaning_en: "The First" },
  { order: 74, arabic_name: "الْآخِرُ", transliteration: "Al-Akhir", meaning_en: "The Last" },
  { order: 75, arabic_name: "الظَّاهِرُ", transliteration: "Az-Zahir", meaning_en: "The Manifest" },
  { order: 76, arabic_name: "الْبَاطِنُ", transliteration: "Al-Batin", meaning_en: "The Hidden" },
  { order: 77, arabic_name: "الْوَالِي", transliteration: "Al-Wali", meaning_en: "The Governor" },
  { order: 78, arabic_name: "الْمُتَعَالِي", transliteration: "Al-Muta'ali", meaning_en: "The Most Exalted" },
  { order: 79, arabic_name: "الْبَرُّ", transliteration: "Al-Barr", meaning_en: "The Most Kind" },
  { order: 80, arabic_name: "التَّوَّابُ", transliteration: "At-Tawwab", meaning_en: "The Acceptor of Repentance" },
  { order: 81, arabic_name: "الْمُنْتَقِمُ", transliteration: "Al-Muntaqim", meaning_en: "The Avenger" },
  { order: 82, arabic_name: "الْعَفُوُّ", transliteration: "Al-'Afuww", meaning_en: "The Pardoner" },
  { order: 83, arabic_name: "الرَّؤُوفُ", transliteration: "Ar-Ra'uf", meaning_en: "The Compassionate" },
  { order: 84, arabic_name: "مَالِكُ الْمُلْكِ", transliteration: "Malik-ul-Mulk", meaning_en: "The Owner of All" },
  { order: 85, arabic_name: "ذُو الْجَلَالِ وَالْإِكْرَامِ", transliteration: "Dhu-l-Jalali wa-l-Ikram", meaning_en: "Lord of Majesty and Bounty" },
  { order: 86, arabic_name: "الْمُقْسِطُ", transliteration: "Al-Muqsit", meaning_en: "The Equitable" },
  { order: 87, arabic_name: "الْجَامِعُ", transliteration: "Al-Jami'", meaning_en: "The Gatherer" },
  { order: 88, arabic_name: "الْغَنِيُّ", transliteration: "Al-Ghaniyy", meaning_en: "The Self-Sufficient" },
  { order: 89, arabic_name: "الْمُغْنِي", transliteration: "Al-Mughni", meaning_en: "The Enricher" },
  { order: 90, arabic_name: "الْمَانِعُ", transliteration: "Al-Mani'", meaning_en: "The Preventer" },
  { order: 91, arabic_name: "الضَّارُّ", transliteration: "Ad-Darr", meaning_en: "The Distressor" },
  { order: 92, arabic_name: "النَّافِعُ", transliteration: "An-Nafi'", meaning_en: "The Benefactor" },
  { order: 93, arabic_name: "النُّورُ", transliteration: "An-Nur", meaning_en: "The Light" },
  { order: 94, arabic_name: "الْهَادِي", transliteration: "Al-Hadi", meaning_en: "The Guide" },
  { order: 95, arabic_name: "الْبَدِيعُ", transliteration: "Al-Badi'", meaning_en: "The Incomparable" },
  { order: 96, arabic_name: "الْبَاقِي", transliteration: "Al-Baqi", meaning_en: "The Everlasting" },
  { order: 97, arabic_name: "الْوَارِثُ", transliteration: "Al-Warith", meaning_en: "The Inheritor" },
  { order: 98, arabic_name: "الرَّشِيدُ", transliteration: "Ar-Rashid", meaning_en: "The Guide" },
  { order: 99, arabic_name: "الصَّبُورُ", transliteration: "As-Sabur", meaning_en: "The Patient" },
];