// ═══════════════════════════════════════════════════════════════
// KASHF AL-HAQA'IQ — PART 1: ALL 28 LUNAR MANSIONS
// Sources: pp.90-132 (PDFs 1-2), Two scholarly layers:
//   Layer 1: Sheikh Khalil + Sheikh Ibn Khambash (pp.95-114)
//   Layer 2: Hermes/Aristotle via Aristotle (pp.115-124)
//   Layer 3: Sheikh Zahir al-Ismaili (pp.126-132)
// ═══════════════════════════════════════════════════════════════

const SOURCE_AR = "كشف الحقائق";
const SOURCE_EN = "Kashf al-Haqa'iq";

// ── LAYER 1: Sheikh Khalili's 28 Mansions (pp.90-114) ──────────
export const MANSIONS_LAYER1 = [
  {
    id: "mansion_01_sharatayn",
    number: 1,
    name_ar: "الشرطين",
    name_en: "al-Sharatayn",
    page: 95,
    layer: "Sheikh Khalil + Sheikh Ibn Khambash",
    nature: "Nahs",
    zodiac: "Aries (Hamal)",
    best_saat: "Mars (al-Murikh)",
    arabic_text: `منزلة الشرطين : الزبرقان يقصد به القمر ويقصد حل بالأشراط في برج الحمل وأنها نحس لا يصلح فيها من الأعمال إلا ما يختص بأمور النساء مثل المحبة والعطف وما أشبه ذلك إلا النكاح أي الزواج فلا لأنه لن يكون بينهما فرح وتموت المرأة دون الستة أشهر ومن تقرب إلى زوجته في هذه المنزلة وقضى الله بينهما بولد فإنه يكون غلاما قتالا ومن زرع فيها يطيب حصاده ومن لبس ثوبا جديدا أو قطعة فإنه ينال ثيابا كثيرة ومن دخل الحرب فيها يغلب عدوه ويتخذه صديقا ومن يغرس الأشجار ويسقيها فأنه ينال خيرا كثيرا ومن ابتدأ فيها بشيء من الأعمال غير التي ذكرت في الأعلى فأنه يكون مذموما والمولود في هذه المنزلة يكون صاحب شر وغضب وحقد لا دين له ويكون شجاعا كثير الهمة ويقتل في آخر عمره وإذا استهل القمر في هذه المنزلة فأنه يهلك الدواب وخاصة البقر وتقضى حوائج الناس بهذا الشهر ومن ضلت له ضالة في هذه المنزلة ولم يكن نجمه الحمل لم يجدها ومن مرض في هذه المنزلة يطول مرضه وخيف عليه الموت`,
    suitable: "Women's affairs: love, affection. Farming, planting trees, new clothing (gains more). Battle (wins).",
    forbidden: "Marriage (wife dies within 6 months). Beginning new works not listed.",
    marriage_rule: "Forbidden — no joy between spouses, wife dies within 6 months",
    clothing_rule: "Allowed — gains many clothes",
    farming_rule: "Allowed — good harvest",
    born_in: "Brave, high-ambition, wrathful, irreligious; dies in battle",
    moon_rise: "Livestock die especially cattle; needs fulfilled",
    illness: "Long illness, danger of death",
    source: { book: SOURCE_AR, book_en: SOURCE_EN, page: 95 }
  },
  {
    id: "mansion_02_butayn",
    number: 2,
    name_ar: "البطين",
    name_en: "al-Butayn",
    page: 96,
    layer: "Sheikh Khalil + Sheikh Ibn Khambash",
    nature: "Saad",
    zodiac: "Aries (Hamal)",
    best_saat: "Mars + Venus",
    arabic_text: `منزلة البطين : إذا نزل القمر بمنزلة البطين فإنه يصلح لأعمال الرجال والنساء ويعمل فيها الطلسمات والبدء فيها بالصناعات والعدة مثل السيوف والرماح وغيرها من الأسلحة وعطف قلوب الملوك والأشراف وينطلق المأخوذ من النساء ويتخذ فيها الصديق ويعمل ما يصلح من المحبة وإن كانت لك حاجة فاطلبها في هذه المنزلة وكل عمل فيها صالح إلا الزواج لأن الزوج لا يعيش قبل المرأة إلا ثمانية أشهر وقيل يمكن الزواج فيها ولكن لا ينجب الذكور ومن تقرب إلى زوجته فيها تأتيه أنثى ذات عفة ومن زرع فيها يفسد زرعه وقت الحصاد ومن سافر فيها يكسب في ماله تجارة خصوصا أن كان سفره في البحر ولا ينصح بلبس الملابس الجديدة بها لأن ذلك قد يؤدي للموت أو المرض الشديد والمولود في هذه المنزلة يكون مباركا كاتم للأسرار كثير الجماع وهذا هو سبب موته وخير ساعاته المريخ والزهرة`,
    suitable: "Talismans, crafts (swords, spears, weapons), love works, making friends, seeking needs from kings.",
    forbidden: "Marriage (husband dies within 8 months, or no male children). New clothing (causes death/illness). Farming (crops fail at harvest).",
    marriage_rule: "Risky — husband dies within 8 months; possible but no male children",
    clothing_rule: "Forbidden — may cause death or serious illness",
    farming_rule: "Forbidden — crops fail at harvest",
    travel_rule: "Profitable, especially sea travel",
    born_in: "Blessed, secretive, very sexual (this causes his death)",
    source: { book: SOURCE_AR, book_en: SOURCE_EN, page: 96 }
  },
  {
    id: "mansion_03_thurayya",
    number: 3,
    name_ar: "الثريا",
    name_en: "al-Thurayya",
    page: 96,
    layer: "Sheikh Khalil + Sheikh Ibn Khambash",
    nature: "Saad",
    zodiac: "Taurus",
    best_saat: "Venus + Mars",
    arabic_text: `منزلة الثريا : إذا حل القمر بالثريا فإنها تصلح لخطبة النساء ومن سافر فيها ينال مبتغاه وتصلح للدخول على الملوك وطلب الحاجات وشراء الجواري وحل عقد السموم والتصلح للحرب والتجارة فيها رابحة وتصلح لكل الأعمال إلا الزواج لأن الزواج بها يكثر العلل بالمرأة ومن تقرب لزوجته فإنها تلد ذكرا حسن المنظر طويل القامة عريض الكفين شجاعا سخيا ومن لبس فيه جديد الثياب يفرح بلبسه لكن يحرق لباسه بالنار وخير ساعاته الزهرة والمريخ ومن ولد بهذه المنزلة يكون صالحا كثير الجماع وأقل ما يتزوج بثلاث نساء ويوافقه الزرع وإذا استهل القمر بهذه المنزلة فإن الخير يعم في الأسواق`,
    suitable: "Proposing marriage, travel (achieves goals), meeting kings, buying slaves, dissolving poisons, war, profitable trade, all works.",
    forbidden: "Marriage (increases woman's ailments).",
    marriage_rule: "Forbidden — wife gets many ailments",
    clothing_rule: "Allowed but clothes burn in fire",
    farming_rule: "Suitable",
    travel_rule: "Excellent — achieves goals",
    born_in: "Righteous, highly sexual, marries at least 3 women; farming suits him",
    moon_rise: "Goodness spreads in markets",
    source: { book: SOURCE_AR, book_en: SOURCE_EN, page: 96 }
  },
  {
    id: "mansion_04_dabaran",
    number: 4,
    name_ar: "الدبران",
    name_en: "al-Dabaran",
    page: 97,
    layer: "Sheikh Khalil + Sheikh Ibn Khambash",
    nature: "Nahs",
    zodiac: "Taurus",
    best_saat: "None specified",
    arabic_text: `منزلة الهقعة : إذا نزل القمر بهذه المنزلة فإنها صالحة للسفر ومن سافر فيها تعلم العلم وهي صالحة لتسليم الولد للمعلم ولا تصلح للبناء ولا للدخول على الملوك والكبراء ولا ينصح بالزواج فيها المزاجها بالنحوس والسعود وقيل ان المرض يكون كثيرا مع كثرة الأولاد وقلة الارزاق للعروس`,
    suitable: "Travel (learns knowledge), sending child to teacher.",
    forbidden: "Building, entering kings, marriage not recommended.",
    marriage_rule: "Not recommended — mixed nahs/saad",
    farming_rule: "Crops ripen early then spoil at harvest",
    illness_rule: "Illness long and serious",
    source: { book: SOURCE_AR, book_en: SOURCE_EN, page: 97 }
  },
  {
    id: "mansion_05_haqaa",
    number: 5,
    name_ar: "الهقعة",
    name_en: "al-Haqaa",
    page: 97,
    layer: "Sheikh Khalil + Sheikh Ibn Khambash",
    nature: "Mixed",
    zodiac: "Gemini",
    best_saat: "Mercury",
    arabic_text: `منزلة الهقعة : إذا نزل القمر بهذه المنزلة فإنها صالحة للسفر ومن سافر فيها تعلم العلم وهي صالحة لتسليم الولد للمعلم ولا تصلح للبناء ولا للدخول على الملوك والكبراء ولا ينصح بالزواج فيها لامتزاجها بالنحوس والسعود ومن تقرب فيها لزوجته وقضى الله لهما بمولود تأتي له أبنة صالحة وإن كان المولود ذكرا فإنه يكون مذموما هذه المنزلة صالحة للبس الجديد ومن زرع فيها فإنه يستوي في أوله ويفسد عند الحصاد وخير ساعاته عطارد`,
    suitable: "Travel, learning, sending child to teacher, new clothing.",
    forbidden: "Building, entering kings/nobles.",
    marriage_rule: "Not recommended — if daughter: righteous; if son: blameworthy",
    clothing_rule: "Suitable for new clothing",
    farming_rule: "Grows well initially, spoils at harvest",
    source: { book: SOURCE_AR, book_en: SOURCE_EN, page: 97 }
  },
  {
    id: "mansion_06_hana",
    number: 6,
    name_ar: "الهنعة",
    name_en: "al-Han'a",
    page: 98,
    layer: "Sheikh Khalil + Sheikh Ibn Khambash",
    nature: "Mixed Saad",
    zodiac: "Gemini",
    best_saat: "Venus",
    arabic_text: `منزلة الهنعة : قيل إن نزل القمر بهذه المنزلة فإنها لا تصلح لتحليل السموم والسحر وتصلح للاتصال بالإخوان وغرس الأشجار والسفر ومن سافر فيها تنقضي حوائجه لكن يخاف عليه من الموت ومن تقرب إلى زوجنه فإنها تلد له غلاما وفي ولادته شك فاحذر أن تواقع امرأة في هذه المنزلة ومن تزوج فيها فإنه يغنم وتستوي أموره ولا تكون بينهما خصومة ومن ولد في هذه المنزلة يكون منحوسا فاسقا قاتلا كذابا لا يستحي من الناس ومن ضلت له ضالة لن يجدها أبدا ولو عاش عمر نوح ومن مرض فيها يطول مرضه ويخاف عليه من المرض والسحر وخير ساعاتها الزهرة`,
    suitable: "Connecting with brothers, planting trees, travel (needs fulfilled), marriage (wealth and harmony).",
    forbidden: "Dissolving poisons/magic.",
    marriage_rule: "Good — wealth and harmony, no quarrels",
    farming_rule: "Suitable",
    travel_rule: "Needs fulfilled but danger of death",
    born_in: "Wretched, immoral, murderer, liar, shameless",
    lost_item: "Never found, even if he lives as long as Noah",
    source: { book: SOURCE_AR, book_en: SOURCE_EN, page: 98 }
  },
  {
    id: "mansion_07_dhira",
    number: 7,
    name_ar: "الذراع",
    name_en: "al-Dhira",
    page: 98,
    layer: "Sheikh Khalil + Sheikh Ibn Khambash",
    nature: "Saad",
    zodiac: "Cancer",
    best_saat: "Venus + Mars",
    arabic_text: `منزلة الذراع : إن نزل القمر بهذه المنزلة فإنها تصلح لعمار الأرض وابتدأ الأعمال المحمودة والاجتماع في بيوت العبادة والصلاة والدعاء والدخول على الحكام والملوك والاتصال بالإخوان والأشراف وصالحة لأعمال المحبة ولجميع الأعمال ومن تزوج في هذه المنزلة فزوجته تكون أرملة فلا يطول فرحه يتصالح في بعض الأيام ويتخالف في بعض ومن تقرب إلى زوجته وقضى الله بولد بينهما فأن يكون غلاما حسن المنظر والخلق محبوبا عند الناس وله حظا عظيما في الحرب والأنعام والحرث ومن زرع في هذه المنزلة حصد قبل الناس ومن سافر فيها ينهب ماله ويقطع رأسه ومن غزا فيها يبلغ مراده ومن ضلت له ضالة وجدها بغرامة قليلة وخير ساعاته الزهرة والمريخ`,
    suitable: "Agriculture, good works, worship gatherings, entering rulers, brotherhood, love works, all good works, farming (early harvest), military campaigns.",
    forbidden: "Travel (wealth plundered, beheaded).",
    marriage_rule: "Wife is a widow — joy short-lived, sometimes agree, sometimes disagree",
    farming_rule: "Harvest before others",
    travel_rule: "Dangerous — wealth plundered, beheaded",
    source: { book: SOURCE_AR, book_en: SOURCE_EN, page: 98 }
  },
  {
    id: "mansion_08_nathra",
    number: 8,
    name_ar: "النثرة",
    name_en: "al-Nathra",
    page: 99,
    layer: "Sheikh Khalil + Sheikh Ibn Khambash",
    nature: "Mixed",
    zodiac: "Cancer",
    best_saat: "Mercury or Moon",
    arabic_text: `منزلة النثرة : قيل إذا نزل القمر في هذه المنزلة فإنها لا تصلح للعداوة والسموم ولا تدخل على أحد من الملوك ولا تتصل مع الاخوان وقيل جيدة للسفر والتزويج ولبس الجديد من الثياب ومن تزوج فيها فإنها جيدة ويكون بينهما اتفاق وقيل يفسد نكاحه ومن تقرب لزوجته وقضى الله بينهما بمولود فإنها تكون أنثى لا تطيع الرجال ومن زرع فيها يصيبه الضر في زراعته ولا يفرح به ومن سافر فيها فإنه ينال شرفا وسناء وإن استهل القمر بهذه المنزلة فإنه يكون المرض في جميع البلدان في العشر الأول والمولود بهذه المنزلة يكون عيشه رديا ويبغض ويكثر عياله ويكون صابرا حليما وخير ساعاته عطار وقيل القمر`,
    suitable: "Travel, marriage, new clothing.",
    forbidden: "Enmity, poisons, entering kings, fraternal contacts.",
    marriage_rule: "Good but contradictory opinions — some say harmony, others say ruined",
    farming_rule: "Causes harm to crops",
    born_in: "Poor life, hated, many children, patient and wise",
    source: { book: SOURCE_AR, book_en: SOURCE_EN, page: 99 }
  },
  {
    id: "mansion_09_tarf",
    number: 9,
    name_ar: "الطرف",
    name_en: "al-Tarf",
    page: 100,
    layer: "Sheikh Khalil + Sheikh Ibn Khambash",
    nature: "Nahs",
    zodiac: "Leo",
    best_saat: "Saturn + Jupiter",
    arabic_text: `منزلة الطرف : إذا نزل القمر بهذه المنزلة فاعمل فيها العداوة والسموم ولا تشتر فيها الرقيق ولا الدواب ولا الحديد واحذر كل جديد ولا تدخل فيها على الملوك والأشراف والإخوان ولا تزرع ولا تحصد وقيل أيضا من زرع بهذه المنزلة يحصد بالفرح والسرور ومن سافر فيها يكسب ويغنم ويسلم ما وجد له ولا تلبس الجديد فمن لبس الجديد يغتم ويهتم ومن تزوج فيها فزوجته تكون محبة للزواج وكارهة لزوجها ومن تقرب من زوجته وقضى الله بمولود بينهما فإنها تكون أنثى طاهرة سليمة ومن ضلت له ضالة وجدها بلا تعب ومن مرض فمرضه من البرودة فليستعمل الأشياء الحارة والمولود بهذه المنزلة يكون صاحب مكر وخيانة وخير ساعاته زحل والمشتري`,
    suitable: "Enmity and poisons. Travel (profitable). Lost item found.",
    forbidden: "Buying slaves/animals/iron, new clothing, entering kings/brothers, farming/harvesting.",
    marriage_rule: "Wife loves marriage but hates husband",
    clothing_rule: "Forbidden — causes grief",
    farming_rule: "Contradictory — some say joyful harvest",
    illness_rule: "Cold illness — use hot things",
    born_in: "Deceitful and treacherous; OR may have good ending (contradictory)",
    source: { book: SOURCE_AR, book_en: SOURCE_EN, page: 100 }
  },
  {
    id: "mansion_10_jabha",
    number: 10,
    name_ar: "الجبهة",
    name_en: "al-Jabha",
    page: 101,
    layer: "Sheikh Khalil + Sheikh Ibn Khambash",
    nature: "Mixed",
    zodiac: "Leo",
    best_saat: "Mercury",
    arabic_text: `منزلة الجبهة : إذا ما حل القمر في هذه المنزلة قال الشيخ الخليلي في شرحه أنه لا تصلح إلا لابتدأ الأعمال والتنقل من مكان لمكان وتصلح لعقد السموم والسحر وحفر الآبار والزراعة والحصاد وشراء الرقيق والدواب ولا يتزوج فيها لأنها تورث العداوة ويصيبه نقصان المال والمرض الشديد ومن تقرب من زوجته يأتيه غلاما كالأسد ولا يصلح لبس الجديد فيها ومن ضلت له ضالة وجدها في الثلث الأول أما إن كان في الثلث الأخر لم يجدها إلا بعد تعب ومن مرض فيها فإن ذلك يكون بسبب السحر ومن سافر فيها يكسب مالا وينال عزا وجاها والمولود بها يكون خفيف الكلام ذو يؤذي وهو صاحب مكر وخديعة وان استهل الشهر بهذه المنزلة فإن الناس في ذلك الشهر صحيحون ولا يمرضون وخير ساعاته عطارد`,
    suitable: "Beginning works, moving places, poisoning/magic, well-digging, farming, harvesting, buying slaves/animals. Travel (earns money, honor, rank).",
    forbidden: "Marriage (causes enmity, financial loss, severe illness). New clothing.",
    marriage_rule: "Forbidden — enmity, financial loss, severe illness",
    farming_rule: "Suitable",
    illness_rule: "Caused by magic",
    born_in: "Sharp-tongued, hurtful, deceitful",
    moon_rise: "People healthy all month",
    source: { book: SOURCE_AR, book_en: SOURCE_EN, page: 101 }
  },
  {
    id: "mansion_11_zubra",
    number: 11,
    name_ar: "الزبرة",
    name_en: "al-Zubra",
    page: 102,
    layer: "Sheikh Khalil + Sheikh Ibn Khambash",
    nature: "Saad",
    zodiac: "Leo/Virgo",
    best_saat: "Venus",
    arabic_text: `منزلة الزبرة : إذا نزل القمر بهذه المنزلة فتصلح للطلسمات ويعمل فيه المحبة للملوك والأشراف والدخول عليهم وشراء الدواب وتدبير الحرب واستفتاح الأعمال والتزويج ولبس الجديد ومن تزوج فيها يغرم ما عنده من مال ولا يكفيه وقيل يهلك في قرب المرأة ومن تقرب إلى زوجته وقضى الله لهما بولد فأنه يكون شجاعا في الحرب عاجزا عن العمل والعلم ومن زرع فيها فإنه يحصد خير حصاد ومن سافر فيها خيف عليه سوء الخاتمة ويستعمل في هذه المنزلة الحديد والصفر وان استهل في هذه المنزلة فإنه يكون في الناس ضحك كثير ومن ضلت له ضالة لن يجدها ويخاف عليه أن يضيع له شيئا آخر ومن مرض بها يخاف عليه الخلط وعليه أن لا يلبس ثوبا جديدا فيها وإلا سرق كثير من ثيابه والمولود بها يكون سعيدا ويبغضه أقاربه وخير ساعاته الزهرة`,
    suitable: "Talismans, love for kings/nobles, entering them, buying animals, war planning, opening works, marriage, new clothing. Farming (excellent harvest). Materials: iron and brass.",
    forbidden: "Travel (danger of bad end). New clothing (many clothes stolen).",
    marriage_rule: "Ruins finances; alternatively said to cause death near wife",
    farming_rule: "Best possible harvest",
    travel_rule: "Fear of bad end",
    source: { book: SOURCE_AR, book_en: SOURCE_EN, page: 102 }
  },
  {
    id: "mansion_12_sarfa",
    number: 12,
    name_ar: "الصرفة",
    name_en: "al-Sarfa",
    page: 102,
    layer: "Sheikh Khalil + Sheikh Ibn Khambash",
    nature: "Mixed Nahs",
    zodiac: "Virgo",
    best_saat: "Venus + Mercury + Moon",
    arabic_text: `منزلة الصرفة : إذا نزل الصرفة في هذه المنزلة فإنها صالحة لتأسيس البنيان وكل ما جاء في منزلة الزبرة أيضا ومن تزوج فيها فأنه يكون بينهما محبة واتفاقا طويلا لكن يطول عليه الهم ومن تقرب إلى زوجته وقضى الله بينهما بولد فإنه يكون قتالا مكارا خداعا ومن يزرع فيها يصيبه تعب ولا يفرح بزرعه ومن سافر فيها يخاف عليه وإن استهل القمر بهذه المنزلة فإن الرسقة تكثر في كل مكان ومن ضلت له ضالة وجدها وخيف عليه الخصومة ومن مرض فيكون ذلك من الحرارة واليبوسة ويبرأ بعد طول الأيام ومن لبس الجديد فيها ينال ثيابا كثيرة والمولود بها يكون شرير النفس مذموم العقل كثير الهمة وخير ساعاته الزهرة وعطارد والقمر`,
    suitable: "Building foundations, all works from al-Zubra mansion. Marriage (long love and harmony). New clothing (gains many clothes).",
    forbidden: "Travel. Farming (hardship, no joy).",
    marriage_rule: "Long love and harmony but prolonged worry. Child: murderer, deceitful, trickster",
    farming_rule: "Hardship, no joy",
    illness_rule: "Heat and dryness — recovers after long time",
    born_in: "Evil-natured, blameworthy mind, high-ambition",
    source: { book: SOURCE_AR, book_en: SOURCE_EN, page: 102 }
  },
  {
    id: "mansion_13_awwa",
    number: 13,
    name_ar: "العواء",
    name_en: "al-Awwa",
    page: 103,
    layer: "Sheikh Khalil + Sheikh Ibn Khambash",
    nature: "Mixed Saad",
    zodiac: "Virgo",
    best_saat: "Saturn + Moon + Jupiter",
    arabic_text: `منزلة العواء : فإذا نزل القمر بهذه المنزلة فإنها تصلح لجميع الأعمال من الأدوية ومحبة النساء وتدبر الطريق يسافر فيها ويتجنب الأعداء ويعمر الأرض ويزرع ويغرس ويلبس فيها الثياب الجديدة ومن تزوج فيها يكون بينهما مودة وتبقى طويلا وتطيب الأمور ويكثر المال ويستوي نكاحه ومن تقرب إلى زوجته وقضى الله بينهما بولد فأنه يكون حسن المنظر كثير المال ومن لبس ثوبا جديدا تقضى حوائجه ومن زرع فيه يفرح بحصاده ومن سافر فيها نال الغنيمة وإن استهل الشهر بهذه المنزلة تكثر الدماميل وسقط الحوامل وتهلك الكثير من الدواب ومن ضلت له ضالة وجدها ومن مرض فيها فإن مرضه من اليبوسة ولكن يبرأ بإذن الله والمولود في هذه المنزلة يكون غير محب للناس وخير ساعاته زحل والقمر والمشتري`,
    suitable: "All works, medicine, love of women, travel (avoids enemies), agriculture, planting, new clothing, marriage (long love, harmony, wealth), farming (joyful harvest), travel (gains spoils).",
    forbidden: "Nothing specific forbidden.",
    marriage_rule: "Long love, harmony, wealth increases",
    clothing_rule: "Suitable — needs fulfilled",
    farming_rule: "Joyful harvest",
    moon_rise: "Abscesses multiply, miscarriages, many livestock die",
    born_in: "Dislikes people",
    source: { book: SOURCE_AR, book_en: SOURCE_EN, page: 103 }
  },
  {
    id: "mansion_14_simak",
    number: 14,
    name_ar: "السماك",
    name_en: "al-Simak",
    page: 104,
    layer: "Sheikh Khalil + Sheikh Ibn Khambash",
    nature: "Nahs",
    zodiac: "Virgo/Libra",
    best_saat: "Mercury",
    arabic_text: `منزلة السماك : واذا نزل القمر بهذه المنزلة فلا يصلح فيها إلا الفساد والعداوة والبغضاء والسموم وكل شيء يؤدي إلى فساد ولا تدخل فيه على الملوك ولا تشتري فيه الدواب ولا تسافر ولا تتزوج ولكن لبس الجديد فيه مبارك وقيل أن من تزوج في هذه المنزلة فأنه يكون في طاعة المرأة وتكون المرأة غير عفيفة وتدور بيوت الناس ومن تقرب إلى زوجته في هذه المنزلة وقضى بينهما بولد فإنه يفسد ويكون خبيثا مشئوما قليل العمر كثير الأولاد وقيل يخاف عليه سوء الخاتمة ومن زرع فيها يفسد زرعه ويصيبه الدود ومن سافر فيها قد لا يعود لوطنه أو يصيبه الغرق وقيل وفيل أن اللبن يكثر بهذه المنزلة وأن من ضلت له ضالة وجدها بلا تعب ويخاف على من يمرض بها أن يكون عليلا مدى الدهر وخير ساعاته عطارد`,
    suitable: "Corruption, enmity, hatred, deadly poisons. New clothing (blessed).",
    forbidden: "Entering kings, buying animals, travel, marriage, farming.",
    marriage_rule: "Man becomes dominated by woman; woman unchaste, visits others' homes",
    farming_rule: "Crops spoil, worms attack",
    travel_rule: "May not return home, or drowns",
    illness_rule: "Lifetime illness",
    source: { book: SOURCE_AR, book_en: SOURCE_EN, page: 104 }
  },
  {
    id: "mansion_15_ghafr",
    number: 15,
    name_ar: "الغفر",
    name_en: "al-Ghafr",
    page: 105,
    layer: "Sheikh Khalil + Sheikh Ibn Khambash",
    nature: "Saad (Airy)",
    zodiac: "Libra",
    best_saat: "Saturn + Sun",
    arabic_text: `منزلة الغفر : هذه المنزلة رياحية سعيدة وقيل لا خير فيها واذا نزل القمر بهذه المنزلة فيصلح لأعمال العطف واختلاط الاخوان وحفر الآبار والأنهار وتدبير الصنعة ويصلح فيها الزواج ولبس الجديد وجميع الأعمال الصالحة ومن تزوج فيها فإن المرأة تكون سامعة لزوجها مطيعة لأمره ومن تقرب الله إلى زوجته وقضى بينهما بولد فأنه يكون جماعا للمال ومن لبس ثوبا جديدا يطيب عيشه ومأكوله ومن زرع فيها فأن زرعه لا يستوي ولا يحصد منه شيئا ومن سافر فيها ينال شرفا ومنزلة رفيعة لكن يخاف عليه الموت وان استهل القمر بهذه المنزلة يعتدل العسل وتستوي الثمار إلا الأترج فإنه يفسد ومن ضلت له ضالة فإنه يغرم ولا يجدها أبدا ومن مرض فيها فيكون سبب المرض ريح من الجن والمولود بهذه المنزلة يكون حسن الحال حراثا غراسا سعيدا كثير النكاح وخير ساعاته زحل والشمس`,
    suitable: "Compassion works, fraternizing, well-digging, river-digging, craft management, marriage, new clothing, all good works. Travel (honor and high rank).",
    forbidden: "Farming (crops won't grow or be harvested). Lost item never found (with financial penalty).",
    marriage_rule: "Wife obedient and attentive",
    clothing_rule: "Excellent life and food",
    farming_rule: "Crops fail completely",
    illness_rule: "Caused by wind from jinn",
    born_in: "Good character, farmer/planter, happy, very sexual",
    source: { book: SOURCE_AR, book_en: SOURCE_EN, page: 105 }
  },
  {
    id: "mansion_16_iklil",
    number: 16,
    name_ar: "الإكليل",
    name_en: "al-Iklil",
    page: 106,
    layer: "Sheikh Khalil + Sheikh Ibn Khambash",
    nature: "Nahs",
    zodiac: "Scorpio",
    best_saat: "Saturn + Jupiter",
    arabic_text: `منزلة الإكليل : إذا نزل القمر بهذه المنزلة تصلح للعداوة والبغضاء والتفريق وكل ما كان مثل ذلك لا يصلح فيها من الأعمال إلا ما كان مثل ذلك ولا تدخل فيها على الملوك واحذر الشراكة فيها ومن تزوج فيها يعادي نفسه ويكثر همه وفكره إلا أن الزوجة تكون مطيعة لزوجها ومن تقر إلى زوجته فيها وقضى الله لهما بولد فأنه يكون غلاما سعيدا والمولود في هذه المنزلة يكون كثير الحركة ومن يزرع فيها يكون حصاده كزرعه بلا تعب أو نصب ومن سافر فيها فإنه يمرض أو يغرق وان استهل الشهر بهذه المنزلة تكون جيدة لاستواء الأصباغ ومن ضلت له ضالة وجدها بغرم ومن مرض فيها يكون من البرد والريح ومن لبس فيها الجديد سيجد العلم والحفظ وخير ساعاته زحل والمشتري`,
    suitable: "Enmity, hatred, separation. New clothing (gains knowledge and memory!).",
    forbidden: "Entering kings, partnerships.",
    marriage_rule: "Man torments himself, worries constantly; wife is obedient",
    farming_rule: "Equal to what was planted — no effort wasted",
    travel_rule: "Gets sick or drowns",
    illness_rule: "From cold and wind",
    clothing_rule: "Special benefit: gains knowledge and memorization!",
    source: { book: SOURCE_AR, book_en: SOURCE_EN, page: 106 }
  },
  {
    id: "mansion_17_qalb",
    number: 17,
    name_ar: "القلب",
    name_en: "al-Qalb",
    page: 107,
    layer: "Sheikh Khalil + Sheikh Ibn Khambash",
    nature: "Saad",
    zodiac: "Scorpio",
    best_saat: "Saturn + Jupiter",
    arabic_text: `منزلة القلب : إذا نزلها القمر لإصلاح ما أفسدته منزلة الإكليل وخير منها وتصلح للمودة وتأليف القلوب والاتصال بالإخوان والدخول على الملوك والاختلاط بالأشراف والنقل للعساكر وطلب العداوة وتدبير الصنعة والتزويج وكل عمل يؤدي إلى صالح سوى السفر ومن تزوج ولبس الجديد فيها يعطي الهيبة ومن تزوج فيها تكون زوجته زاهدة عابدة وأكثر ما تنجب البنات ومن تقرب إلى زوجته فيها وقضى الله بينهما بولد فإنه يكون سعيدا ومن زرع برا أو شعيرا فإنه يحصد أكثر الحصاد ومن سافر فيها خاطر خطرا عظيما وقد تنهب أمواله وإن استهل الشهر بها يكثر الخصب في البلدان ومن ضلت له ضاله وجدها بغرم قليل ومن مرض فيها فمرد ذلك الريد الذي يخرج من الضلوع ويبرأ إن شاء الله المولود بها يكون سعيدا وبها ولد المصطفى صلى الله عليه وسلم وخير ساعاته زحل والمشتري`,
    suitable: "Fixing what al-Iklil corrupted, love, uniting hearts, brotherhood, entering kings, mixing with nobles, army transfers, seeking enmity, craft management, marriage, all good works except travel. New clothing (gains awe/prestige).",
    forbidden: "Travel (great danger, wealth plundered).",
    marriage_rule: "Wife is devout worshipper, mostly bears daughters. Child: happy",
    farming_rule: "Wheat/barley — maximum harvest",
    born_in: "Happy (the Prophet Muhammad ﷺ was born in this mansion)",
    special: "Contains a talisman for reconciling disputants: write (مله) (يا كفكف يا صمد من غير شبيه فلا ريح وسفي يا صمد كفؤه) in a green bowl and give to the disputants to drink",
    source: { book: SOURCE_AR, book_en: SOURCE_EN, page: 107 }
  },
  {
    id: "mansion_18_shawla",
    number: 18,
    name_ar: "الشولة",
    name_en: "al-Shawla",
    page: 108,
    layer: "Sheikh Khalil + Sheikh Ibn Khambash",
    nature: "Mixed Nahs",
    zodiac: "Scorpio/Sagittarius",
    best_saat: "Mars",
    arabic_text: `منزلة الشولة : إذا نزل بها القمر لا تصلح إلا للفتن ومخاطرة الحرب والقتال وعقد الشهوة وتحليل الرجل عن المرأة والزراعات ويقيل أن من يزرع فيها يفسد زرعه ولغرس الأشجار ولا تلبس فيها الجديد ولا تدخل على الملوك ودع كل طريق ومن تزوج فيها ويكون بينهما آلفة وحبة وقيل : لا يدخل على إمراة أبدا ويطلقها قبل الجماع ومن قضى الله بينهما فإنه يكون غلاما طائعا لوالديه ومن سافر فيها خيف عليه سوء الخاتمة وان استهل بها تهلك الدواب لا سيما البقر ولا تهلك الإبل ولا الماعز ومن ضلت له ضالة وجدها بغرم كثير ومن مرض فيها فمرضه ممزوج ظاهره برد وباطنه حر ومن لبس فيها ثوب جديد كثر خصامه وأصابته حمى ودماميل وخير ساعاته المريخ ومن يولد بهذه المنزلة يكون شريرا لا يصيب الرأي`,
    suitable: "Strife, war, battles, binding passion (sexual compulsion), releasing man from woman, planting trees, farming (contradictory).",
    forbidden: "New clothing (quarrels and fever!), entering kings.",
    marriage_rule: "Contradictory: affection OR divorce before consummation",
    clothing_rule: "Forbidden — quarrels, fever, abscesses",
    farming_rule: "Contradictory opinions",
    travel_rule: "Fear of bad end",
    moon_rise: "Livestock die especially cattle; camels and goats safe",
    born_in: "Evil, poor judgement",
    source: { book: SOURCE_AR, book_en: SOURCE_EN, page: 108 }
  },
  {
    id: "mansion_19_naayim",
    number: 19,
    name_ar: "النعايم",
    name_en: "al-Naayim",
    page: 108,
    layer: "Sheikh Khalil + Sheikh Ibn Khambash",
    nature: "Saad",
    zodiac: "Sagittarius",
    best_saat: "Mars",
    arabic_text: `منزلة النعايم : إذا نزل القمر بها فممدوح لبس الثوب الجديد فيها وتصلح لأعمال المحبة والمودة والقبول والاختلاط بالملوك والاخوان والسفر والدواء والبناء واستعمال شراء الرقيق والدواب وشرب القوس والنشاب والسمر ومن تزوج فيها نال البركة وتكون زوجته مباركة طيبة وينعم بها ومن تقرب من زوجته بها وقضى الله بينهما بولد يكون غلاما قتالا خداعا للناس ولا يأتي بخير يشكو منه جميع الناس ويكسب المال الحرام ومن يزرع فيها يفرح بزرعه ومن سافر يتنعم في سفره ويكسب المال وإن استهل الشهر بها يكثر القتال لأنها منزلة القوس ومن مرض فيها فمرضه من السحر المدفون ومن لبس ثوبا جديدا يخشى عليه من العين والمولود فيها يكون سعيدا ميمونا حسن الحال كثير الرزق ويحتاج إليه الناس وخير ساعاته المريخ`,
    suitable: "New clothing (excellent!), love, acceptance, mixing with kings/brothers, travel, medicine, building, buying slaves/animals, archery, weapons, marriage (blessed wife).",
    forbidden: "Nothing specific forbidden.",
    marriage_rule: "Blessed wife, good and wholesome. Child: murderer and deceiver of people",
    clothing_rule: "Excellent but beware of evil eye",
    farming_rule: "Joyful harvest",
    moon_rise: "Much fighting — it is the mansion of the bow",
    born_in: "Happy, blessed, good character, rich, needed by people",
    source: { book: SOURCE_AR, book_en: SOURCE_EN, page: 108 }
  },
  {
    id: "mansion_20_balda",
    number: 20,
    name_ar: "البلدة",
    name_en: "al-Balda",
    page: 109,
    layer: "Sheikh Khalil + Sheikh Ibn Khambash",
    nature: "Nahs",
    zodiac: "Sagittarius/Capricorn",
    best_saat: "Jupiter + Mars",
    arabic_text: `منزلة البلدة : إذا نزل القمر بها تصلح لابتداء الأعمال والبناء وعمارتها وشراء الأرض وشراء الدواب والرقيق والزرع والتدبير لجميع الصنائع واحذر فيها اتخاذ الصديق وخلطة الاخوان ولبس الجديد ومن تزوج فيها كانت على غير عفة مفارقة لزوجها ومن تقرب إلى زوجها ورزقهما الله بولد يكون كثير الوسواس بخيلا وإن استهل بهذه المنزلة يخرب كثير من البيوت ومن ضلت ضالته وجدها ومن مرض فيها يبرأ بعد شدة ومن لبس فيها الجديد يخرش عليه الحكة والمرض وخير ساعاته المشتري والمريخ`,
    suitable: "Beginning works, building, agriculture, land purchase, buying animals/slaves, craft management.",
    forbidden: "Making friends, fraternizing, new clothing (causes itching and illness).",
    marriage_rule: "Wife unchaste, separates from husband",
    farming_rule: "Suitable",
    moon_rise: "Many houses destroyed",
    born_in: "Obsessive, miserly",
    source: { book: SOURCE_AR, book_en: SOURCE_EN, page: 109 }
  },
  {
    id: "mansion_21_saad_dhabih",
    number: 21,
    name_ar: "سعد الذابح",
    name_en: "Sa'd al-Dhabih",
    page: 110,
    layer: "Sheikh Khalil + Sheikh Ibn Khambash",
    nature: "Nahs",
    zodiac: "Capricorn",
    best_saat: "Sun + Moon",
    arabic_text: `منزلة الذابح : إذا حل القمر بهذه المنزلة تصلح للبغضاء والعداوة والسموم القاتلة ومذموم فيها الدخول على الملوك والأشراف وسفر البر وابتداء الأعمال ولبس الجديد وعواقب الأمور والأفعال وقيل أن من لبس فيها جديد الثياب أصابه جراح ومن تزوج فيها يفترقان ومن ولد فيها يكون متوسط الحال ويقتل آخر عمره لأنه البرج الذي ولد فيه هابيل ومن زرع يحصد لكن تصيبه سرقة خفيفة ومن طلب عدوه يظفر به حيث كان ومن ضلت له صالة لن يجدها ومن مرض فيها خيف عليه الموت وان استهل القمر بها اسقطت كثير من الحوامل ما في بطونها وخير ساعاته الشمس والقمر`,
    suitable: "Enmity, hatred, deadly poisons. Seeking enemy (finds them anywhere). Farming (good harvest with minor theft).",
    forbidden: "Entering kings, land travel, beginning works, new clothing (causes wounds). Marriage (separation).",
    marriage_rule: "Couple separates",
    farming_rule: "Good harvest but minor theft",
    moon_rise: "Many pregnant women miscarry",
    born_in: "Average condition, killed at end of life (mansion of Habil's birth)",
    source: { book: SOURCE_AR, book_en: SOURCE_EN, page: 110 }
  },
  {
    id: "mansion_22_saad_bula",
    number: 22,
    name_ar: "سعد بلع",
    name_en: "Sa'd Bula",
    page: 111,
    layer: "Sheikh Khalil + Sheikh Ibn Khambash",
    nature: "Mixed",
    zodiac: "Capricorn/Aquarius",
    best_saat: "None specified",
    arabic_text: `منزلة البلع : إذا نزل القمر بهذه المنزلة تكون صالحة للسموم القاتلة والتفريق ولا تصلح للتوفيق عن جميع الأعمال ومنزلة الجودة والرداءة وقيل أنها جيدة لابتداء الأعمال والسفر ولبس الجديد إلا أنه يرمد العينين ويخرج آخر لباسه إلا أنه يكثر المال عنده ومن زرع فيها فإنه يكسب زرعا كثيرا ومن سافر فيها ينال خيرا في سفره ومن ضلت له ضالة وجدها بغير تعب ومن مرض فيه يطول مرضه وقيل إن أستهل القمر فيها فإن النساء أكثرهن تلد البنين`,
    suitable: "Deadly poisons, separation. Beginning works, travel, new clothing (wealth increases but eye problems). Farming (abundant crops). Travel (gain).",
    forbidden: "Reconciliation and all good works.",
    clothing_rule: "Wealth increases but eye problems; last garment gets damaged",
    farming_rule: "Very abundant crops",
    moon_rise: "Women mostly give birth to boys",
    source: { book: SOURCE_AR, book_en: SOURCE_EN, page: 111 }
  },
  {
    id: "mansion_23_saad_saud",
    number: 23,
    name_ar: "سعد السعود",
    name_en: "Sa'd al-Su'ud",
    page: 111,
    layer: "Sheikh Khalil + Sheikh Ibn Khambash",
    nature: "Saad (Best for marriage)",
    zodiac: "Aquarius",
    best_saat: "None specified",
    arabic_text: `منزلة سعد السعود : إذا نزل القمر بهذه المنزلة تكون صالحة للمحبة والعطف والبيع والشراء والزرع والحصاد وتدبير الصنعة والاتصال بالملوك والتزويج ولبس الجديد والبنيان ومن تزوج فيها يكون زواجه مباركا وهي من أفضل المنازل للزواج ومن تقرب إلى زوجته فيها وقضى الله بينهما بولد فإنه يكون من ولاة الأمر إن كان من بيت ملك وإن كان من غير ذلك يكون كاسبا للمال ويحتاج إليه الناس ومن ولد فيها فإنه يكون مباركا ميمونا ومن زرع فيها يحصد حصادا يفرحه ومن سافر فيها يربح ويفرح في سفره ومن ضلت له ضالة وجدها في يومها ومن مرض فيها يصيبه الكمد وإن استهل بها فإنه يعرى الناس خير ومن لبس ثوبا جديدا بها يكثر ماله ويصح بدنه ولا يخاف عليه`,
    suitable: "Love, compassion, buying/selling, farming, harvesting, craft management, meeting kings, marriage (BEST mansion for marriage!), new clothing (wealth multiplies, health improves). Travel (profitable and joyful).",
    forbidden: "Nothing specific forbidden.",
    marriage_rule: "BEST mansion for marriage — blessed, wealth, obedient; child: if royalty becomes ruler, if not becomes wealthy and needed by all",
    clothing_rule: "Wealth multiplies, health improves, safe from harm",
    farming_rule: "Joyful harvest",
    travel_rule: "Profitable and joyful",
    born_in: "Blessed and auspicious",
    source: { book: SOURCE_AR, book_en: SOURCE_EN, page: 111 }
  },
  {
    id: "mansion_24_saad_akhbiya",
    number: 24,
    name_ar: "سعد الأخبية",
    name_en: "Sa'd al-Akhbiya",
    page: 112,
    layer: "Sheikh Khalil + Sheikh Ibn Khambash",
    nature: "Nahs",
    zodiac: "Aquarius/Pisces",
    best_saat: "None specified",
    arabic_text: `منزلة سعد الأخبية : إذا نزل القمر بهذه المنزلة فإنها تكون صالحة لمحبة الرجال والنساء والدخول على الملوك ومخاطبة الاخوان وطلب الضمان وإنفاذ الرسل والفتن ردية وهي للتزويج وكذلك للبس الجديد ومن تزوج فيها تكون زوجته مشؤومة لأهل الدار قبيحة الفعال ومن تقرب من زوجته وقضى الله لهما بولد يكون كاظم للغيض قليل الكلام ينال خيرا كثيرا ومن زرع فيها فسد زرعه ومن سافر فيها خيف عليه الغرق ومن ضلت له ضاله وجدها بطول زمان ومن مرض فيها يكون مرضه سحر مدفون وقيل إن استهل صلح الناس فيها`,
    suitable: "Love between men and women, entering kings, fraternal communication, sending messengers. New clothing, marriage.",
    forbidden: "Farming (crops spoil). Travel (danger of drowning).",
    marriage_rule: "Wife brings bad luck to household, does evil deeds",
    farming_rule: "Crops completely spoil",
    travel_rule: "Fear of drowning",
    illness_rule: "Caused by buried magic",
    born_in: "Controls anger, speaks little, gains much",
    source: { book: SOURCE_AR, book_en: SOURCE_EN, page: 112 }
  },
  {
    id: "mansion_25_fargh_muqaddam",
    number: 25,
    name_ar: "الفراغ المقدم",
    name_en: "al-Fargh al-Muqaddam",
    page: 112,
    layer: "Sheikh Khalil + Sheikh Ibn Khambash",
    nature: "Mixed (Saad with Nahs)",
    zodiac: "Aquarius/Pisces",
    best_saat: "Mercury",
    arabic_text: `منزلة الفراغ المقدم : إذا نزل القمر بهذه المنزلة فهي سعد غير مشوب بنحس صالحة لعطف القلوب والمحبة والإصلاح بالتهيجات الاثنين والدخول على الملوك والأشراف واتخاذ الصديق وابتداء الأعمال والسفر والفرقة وحفر الآبار وعمارة وغير صالحة للبساتين وشرب الدواء والشراكة ومن تزوج فيها فإنه يهتم ويغتم وتكون مشؤومة لأهلها قليلة البخت ومن تقرب من زوجته وقضى الله بينهما بولد يكون صبيح الوجه كثير الحياء ينال العلم والمال والشرف والأمر والنهي`,
    suitable: "Compassion, love, reconciliation, rousing two people (love stimulation), entering kings/nobles, making friends, beginning works, travel, separation, well-digging, building.",
    forbidden: "Gardens, drinking medicine, partnerships.",
    marriage_rule: "Man worried and sad; wife brings bad luck to household",
    born_in: "Handsome, very modest, gains knowledge, wealth, honor, authority",
    source: { book: SOURCE_AR, book_en: SOURCE_EN, page: 112 }
  },
  {
    id: "mansion_26_fargh_muakhkhar",
    number: 26,
    name_ar: "الفراغ المؤخر",
    name_en: "al-Fargh al-Muakhkhar",
    page: 113,
    layer: "Sheikh Khalil + Sheikh Ibn Khambash",
    nature: "Saad (with Nahs)",
    zodiac: "Pisces",
    best_saat: "None specified",
    arabic_text: `منزلة الفراغ المؤخر : إذا نزل القمر بهذه المنزلة تكون سعد مضروبة بنحس صالحة للعداوة والقطيعة وإخراج الدم وأخذ الشعر والاتصال بالإخوان والتزويج ولبس الجديد واتخاذ الصديق والتسليف للمال ومن تزوج فيها تكون زوجته سامعة لزوجها مطيعة وقيل يغتم ويهتم ومن تقرب إلى زوجته وقضى الله بينهما بولد فإنه يكون سعيدا يحرث الأرض كثير السفر قليل الأولاد ومن زرع فيها يغتم ويهتم ومن سافر فيها يكسب المال ويخاف عليه الغرق وإن استهل الشهر بها تكون ربح للمسافرين ومن ضلت له ضالة وجدها بغير غرامة بطول زمان ومن مرد فيها يكون مرضه من البرد ويبرأ ومن لبس ثوبا جديدا فإنه يفرح فرحا كثيرا وتكثر ثيابه والمولود فيها يكون مشؤما صاحب كبر وينال الشرف والمنزلة`,
    suitable: "Enmity, cutting off, bloodletting, hair removal, brotherhood, marriage, new clothing (great joy, many clothes), making friends, lending money. Travel (profitable).",
    forbidden: "Farming (grief and worry). Travel has drowning risk.",
    marriage_rule: "Wife obedient (OR man grieves); child: happy, farmer, traveler, few children",
    moon_rise: "Profitable for travelers",
    born_in: "Ill-omened, arrogant, but gains honor and rank",
    source: { book: SOURCE_AR, book_en: SOURCE_EN, page: 113 }
  },
  {
    id: "mansion_27_risha",
    number: 27,
    name_ar: "الرشا / بطن الحوت",
    name_en: "al-Risha / Batn al-Hut",
    page: 114,
    layer: "Sheikh Khalil + Sheikh Ibn Khambash",
    nature: "Saad",
    zodiac: "Pisces",
    best_saat: "Jupiter",
    arabic_text: `منزلة الرشا أو بطن الحوت : إذا نزل القمر بهذه المنزلة تكون صالحة للمحبة والمودة وتدبير الصنعة وطلاق الرجل عن المرأة والزرع والحصاد والسفر والاختلاط بالملوك واستفتاح الأعمال والتجارة والسلف وشرب الأدوية والدعاء والعلاج والتزويج ومن تزوج فيها ينال الفرح والسرور وتكون المرأة طيبة النفس ومن تقرب لزوجته وقضى الله بينهما بولد فإنه يكون حسن المنظر حسن الخلق كثير المال والرزق ومن زرع فيها يحصد بلا تعب ومن سافر فيها اغتنم غنيمة عظيمة وإن استهل الشهر فيها يستوي الزرع ويجود الصوف ومن ضلة له ضالة وجدها بلا تعب ومن مرض فيها فمرضه الريد ويبرأ ومن لبس ثوبا جديدا تنصلح أموره والمولود بها يكون سعيدا`,
    suitable: "Love, affection, craft management, releasing man from woman, farming, harvesting, travel (great gain), mixing with kings, opening works, trade, lending, drinking medicine, prayer, treatment, marriage.",
    forbidden: "Nothing specific forbidden.",
    marriage_rule: "Joy and happiness; wife good-natured; child: handsome, good-mannered, wealthy",
    clothing_rule: "Affairs improve",
    farming_rule: "Harvest without effort",
    travel_rule: "Great booty/gain",
    moon_rise: "Crops and wool excellent",
    born_in: "Happy",
    source: { book: SOURCE_AR, book_en: SOURCE_EN, page: 114 }
  },
  {
    id: "mansion_28_sharaatayn_hermes",
    number: 28,
    name_ar: "الشرطين (هرمس)",
    name_en: "al-Sharatayn — Hermes layer",
    page: 115,
    layer: "Hermes (via Aristotle)",
    nature: "Mixed",
    arabic_text: `الشريطين : إذا نزل القمر بالشريطين فاعمل فيها تهييج المحبة والمودة بالنساء ولا تلبس في يومها أو ليلتها ثوبا جديدا ولا تدخل فيها على الملوك ومن اتصل بهم عجلوه بالعقوبة وبغضوه ومن تزوج فيها تقع المحبة بين الزوجين وهذه المنزلة جيدة لشراء الدواب والزرع والغرس والبناء فيها عقبته محمودة ولا تأخذ فيها أخا فأنه لا يثبت ولا تشتري شيئا للتجارة فإن ذلك غير محمود العاقبة ولا تسافر ولا تكتال فيها غلتك ولا تستعمل فيها طلسم الدعوة ولا تدبير الصنعة ولا أشياء من أعمالها`,
    suitable: "Stirring love and affection with women. Marriage (love between spouses). Buying animals, farming, planting, building.",
    forbidden: "New clothing, entering kings, taking a brother (relationship won't last), buying for trade, travel, measuring grain, using talismans/invocations.",
    source: { book: SOURCE_AR, book_en: SOURCE_EN, page: 115 }
  }
];

// ── OPERATIONS TABLE (جدول الأعمال للمنازل, p.125) ──────────
export const MANSION_OPERATIONS_TABLE = {
  source: { book: "كشف الحقائق", book_en: "Kashf al-Haqa'iq", page: 125 },
  purpose_to_mansion: [
    { purpose_ar: "للمحبة", purpose_en: "Love", mansion: "البطين" },
    { purpose_ar: "للألفة", purpose_en: "Affection/Unity", mansion: "الثريا" },
    { purpose_ar: "للوصول", purpose_en: "Arrival/Achievement", mansion: "الدبران" },
    { purpose_ar: "للاجتماع", purpose_en: "Gathering", mansion: "الهنعة" },
    { purpose_ar: "للنصر", purpose_en: "Victory", mansion: "الذراع" },
    { purpose_ar: "للقبول", purpose_en: "Acceptance", mansion: "الزبرة" },
    { purpose_ar: "للأمن", purpose_en: "Safety/Security", mansion: "الغفر" },
    { purpose_ar: "للنصر (2)", purpose_en: "Victory (2)", mansion: "القلب" },
    { purpose_ar: "للفتح", purpose_en: "Opening/Success", mansion: "النعايم" },
    { purpose_ar: "الشفاء", purpose_en: "Healing", mansion: "سعد بلع" },
    { purpose_ar: "لحفظ النفس", purpose_en: "Self-Protection", mansion: "سعد السعود" },
    { purpose_ar: "المغاب", purpose_en: "Concealment", mansion: "سعد الأخبية" },
    { purpose_ar: "للعمل", purpose_en: "Work/Action", mansion: "الفرع المقدم" },
    { purpose_ar: "لقضاء الحاجات", purpose_en: "Fulfilling Needs", mansion: "الرشا" },
    { purpose_ar: "للبغض", purpose_en: "Hatred", mansion: "الشرطين" },
    { purpose_ar: "للعداوة", purpose_en: "Enmity", mansion: "الهقعة" },
    { purpose_ar: "للانفصال", purpose_en: "Separation", mansion: "النثرة" },
    { purpose_ar: "للفرقة", purpose_en: "Division", mansion: "الطرفة" },
    { purpose_ar: "للذل", purpose_en: "Humiliation", mansion: "الجبهة" },
    { purpose_ar: "للرد", purpose_en: "Repelling/Returning", mansion: "الصرفة" },
    { purpose_ar: "للخوف", purpose_en: "Fear/Terror", mansion: "العواء" },
    { purpose_ar: "للخصومة", purpose_en: "Dispute/Conflict", mansion: "السماك" },
    { purpose_ar: "لتسليط المرض", purpose_en: "Sending Illness", mansion: "الزبان" },
    { purpose_ar: "لإزالة الحمى", purpose_en: "Removing Fever", mansion: "الاكليل" },
    { purpose_ar: "لخلاص المسجون", purpose_en: "Releasing Prisoner", mansion: "الشولة" },
    { purpose_ar: "لخلاص الحال", purpose_en: "Improving Situation", mansion: "البلدة" },
    { purpose_ar: "لعزل العمال", purpose_en: "Dismissing Workers", mansion: "الذابح" },
    { purpose_ar: "لتسليط الفقر", purpose_en: "Sending Poverty", mansion: "الفرع المؤخر" },
  ]
};

// ── ZODIAC-TO-MANSION DISTRIBUTION TABLE (p.127) ──────────
export const ZODIAC_MANSION_TABLE = {
  source: { book: "كشف الحقائق", book_en: "Kashf al-Haqa'iq", page: 127 },
  scholar: "Sheikh Zahir bin Muhammad al-Ismaili",
  distribution: [
    { zodiac_ar: "الحمل", zodiac_en: "Aries", mansions: "الشرطين والبطين وثلث الثريا الأول" },
    { zodiac_ar: "الثور", zodiac_en: "Taurus", mansions: "ثلثي الثريا والدبران وثلثي الهقعة" },
    { zodiac_ar: "الجوزاء", zodiac_en: "Gemini", mansions: "ثلث الهقعة والهنعة والذراع" },
    { zodiac_ar: "السرطان", zodiac_en: "Cancer", mansions: "النثرة والطرفة وثلث الجبهة" },
    { zodiac_ar: "الأسد", zodiac_en: "Leo", mansions: "ثلثان الجبهة والزبرة وثلثي الصرفة" },
    { zodiac_ar: "العذراء (السنبلة)", zodiac_en: "Virgo", mansions: "ثلث الصرفة والعواء والسماك" },
    { zodiac_ar: "الميزان", zodiac_en: "Libra", mansions: "الغفر والزبانا وثلث الإكليل" },
    { zodiac_ar: "العقرب", zodiac_en: "Scorpio", mansions: "ثلثي الاكليل والقلب وثلثي الشولة" },
    { zodiac_ar: "القوس", zodiac_en: "Sagittarius", mansions: "ثلث الشولة والنعايم والبلدة" },
    { zodiac_ar: "الجدي", zodiac_en: "Capricorn", mansions: "سعد الذابح وسعد بلع وثلث سعد السعود" },
    { zodiac_ar: "الدلو", zodiac_en: "Aquarius", mansions: "ثلثي سعد السعود وسعد الأخبية وثلثي فرع المقدم" },
    { zodiac_ar: "الحوت", zodiac_en: "Pisces", mansions: "ثلث فرع المقدم والمؤخر وبطن الحوت (الرشا)" },
  ]
};

export default MANSIONS_LAYER1;