// ═══════════════════════════════════════════════════════════════
// METHOD 3 — ASMA-UL HUSNA WITH ADAD (INDEPENDENT DATABASE)
// ─────────────────────────────────────────────────────────────
// Source: "Asma ul Husna with Adad" reference table (Allah → As-Sabur).
// Exact Arabic spelling, exact ordering, exact Adad/Abjad value as
// supplied in the reference — used ONLY by Method 3.
// This database is completely independent from Method 1 / Method 2.
//
// `name`, `translit`, `adad` — UNCHANGED, used for calculation/matching.
// `vocalized` — fully vocalized (tashkeel) Arabic spelling, display only.
// `malayalam` — Malayalam meaning gloss, display only.
// ═══════════════════════════════════════════════════════════════
export const METHOD3_ASMA_UL_HUSNA_ADAD = [
  { name: "الله",                  translit: "Allah",            adad: 66,   vocalized: "اللَّه",                       malayalam: "എല്ലാ നാമങ്ങളും ഉൾക്കൊള്ളുന്ന പരമോന്നത നാഥൻ" },
  { name: "الرحمن",                translit: "Ar-Rahman",        adad: 298,  vocalized: "الرَّحْمَٰن",                    malayalam: "പരമകാരുണികൻ" },
  { name: "الرحيم",                translit: "Ar-Rahim",         adad: 258,  vocalized: "الرَّحِيم",                      malayalam: "കരുണാമയൻ" },
  { name: "الملك",                 translit: "Al-Malik",         adad: 90,   vocalized: "الْمَلِك",                       malayalam: "സർവ്വാധിപൻ" },
  { name: "القدوس",                translit: "Al-Quddus",        adad: 170,  vocalized: "الْقُدُّوس",                     malayalam: "പരിശുദ്ധൻ" },
  { name: "السلام",                translit: "As-Salam",         adad: 131,  vocalized: "السَّلَام",                      malayalam: "സമാധാനത്തിന്റെ ഉറവിടം" },
  { name: "المؤمن",                translit: "Al-Mu'min",        adad: 136,  vocalized: "الْمُؤْمِن",                     malayalam: "സുരക്ഷ നൽകുന്നവൻ" },
  { name: "المهيمن",               translit: "Al-Muhaymin",      adad: 145,  vocalized: "الْمُهَيْمِن",                   malayalam: "മേൽനോട്ടം വഹിക്കുന്ന സംരക്ഷകൻ" },
  { name: "العزيز",                translit: "Al-Aziz",          adad: 94,   vocalized: "الْعَزِيز",                      malayalam: "പ്രതാപവാൻ" },
  { name: "الجبار",                translit: "Al-Jabbar",        adad: 206,  vocalized: "الْجَبَّار",                     malayalam: "തകർന്നത് നന്നാക്കുന്ന സർവ്വശക്തൻ" },
  { name: "المتكبر",               translit: "Al-Mutakabbir",    adad: 662,  vocalized: "الْمُتَكَبِّر",                  malayalam: "മഹത്വത്തിനർഹൻ" },
  { name: "الخالق",                translit: "Al-Khaliq",        adad: 731,  vocalized: "الْخَالِق",                      malayalam: "സൃഷ്ടാവ്" },
  { name: "الباري",                translit: "Al-Bari'",         adad: 213,  vocalized: "الْبَارِئ",                      malayalam: "ന്യൂനതയില്ലാതെ സൃഷ്ടിക്കുന്നവൻ" },
  { name: "المصور",                translit: "Al-Musawwir",      adad: 336,  vocalized: "الْمُصَوِّر",                    malayalam: "രൂപം നൽകുന്നവൻ" },
  { name: "الغفار",                translit: "Al-Ghaffar",       adad: 1281, vocalized: "الْغَفَّار",                     malayalam: "അധികമായി പൊറുക്കുന്നവൻ" },
  { name: "القهار",                translit: "Al-Qahhar",        adad: 306,  vocalized: "الْقَهَّار",                     malayalam: "അജയ്യൻ" },
  { name: "الوهاب",                translit: "Al-Wahhab",        adad: 14,   vocalized: "الْوَهَّاب",                     malayalam: "പ്രതിഫലമില്ലാതെ ദാനം ചെയ്യുന്നവൻ" },
  { name: "الرزاق",                translit: "Ar-Razzaq",        adad: 308,  vocalized: "الرَّزَّاق",                     malayalam: "മഹാ ഉപജീവനം നൽകുന്നവൻ" },
  { name: "الفتاح",                translit: "Al-Fattah",        adad: 489,  vocalized: "الْفَتَّاح",                     malayalam: "വിജയത്തിന്റെ വാതിൽ തുറക്കുന്നവൻ" },
  { name: "العليم",                translit: "Al-'Alim",         adad: 150,  vocalized: "الْعَلِيم",                      malayalam: "സർവ്വജ്ഞൻ" },
  { name: "القابض",                translit: "Al-Qabid",         adad: 903,  vocalized: "الْقَابِض",                      malayalam: "ചുരുക്കുന്നവൻ" },
  { name: "الباسط",                translit: "Al-Basit",         adad: 72,   vocalized: "الْبَاسِط",                      malayalam: "വിശാലമാക്കുന്നവൻ" },
  { name: "الخافض",                translit: "Al-Khafid",        adad: 1481, vocalized: "الْخَافِض",                      malayalam: "താഴ്ത്തുന്നവൻ" },
  { name: "الرافع",                translit: "Ar-Rafi",          adad: 351,  vocalized: "الرَّافِع",                      malayalam: "ഉയർത്തുന്നവൻ" },
  { name: "المعز",                 translit: "Al-Mu'izz",        adad: 117,  vocalized: "الْمُعِزّ",                      malayalam: "ബഹുമാനം നൽകുന്നവൻ" },
  { name: "المذل",                 translit: "Al-Mudhill",       adad: 770,  vocalized: "الْمُذِلّ",                      malayalam: "അപമാനിതനാക്കുന്നവൻ" },
  { name: "السميع",                translit: "As-Sami",          adad: 180,  vocalized: "السَّمِيع",                      malayalam: "എല്ലാം കേൾക്കുന്നവൻ" },
  { name: "البصير",                translit: "Al-Basir",         adad: 302,  vocalized: "الْبَصِير",                      malayalam: "എല്ലാം കാണുന്നവൻ" },
  { name: "الحكم",                 translit: "Al-Hakam",         adad: 68,   vocalized: "الْحَكَم",                       malayalam: "അന്തിമ ന്യായാധിപൻ" },
  { name: "العدل",                 translit: "Al-'Adl",          adad: 104,  vocalized: "الْعَدْل",                       malayalam: "തികഞ്ഞ നീതിമാൻ" },
  { name: "اللطيف",                translit: "Al-Latif",         adad: 129,  vocalized: "اللَّطِيف",                      malayalam: "സൂക്ഷ്മജ്ഞനും ദയാലുവും" },
  { name: "الخبير",                translit: "Al-Khabir",        adad: 812,  vocalized: "الْخَبِير",                      malayalam: "ആഴത്തിൽ അറിയുന്നവൻ" },
  { name: "الحليم",                translit: "Al-Halim",         adad: 88,   vocalized: "الْحَلِيم",                      malayalam: "ക്ഷമാശീലൻ" },
  { name: "العظيم",                translit: "Al-Azim",          adad: 1020, vocalized: "الْعَظِيم",                      malayalam: "മഹോന്നതൻ" },
  { name: "الغفور",                translit: "Al-Ghafur",        adad: 1286, vocalized: "الْغَفُور",                      malayalam: "പൊറുക്കുന്നവൻ" },
  { name: "الشكور",                translit: "Ash-Shakur",       adad: 526,  vocalized: "الشَّكُور",                      malayalam: "നന്ദി അംഗീകരിക്കുന്നവൻ" },
  { name: "العلي",                 translit: "Al-Ali",           adad: 110,  vocalized: "الْعَلِيّ",                      malayalam: "അത്യുന്നതൻ" },
  { name: "الكبير",                translit: "Al-Kabir",         adad: 232,  vocalized: "الْكَبِير",                      malayalam: "മഹാൻ" },
  { name: "الحفيظ",                translit: "Al-Hafiz",         adad: 998,  vocalized: "الْحَفِيظ",                      malayalam: "സംരക്ഷിക്കുന്നവൻ" },
  { name: "المقيت",                translit: "Al-Muqit",         adad: 550,  vocalized: "الْمُقِيت",                      malayalam: "പോഷണം നൽകുന്നവൻ" },
  { name: "الحسيب",                translit: "Al-Hasib",         adad: 80,   vocalized: "الْحَسِيب",                      malayalam: "കണക്കെടുക്കുന്നവൻ" },
  { name: "الجليل",                translit: "Al-Jalil",         adad: 73,   vocalized: "الْجَلِيل",                      malayalam: "മഹത്വമുള്ളവൻ" },
  { name: "الكريم",                translit: "Al-Karim",         adad: 270,  vocalized: "الْكَرِيم",                      malayalam: "ഉദാരമനസ്കൻ" },
  { name: "الرقيب",                translit: "Ar-Raqib",         adad: 312,  vocalized: "الرَّقِيب",                      malayalam: "എപ്പോഴും നിരീക്ഷിക്കുന്നവൻ" },
  { name: "المجيب",                translit: "Al-Mujib",         adad: 55,   vocalized: "الْمُجِيب",                      malayalam: "പ്രാർത്ഥനയ്ക്ക് ഉത്തരം നൽകുന്നവൻ" },
  { name: "الواسع",                translit: "Al-Wasi",          adad: 137,  vocalized: "الْوَاسِع",                      malayalam: "എല്ലാം ഉൾക്കൊള്ളുന്ന വിശാലൻ" },
  { name: "الحكيم",                translit: "Al-Hakim",         adad: 78,   vocalized: "الْحَكِيم",                      malayalam: "ജ്ഞാനിയായവൻ" },
  { name: "الودود",                translit: "Al-Wadud",         adad: 20,   vocalized: "الْوَدُود",                      malayalam: "സ്നേഹമുള്ളവൻ" },
  { name: "المجيد",                translit: "Al-Majid",         adad: 57,   vocalized: "الْمَجِيد",                      malayalam: "മഹത്വമേറിയവൻ" },
  { name: "الباعث",                translit: "Al-Ba'ith",        adad: 573,  vocalized: "الْبَاعِث",                      malayalam: "ഉയിർത്തെഴുന്നേൽപ്പിക്കുന്നവൻ" },
  { name: "الشهيد",                translit: "Ash-Shahid",       adad: 319,  vocalized: "الشَّهِيد",                      malayalam: "എല്ലാറ്റിനും സാക്ഷിയായവൻ" },
  { name: "الحق",                  translit: "Al-Haqq",          adad: 108,  vocalized: "الْحَقّ",                        malayalam: "സമ്പൂർണ്ണ സത്യം" },
  { name: "الوكيل",                translit: "Al-Wakil",         adad: 66,   vocalized: "الْوَكِيل",                      malayalam: "ഭരമേൽപ്പിക്കപ്പെടേണ്ട കൈകാര്യകർത്താവ്" },
  { name: "القوي",                 translit: "Al-Qawiyy",        adad: 116,  vocalized: "الْقَوِيّ",                      malayalam: "പരമശക്തൻ" },
  { name: "المتين",                translit: "Al-Matin",         adad: 500,  vocalized: "الْمَتِين",                      malayalam: "ദൃഢനായവൻ" },
  { name: "الولي",                 translit: "Al-Waliyy",        adad: 46,   vocalized: "الْوَلِيّ",                      malayalam: "സംരക്ഷകനും മിത്രവും" },
  { name: "الحميد",                translit: "Al-Hamid",         adad: 62,   vocalized: "الْحَمِيد",                      malayalam: "എല്ലാ സ്തുതികൾക്കും അർഹൻ" },
  { name: "المحصي",                translit: "Al-Muhsi",         adad: 148,  vocalized: "الْمُحْصِي",                     malayalam: "എല്ലാം എണ്ണിത്തിട്ടപ്പെടുത്തുന്നവൻ" },
  { name: "المبدئ",                translit: "Al-Mubdi'",        adad: 56,   vocalized: "الْمُبْدِئ",                     malayalam: "ആദ്യമായി സൃഷ്ടിക്കുന്നവൻ" },
  { name: "المعيد",                translit: "Al-Mu'id",         adad: 124,  vocalized: "الْمُعِيد",                      malayalam: "വീണ്ടും സൃഷ്ടിക്കുന്നവൻ" },
  { name: "المحيي",                translit: "Al-Muhyi",         adad: 68,   vocalized: "الْمُحْيِي",                     malayalam: "ജീവൻ നൽകുന്നവൻ" },
  { name: "المميت",                translit: "Al-Mumit",         adad: 490,  vocalized: "الْمُمِيت",                      malayalam: "മരണം നൽകുന്നവൻ" },
  { name: "الحي",                  translit: "Al-Hayy",          adad: 18,   vocalized: "الْحَيّ",                        malayalam: "ശാശ്വത ജീവനുള്ളവൻ" },
  { name: "القيوم",                translit: "Al-Qayyum",        adad: 156,  vocalized: "الْقَيُّوم",                     malayalam: "സ്വയം നിലനിൽക്കുന്ന പരിപാലകൻ" },
  { name: "الواجد",                translit: "Al-Wajid",         adad: 14,   vocalized: "الْوَاجِد",                      malayalam: "എല്ലാം കണ്ടെത്തുന്നവൻ" },
  { name: "الماجد",                translit: "Al-Majid",         adad: 48,   vocalized: "الْمَاجِد",                      malayalam: "മഹത്വമുള്ളവൻ" },
  { name: "الواحد",                translit: "Al-Wahid",         adad: 19,   vocalized: "الْوَاحِد",                      malayalam: "ഏകനും അദ്വിതീയനും" },
  { name: "الصمد",                 translit: "As-Samad",         adad: 134,  vocalized: "الصَّمَد",                       malayalam: "എല്ലാവരും ആശ്രയിക്കുന്നവൻ" },
  { name: "القادر",                translit: "Al-Qadir",         adad: 305,  vocalized: "الْقَادِر",                      malayalam: "എല്ലാം ചെയ്യാൻ കഴിവുള്ളവൻ" },
  { name: "المقتدر",               translit: "Al-Muqtadir",      adad: 744,  vocalized: "الْمُقْتَدِر",                   malayalam: "സമ്പൂർണ്ണ ശക്തിയുള്ളവൻ" },
  { name: "المقدم",                translit: "Al-Muqaddim",      adad: 184,  vocalized: "الْمُقَدِّم",                    malayalam: "മുന്നിലാക്കുന്നവൻ" },
  { name: "المؤخر",                translit: "Al-Mu'akhkhir",    adad: 846,  vocalized: "الْمُؤَخِّر",                    malayalam: "പിന്നിലാക്കുന്നവൻ" },
  { name: "الأول",                 translit: "Al-Awwal",         adad: 37,   vocalized: "الْأَوَّل",                      malayalam: "ആദ്യമില്ലാത്ത ആദ്യത്തവൻ" },
  { name: "الآخر",                 translit: "Al-Akhir",         adad: 801,  vocalized: "الْآخِر",                        malayalam: "അവസാനമില്ലാത്ത അവസാനത്തവൻ" },
  { name: "الظاهر",                translit: "Az-Zahir",         adad: 1106, vocalized: "الظَّاهِر",                      malayalam: "സകലവും വെളിവാക്കുന്നവൻ" },
  { name: "الباطن",                translit: "Al-Batin",         adad: 62,   vocalized: "الْبَاطِن",                      malayalam: "മറഞ്ഞിരിക്കുന്നവൻ" },
  { name: "الوالي",                translit: "Al-Wali",          adad: 47,   vocalized: "الْوَالِي",                      malayalam: "സമ്പൂർണ്ണ ഭരണാധികാരി" },
  { name: "المتعالي",              translit: "Al-Muta'ali",      adad: 551,  vocalized: "الْمُتَعَالِي",                  malayalam: "എല്ലാറ്റിനും അതീതനായവൻ" },
  { name: "البر",                  translit: "Al-Barr",          adad: 202,  vocalized: "الْبَرّ",                        malayalam: "നന്മ ചൊരിയുന്നവൻ" },
  { name: "التواب",                translit: "At-Tawwab",        adad: 409,  vocalized: "التَّوَّاب",                     malayalam: "പശ്ചാത്താപം ആവർത്തിച്ച് സ്വീകരിക്കുന്നവൻ" },
  { name: "المنتقم",               translit: "Al-Muntaqim",      adad: 430,  vocalized: "الْمُنْتَقِم",                   malayalam: "അതിക്രമകാരികളോട് പ്രതികാരം ചെയ്യുന്നവൻ" },
  { name: "العفو",                 translit: "Al-'Afuww",        adad: 156,  vocalized: "الْعَفُوّ",                      malayalam: "പൂർണ്ണമായി മാപ്പ് നൽകുന്നവൻ" },
  { name: "الرؤوف",                translit: "Ar-Ra'uf",         adad: 292,  vocalized: "الرَّؤُوف",                      malayalam: "അതീവ ദയാലു" },
  { name: "مالك الملك",            translit: "Malik-al-Mulk",    adad: 212,  vocalized: "مَالِكُ الْمُلْك",               malayalam: "രാജ്യാധിപത്യത്തിന്റെ ഉടമ" },
  { name: "ذو الجلال والإكرام",    translit: "Dhu-al-Jalal wa-al-Ikram", adad: 1100, vocalized: "ذُو الْجَلَالِ وَالْإِكْرَام", malayalam: "മഹത്വത്തിന്റെയും ആദരവിന്റെയും ഉടമ" },
  { name: "المقسط",                translit: "Al-Muqsit",        adad: 209,  vocalized: "الْمُقْسِط",                     malayalam: "തികഞ്ഞ നീതി പുലർത്തുന്നവൻ" },
  { name: "الجامع",                translit: "Al-Jami'",         adad: 114,  vocalized: "الْجَامِع",                      malayalam: "എല്ലാം ഒരുമിച്ചു കൂട്ടുന്നവൻ" },
  { name: "الغني",                 translit: "Al-Ghani",         adad: 1060, vocalized: "الْغَنِيّ",                      malayalam: "ആരെയും ആശ്രയിക്കാത്ത ധനികൻ" },
  { name: "المغني",                translit: "Al-Mughni",        adad: 1100, vocalized: "الْمُغْنِي",                     malayalam: "മറ്റുള്ളവരെ ധനികരാക്കുന്നവൻ" },
  { name: "المعطي",                translit: "Al-Mu'ti",         adad: 129,  vocalized: "الْمُعْطِي",                     malayalam: "നൽകുന്നവൻ" },
  { name: "المانع",                translit: "Al-Mani'",         adad: 161,  vocalized: "الْمَانِع",                      malayalam: "തടയുന്നവൻ" },
  { name: "الضار",                 translit: "Ad-Darr",          adad: 1001, vocalized: "الضَّار",                        malayalam: "ദോഷം വരുത്താൻ കഴിവുള്ളവൻ" },
  { name: "النافع",                translit: "An-Nafi'",         adad: 201,  vocalized: "النَّافِع",                      malayalam: "ഗുണം ചെയ്യുന്നവൻ" },
  { name: "النور",                 translit: "An-Nur",           adad: 256,  vocalized: "النُّور",                        malayalam: "പ്രകാശത്തിന്റെ ഉറവിടം" },
  { name: "الهادي",                translit: "Al-Hadi",          adad: 20,   vocalized: "الْهَادِي",                      malayalam: "മാർഗ്ഗദർശകൻ" },
  { name: "البديع",                translit: "Al-Badi",          adad: 86,   vocalized: "الْبَدِيع",                      malayalam: "മാതൃകയില്ലാതെ സൃഷ്ടിക്കുന്നവൻ" },
  { name: "الباقي",                translit: "Al-Baqi",          adad: 113,  vocalized: "الْبَاقِي",                      malayalam: "ശാശ്വതനായവൻ" },
  { name: "الوارث",                translit: "Al-Warith",        adad: 707,  vocalized: "الْوَارِث",                      malayalam: "എല്ലാറ്റിന്റെയും അന്തിമ അവകാശി" },
  { name: "الرشيد",                translit: "Ar-Rashid",        adad: 614,  vocalized: "الرَّشِيد",                      malayalam: "സന്മാർഗ്ഗം കാണിക്കുന്നവൻ" },
  { name: "الصبور",                translit: "As-Sabur",         adad: 298,  vocalized: "الصَّبُور",                      malayalam: "അതീവ ക്ഷമാശീലൻ" },
];