// ═══════════════════════════════════════════════════════════════
// PLANTS & INGREDIENTS DICTIONARY — STANDALONE DATA
// Schema: ArabicName, EnglishName, MalayalamName, ScientificName,
//         DescriptionEnglish, DescriptionMalayalam,
//         UsesEnglish, UsesMalayalam, PageReference, SourcePage
// Completely isolated. Zero imports from any engine or lib file.
// ═══════════════════════════════════════════════════════════════

export const PLANT_CATEGORIES = [
  { id: 'all',    label: 'All',     arabic: 'الكل',     ml: 'എല്ലാം' },
  { id: 'herb',   label: 'Herbs',   arabic: 'الأعشاب',  ml: 'ഔഷധസസ്യം' },
  { id: 'spice',  label: 'Spices',  arabic: 'التوابل',  ml: 'സുഗന്ധദ്രവ്യം' },
  { id: 'resin',  label: 'Resins',  arabic: 'الصمغ',    ml: 'റെസിൻ' },
  { id: 'root',   label: 'Roots',   arabic: 'الجذور',   ml: 'വേര്' },
  { id: 'flower', label: 'Flowers', arabic: 'الأزهار',  ml: 'പൂക്കൾ' },
  { id: 'fruit',  label: 'Fruits',  arabic: 'الفواكه',  ml: 'ഫലം' },
  { id: 'seed',   label: 'Seeds',   arabic: 'البذور',   ml: 'വിത്ത്' },
  { id: 'oil',    label: 'Oils',    arabic: 'الزيوت',   ml: 'എണ്ണ' },
  { id: 'wood',   label: 'Woods',   arabic: 'الأخشاب',  ml: 'മരം' },
  { id: 'other',  label: 'Other',   arabic: 'أخرى',     ml: 'മറ്റുള്ളവ' },
];

export const PLANTS_DATA = [
  {
    id: 1,
    category: 'resin',
    ArabicName: 'العقاقيه',
    EnglishName: 'Acacia',
    MalayalamName: 'അക്കേഷ്യ',
    ScientificName: 'Acacia Senegal',
    DescriptionEnglish: 'A gum resin used medicinally to soothe irritated areas of the digestive tract. Boiled down and evaporated into an astringent medicine to stop excessive mucous discharge and hemorrhages. Later discovered to serve as a binder for medicinal pellets.',
    DescriptionMalayalam: 'ദഹനേന്ദ്രിയ ഭാഗങ്ങളിലെ ജ്വലനം ശമിപ്പിക്കാൻ ഉപയോഗിക്കുന്ന ഗം റെസിൻ. അമിതമായ ശ്ലേഷ്മ സ്രാവവും രക്തസ്രാവവും നിർത്തുന്ന ഔഷധം ഉണ്ടാക്കാൻ ഉപയോഗിക്കുന്നു.',
    UsesEnglish: 'Soothing digestive tract irritations; astringent for mucous discharge and hemorrhages; binder for medicinal pellets.',
    UsesMalayalam: 'ദഹനവ്യവസ്ഥ ശമനം; ശ്ലേഷ്മ, രക്തസ്രാവ നിയന്ത്രണം; ഔഷധ ഗുളിക ബൈൻഡർ.',
    PageReference: '23r-2',
    SourcePage: 193,
  },
  {
    id: 2,
    category: 'other',
    ArabicName: 'الحموضة',
    EnglishName: 'Acidic',
    MalayalamName: 'അമ്ലം',
    ScientificName: '',
    DescriptionEnglish: 'Refers to acidic substances added to medicines. Used to moisten the mouth and palate, to reduce acidity in the yellow bile and to prevent harm to the intestinal tract, whose nature was considered to be cold, dry and sinewy.',
    DescriptionMalayalam: 'മരുന്നുകളിൽ ചേർക്കുന്ന അമ്ല പദാർഥങ്ങൾ. വായും അണ്ണാക്കും നനയ്ക്കാനും മഞ്ഞ പിത്തത്തിലെ അമ്ലത കുറയ്ക്കാനും ഉപയോഗിക്കുന്നു.',
    UsesEnglish: 'Moisten the mouth and palate; reduce acidity in yellow bile; prevent harm to the intestinal tract.',
    UsesMalayalam: 'വായ്, അണ്ണാക്ക് നനവ്; മഞ്ഞ പിത്ത അമ്ലത കുറക്കൽ; കുടൽ സംരക്ഷണം.',
    PageReference: '25r-16',
    SourcePage: 193,
  },
  {
    id: 3,
    category: 'wood',
    ArabicName: 'عود',
    EnglishName: 'Agar Wood',
    MalayalamName: 'അഗർവുഡ്',
    ScientificName: 'Aquilera malaccensis',
    DescriptionEnglish: 'An aromatic wood known as aloe wood or agar wood. Appears on pages 7r and 4r-15. Used in fumigations.',
    DescriptionMalayalam: 'ആലൂ മരം അല്ലെങ്കിൽ അഗർ മരം എന്നറിയപ്പെടുന്ന സുഗന്ധ മരം. ധൂപ ആവശ്യങ്ങൾക്ക് ഉപയോഗിക്കുന്നു.',
    UsesEnglish: 'Used in fumigations.',
    UsesMalayalam: 'ധൂപ ആവശ്യങ്ങൾക്ക് ഉപയോഗിക്കുന്നു.',
    PageReference: '7r, 4r-15',
    SourcePage: 193,
  },
  {
    id: 4,
    category: 'herb',
    ArabicName: 'الفصفصا',
    EnglishName: 'Alfalfa',
    MalayalamName: 'അൽഫൽഫ',
    ScientificName: 'Medicago Satina',
    DescriptionEnglish: 'Appears on page 11v-13. Used in a tea to calm nerve endings, relieving the pain of arthritis and neuralgia. Also used to treat diseases of malnutrition or weight loss.',
    DescriptionMalayalam: 'നാഡി അഗ്രങ്ങൾ ശാന്തമാക്കാൻ ചായ രൂപത്തിൽ ഉപയോഗിക്കുന്നു. സന്ധിവാതം, നാഡീ വേദന ഒഴിവാക്കാൻ ഫലപ്രദം.',
    UsesEnglish: 'Tea to calm nerve endings; relieve arthritis and neuralgia pain; treat malnutrition and weight loss.',
    UsesMalayalam: 'നാഡി ശമനം; സന്ധിവാത, നാഡീ വേദന ആശ്വാസം; പോഷകക്കുറവ്, ഭാരക്കുറവ് ചികിത്സ.',
    PageReference: '11v-13',
    SourcePage: 193,
  },
  {
    id: 5,
    category: 'herb',
    ArabicName: 'صبر',
    EnglishName: 'Aloe Vera',
    MalayalamName: 'കറ്റാർവാഴ',
    ScientificName: 'Aloaceae',
    DescriptionEnglish: 'Appears on pages 15r-20 and 27r-13. An Arabic reference for the juices of all bitter plants, especially aloe vera juice. These juices were used in medicine as purges and tonics, as well as for wound healing.',
    DescriptionMalayalam: 'കൊടും കയ്പ്പേറിയ സസ്യ നീരുകൾ, പ്രത്യേകിച്ചും കറ്റാർ നീര്. ശുദ്ധീകരണ ഔഷധം, ടോണിക്ക്, മുറിവ് ഉണക്കൽ എന്നിവയ്ക്ക് ഉപയോഗിക്കുന്നു.',
    UsesEnglish: 'Purges and tonics; wound healing.',
    UsesMalayalam: 'ശുദ്ധീകരണ ഔഷധം; ടോണിക്ക്; മുറിവ് ഉണക്കൽ.',
    PageReference: '15r-20, 27r-13',
    SourcePage: 193,
  },
  {
    id: 6,
    category: 'seed',
    ArabicName: 'لوز',
    EnglishName: 'Almond',
    MalayalamName: 'ബദാം',
    ScientificName: 'Prunus dulcis',
    DescriptionEnglish: 'Appears on page 24r-4. Native to West and Central Asia, common in Palestine and Syria. One of the earliest recognized benefits was preventing intoxication. Used for kidney and bladder disorders, heartburn relief, skin cleansing, and as a component in medicinal ointments.',
    DescriptionMalayalam: 'പശ്ചിമ, മധ്യ ഏഷ്യ സ്വദേശി. ലഹരി തടയൽ, വൃക്ക, മൂത്രാശയ പ്രശ്നങ്ങൾ, നെഞ്ചെരിച്ചിൽ ശമനം, ചർമ്മ ശുദ്ധീകരണം എന്നിവയ്ക്ക് ഉപയോഗിക്കുന്നു.',
    UsesEnglish: 'Prevent intoxication; kidney and bladder disorders; heartburn relief; skin cleansing; medicinal ointment component; nutritional regimen with sesame, honey, and sugar.',
    UsesMalayalam: 'ലഹരി നിവാരണം; വൃക്ക, മൂത്രാശയ ചികിത്സ; നെഞ്ചെരിച്ചിൽ ശമനം; ചർമ്മ ശുദ്ധീകരണം; ഔഷധ മേൽ‌പ്പൂശൽ.',
    PageReference: '24r-4',
    SourcePage: 194,
  },
  {
    id: 7,
    category: 'flower',
    ArabicName: 'شقايق النعمان',
    EnglishName: 'Anemone',
    MalayalamName: 'അനിമോൺ',
    ScientificName: 'Anemone nemorosa',
    DescriptionEnglish: 'Appears on page 13v, lines 13 and 14. Applied externally for headaches, tertian agues and rheumatic gout. A decoction was highly recommended for the cure of leprosy.',
    DescriptionMalayalam: 'ബാഹ്യ പ്രയോഗം: തലവേദന, ത്രിദിന ജ്വരം, സന്ധിവാതം. കഷായം: കുഷ്ഠരോഗ ചികിത്സ.',
    UsesEnglish: 'Headaches; tertian agues; rheumatic gout (external); decoction for leprosy.',
    UsesMalayalam: 'തലവേദന; ത്രിദിന ജ്വരം; സന്ധിവാതം (ബാഹ്യ); കുഷ്ഠരോഗ കഷായം.',
    PageReference: '13v',
    SourcePage: 194,
  },
  {
    id: 8,
    category: 'herb',
    ArabicName: 'درونج',
    EnglishName: 'Arnica',
    MalayalamName: 'അർണിക്ക',
    ScientificName: 'Arnica montana',
    DescriptionEnglish: 'Appears on pages 10v-1 and 23r-1. Used for pain relief and against bruising.',
    DescriptionMalayalam: 'വേദന ശമനത്തിനും ചതവ് ഭേദമാക്കുന്നതിനും ഉപയോഗിക്കുന്നു.',
    UsesEnglish: 'Pain relief; against bruising.',
    UsesMalayalam: 'വേദന ശമനം; ചതവ് ഭേദം.',
    PageReference: '10v-1, 23r-1',
    SourcePage: 194,
  },
  {
    id: 9,
    category: 'resin',
    ArabicName: 'حلتيت / عروق الانجرن',
    EnglishName: 'Asafetida',
    MalayalamName: 'കായം',
    ScientificName: 'Ferula asafoetida',
    DescriptionEnglish: 'Appears on pages 5v, 18r, 21r, and 6v. Has certain medicinal uses; most commonly used as a digestive aid. Reputed to lessen flatulence. Helpful in asthma and bronchitis, and employed against hysteria and nervous afflictions.',
    DescriptionMalayalam: 'ദഹന സഹായി ആയി ഏറ്റവും കൂടുതൽ ഉപയോഗിക്കുന്ന ഔഷധം. വായുക്കുഴപ്പം കുറയ്ക്കുന്നു. ആസ്ത്മ, ബ്രോങ്കൈറ്റിസ്, ഹിസ്റ്റീരിയ, നാഡീ ദൗർബല്യം എന്നിവയ്ക്ക് ഉപകാരപ്രദം.',
    UsesEnglish: 'Digestive aid; reduce flatulence; asthma and bronchitis; hysteria and nervous afflictions.',
    UsesMalayalam: 'ദഹന സഹായം; വായുക്കുഴപ്പം കുറക്കൽ; ആസ്ത്മ, ബ്രോങ്കൈറ്റിസ്; ഹിസ്റ്റീരിയ, നാഡി ദൗർബല്യം.',
    PageReference: '5v, 18r, 21r, 6v',
    SourcePage: 194,
  },
  {
    id: 10,
    category: 'herb',
    ArabicName: 'الغار',
    EnglishName: 'Bay Leaves',
    MalayalamName: 'ബേ ഇല',
    ScientificName: 'Lauris nobilis',
    DescriptionEnglish: 'Found on page 10r-7. Used mainly to treat upper digestive tract disorders and to ease arthritic aches and pains.',
    DescriptionMalayalam: 'ഉപരി ദഹനേന്ദ്രിയ ക്രമക്കേടുകൾ ചികിത്സിക്കാനും സന്ധിവേദന ഒഴിവാക്കാനും ഉപയോഗിക്കുന്നു.',
    UsesEnglish: 'Upper digestive tract disorders; ease arthritic aches and pains.',
    UsesMalayalam: 'ദഹന ക്രമക്കേട് ചികിത്സ; സന്ധിവേദന ശമനം.',
    PageReference: '10r-7',
    SourcePage: 194,
  },
  {
    id: 11,
    category: 'fruit',
    ArabicName: 'الكاد',
    EnglishName: 'Betal Palm Nut',
    MalayalamName: 'അടക്ക',
    ScientificName: 'Areca catechu',
    DescriptionEnglish: 'Found on page 25r-15. Used medicinally to remove tapeworms and other digestive parasites.',
    DescriptionMalayalam: 'ടേപ്പ്‌വേം, മറ്റ് ദഹന പരാദ ജീവികൾ നീക്കം ചെയ്യാൻ ഔഷധമായി ഉപയോഗിക്കുന്നു.',
    UsesEnglish: 'Remove tapeworms and other digestive parasites.',
    UsesMalayalam: 'ടേപ്പ്‌വേം, ദഹന പരാദ നിർമ്മാർജ്ജനം.',
    PageReference: '25r-15',
    SourcePage: 194,
  },
  {
    id: 12,
    category: 'other',
    ArabicName: 'مرارة',
    EnglishName: 'Bile',
    MalayalamName: 'പിത്തരസം',
    ScientificName: '',
    DescriptionEnglish: 'Various animal biles (snake, crow, wolf, cow, ram, viper, goat, crane) appear throughout the manuscript. Bile was an important part of ancient medicine in both Greece and Rome, considered one of the four humors. Used medicinally for thousands of years across many traditions including Chinese and Islamic medicine.',
    DescriptionMalayalam: 'പല മൃഗങ്ങളുടെ (സർപ്പം, കാക്ക, ചെന്നായ, പശു, ആട്, ക്രൗഞ്ചം) പിത്തരസം ഗ്രന്ഥത്തിൽ കാണുന്നു. ഗ്രീക്ക്, റോം ചികിത്സയിൽ നാലു ദ്രവ്യങ്ങളിൽ ഒന്ന്.',
    UsesEnglish: 'Cut thirst; bind the bowels; treat rheumatic pain, high fever, convulsions, hemorrhoids, bleeding gums, whooping cough, skin infections.',
    UsesMalayalam: 'ദാഹ ശമനം; കുടൽ ബന്ധനം; സന്ധിവേദന, പനി, ബേധം, മൂലം, ചർമ്മ അണുബാധ ചികിത്സ.',
    PageReference: '3r-20, 4r-12, 5v-5, 6r-10, 11r-14, 16v-6',
    SourcePage: 195,
  },
  {
    id: 13,
    category: 'seed',
    ArabicName: 'شونيز',
    EnglishName: 'Black Cumin / Black Onion Seeds',
    MalayalamName: 'കരിഞ്ജീരകം',
    ScientificName: 'Nigella sativa',
    DescriptionEnglish: 'Appears on pages 8v-4 and 19v-14. Black cumin or black onion seed. Traditionally used to stimulate the body\'s energy, aid recovery from fatigue and dispiritedness. Used for respiratory health, stomach and intestinal health, kidney and liver function, circulatory and immune system support, and general overall well-being.',
    DescriptionMalayalam: 'ഊർജ്ജ ഉത്തേജനം, ക്ഷീണ ദൂരീകരണം, ശ്വസന ആരോഗ്യം, ദഹനശക്തി, വൃക്ക, കരൾ പ്രവർത്തനം, രക്ത, പ്രതിരോധ ശക്തി വർദ്ധനവ്.',
    UsesEnglish: 'Stimulate energy; recovery from fatigue; respiratory health; stomach and intestinal health; kidney and liver function; circulatory and immune support; general well-being.',
    UsesMalayalam: 'ഊർജ്ജ ഉത്തേജനം; ക്ഷീണ ദൂരീകരണം; ശ്വസനാരോഗ്യം; ദഹനശക്തി; വൃക്ക, കരൾ ആരോഗ്യം; രക്ത, പ്രതിരോധ ശക്തി.',
    PageReference: '8v-4, 19v-14',
    SourcePage: '195-196',
  },
  {
    id: 14,
    category: 'herb',
    ArabicName: 'حزبق',
    EnglishName: 'Black Hellebore',
    MalayalamName: 'കറുത്ത ഹെല്ലിബോർ',
    ScientificName: 'Helleborus officinalis',
    DescriptionEnglish: 'Appears on pages 10v-2 and 19r-18. Used as a purgative in mania and proved of value in nervous disorders and hysteria. Administered in the form of a tincture with great care.',
    DescriptionMalayalam: 'ഭ്രാന്ത്, നാഡി ക്രമക്കേട്, ഹിസ്റ്റീരിയ ചികിത്സയ്ക്ക് ഉപയോഗിക്കുന്ന ശക്തമായ ഔഷധം. ടിൻചർ രൂപത്തിൽ ജാഗ്രതയോടെ നൽകണം.',
    UsesEnglish: 'Purgative in mania; nervous disorders; hysteria. Administered as a tincture with care.',
    UsesMalayalam: 'ഭ്രാന്ത് ശുദ്ധീകരണം; നാഡി ക്രമക്കേട്; ഹിസ്റ്റീരിയ.',
    PageReference: '10v-2, 19r-18',
    SourcePage: 196,
  },
  {
    id: 15,
    category: 'other',
    ArabicName: 'زبد الجمل',
    EnglishName: 'Camel Milk Butter',
    MalayalamName: 'ഒട്ടക പാൽ വെണ്ണ',
    ScientificName: '',
    DescriptionEnglish: 'Appears on pages 5r-7 and 7v-8. Because there was very little fat in camel milk, it was hard to make and was not eaten, but used as a base for medicines.',
    DescriptionMalayalam: 'ഒട്ടകപ്പാലിൽ കൊഴുപ്പ് വളരെ കുറവായതിനാൽ ഉണ്ടാക്കാൻ പ്രയാസം. ഭക്ഷണത്തിനല്ല, ഔഷധ അടിത്തറ ആയി ഉപയോഗിക്കുന്നു.',
    UsesEnglish: 'Used as a base for medicines.',
    UsesMalayalam: 'ഔഷധ അടിത്തറ.',
    PageReference: '5r-7, 7v-8',
    SourcePage: 196,
  },
  {
    id: 16,
    category: 'seed',
    ArabicName: 'حبة كافر',
    EnglishName: 'Camphor Seed',
    MalayalamName: 'കർപ്പൂര വിത്ത്',
    ScientificName: 'Cinnamomum Camphora / Laurus Camphora',
    DescriptionEnglish: 'Appears on page 23r-2. The manuscript refers specifically to camphor seed, which grows in China and Japan. The Arabs introduced its use in medicine to the West. Used in traditional medicine for poor circulation, painful joints, and breathing and sinus problems.',
    DescriptionMalayalam: 'ചൈനയിലും ജപ്പാനിലും വളരുന്ന കർപ്പൂര വിത്ത്. അറബികൾ ഇതിന്റെ ഉപയോഗം പടിഞ്ഞാറ് പരിചയപ്പെടുത്തി. രക്ത ചംക്രമണം, സന്ധി വേദന, ശ്വസന, സൈനസ് പ്രശ്നങ്ങൾക്ക് ഉപകരിക്കുന്നു.',
    UsesEnglish: 'Poor circulation; painful joints; breathing and sinus problems.',
    UsesMalayalam: 'രക്ത ചംക്രമണ ദൗർബല്യം; സന്ധി വേദന; ശ്വസന, സൈനസ് ചികിത്സ.',
    PageReference: '23r-2',
    SourcePage: 196,
  },
  {
    id: 17,
    category: 'herb',
    ArabicName: 'نبات القصب',
    EnglishName: 'Cane Plant',
    MalayalamName: 'കരിമ്പ് ചെടി',
    ScientificName: 'Saccharum officinarum',
    DescriptionEnglish: 'Found on pages 25r-9 and 6v-18, 34. The cane plant. Used as a sweetener for many bitter remedies.',
    DescriptionMalayalam: 'കയ്പ്പേറിയ ഔഷധങ്ങൾ മധുരമാക്കാൻ ഉപയോഗിക്കുന്ന കരിമ്പ് ചെടി.',
    UsesEnglish: 'Sweetener for bitter remedies.',
    UsesMalayalam: 'കയ്പ്പ് ഔഷധ മധുരീകരണം.',
    PageReference: '25r-9, 6v-18',
    SourcePage: 196,
  },
  {
    id: 18,
    category: 'root',
    ArabicName: 'عروق القصب',
    EnglishName: 'Cane Root',
    MalayalamName: 'കരിമ്പ് വേര്',
    ScientificName: 'Calamus aromaticus',
    DescriptionEnglish: 'Appears on pages 6v-18, 7v-7, 7v-8, and 26v-18. Most likely refers to the Sweet Flag (Calamus aromaticus of Dioscorides). Used to support the healing of wounds, scars and acne.',
    DescriptionMalayalam: 'ഡയോസ്കോറിഡീസിന്റെ കലാമസ് അരോമാറ്റിക്കസ് (Sweet Flag) ആകാൻ സാധ്യത. മുറിവ്, പാടുകൾ, മുഖക്കുരു ഭേദപ്പെടുത്തൽ.',
    UsesEnglish: 'Healing of wounds, scars and acne.',
    UsesMalayalam: 'മുറിവ്, പാടുകൾ, മുഖക്കുരു ഭേദം.',
    PageReference: '6v-18, 7v-7, 7v-8, 26v-18',
    SourcePage: 196,
  },
  {
    id: 19,
    category: 'oil',
    ArabicName: 'جندبادستر',
    EnglishName: 'Castor Oil',
    MalayalamName: 'ആവണക്കെണ്ണ',
    ScientificName: 'Ricinus Communis',
    DescriptionEnglish: 'Appears on pages 8r-7, 10v-1, 10v-2, and 21r-21. Used as a laxative, for intestinal inflammation and worms. In homeopathy for digestive complaints. In Asian medicine for joint pain, dry stool, indigestion, facial paralysis, boils and ulcers.',
    DescriptionMalayalam: 'വിരേചകം, കുടൽ ജ്വലനം, കൃമി നാശം. ദഹന പ്രശ്നങ്ങൾ, സന്ധി വേദന, മലബന്ധം, ദഹനക്കേട്, മുഖ തളർവാതം, ചെളിക്കുരു, വ്രണം ചികിത്സ.',
    UsesEnglish: 'Laxative; intestinal inflammation; worms; digestive complaints; joint pain; dry stool; indigestion; facial paralysis; boils and ulcers.',
    UsesMalayalam: 'വിരേചനം; കുടൽ ജ്വലനം; കൃമി; ദഹന പ്രശ്നം; സന്ധി വേദന; മലബന്ധം; ദഹനക്കേട്; മുഖ തളർവാതം.',
    PageReference: '8r-7, 10v-1, 10v-2, 21r-21',
    SourcePage: 197,
  },
  {
    id: 20,
    category: 'herb',
    ArabicName: 'الهندبا / اصفر سلم',
    EnglishName: 'Chicory',
    MalayalamName: 'ചിക്കറി',
    ScientificName: 'Cichorium intybus',
    DescriptionEnglish: 'Appears on pages 17r-16 and 17r-14. Used since the 1st century C.E. The Egyptians used it to purify the blood and liver. Taken internally for spleen problems, gallstones, jaundice, rheumatism, and loss of appetite. Also used as a laxative and to increase the flow of bile.',
    DescriptionMalayalam: 'ക്രി.ശ. ഒന്നാം നൂറ്റാണ്ട് മുതൽ ഉപയോഗത്തിൽ. രക്തം, കരൾ ശുദ്ധീകരണം. പ്ലീഹ, ഗാൾസ്റ്റോൺ, മഞ്ഞപ്പിത്തം, സന്ധിവാതം, വിശപ്പില്ലായ്മ ചികിത്സ.',
    UsesEnglish: 'Blood and liver purification; spleen problems; gallstones; jaundice; rheumatism; loss of appetite; laxative; increase bile flow.',
    UsesMalayalam: 'രക്ത, കരൾ ശുദ്ധീകരണം; പ്ലീഹ, ഗാൾസ്റ്റോൺ; മഞ്ഞപ്പിത്തം; സന്ധിവാതം; വിശപ്പില്ലായ്മ; വിരേചനം.',
    PageReference: '17r-16, 17r-14',
    SourcePage: 197,
  },
  {
    id: 21,
    category: 'root',
    ArabicName: 'الروند الصينى',
    EnglishName: 'Chinese Rhubarb',
    MalayalamName: 'ചൈനീസ് റൂബാർബ്',
    ScientificName: 'Rheum rhaponticum',
    DescriptionEnglish: 'Appears on page 3r-1. From northwest China and Tibet. A favorite remedy of early Persian and Arabian physicians for over 2000 years. Used for constipation and diarrhea depending on dosage. Also for boils, burns, and as a mouthwash for canker sores. Note: leaves and roots are toxic due to high oxalic acid content. Also appears as Long Rhubarb (الروند الطويل) on pages 4r-16 and 16r-6.',
    DescriptionMalayalam: 'വടക്കുപടിഞ്ഞാറൻ ചൈന, ടിബറ്റ് സ്വദേശി. 2000 വർഷത്തിലധികം ഉപയോഗം. ഡോസ് അനുസരിച്ച് മലബന്ധം / വയറിളക്കം ചികിത്സ. ചെളിക്കുരു, പൊള്ളൽ, വായ്‌പ്പുണ്ണ്. ഇലകളും വേരും വിഷകരം.',
    UsesEnglish: 'Constipation and diarrhea (dose-dependent); boils; burns; mouthwash for canker sores.',
    UsesMalayalam: 'മലബന്ധം/വയറിളക്കം; ചെളിക്കുരു; പൊള്ളൽ; വായ്‌പ്പുണ്ണ് ഗ്ലർഗ്ഗൾ.',
    PageReference: '3r-1, 4r-16, 16r-6',
    SourcePage: '197-198',
  },
  {
    id: 22,
    category: 'herb',
    ArabicName: 'كزبورة اليابسة',
    EnglishName: 'Cilantro (Dried)',
    MalayalamName: 'ഉണക്ക മല്ലി',
    ScientificName: 'Coriandrum sativum',
    DescriptionEnglish: 'Appears on page 10v-18. Used for the relief of anxiety and insomnia, also as a diuretic in combination with cumin seed.',
    DescriptionMalayalam: 'ഉത്കണ്ഠ, ഉറക്കക്കുറവ് ശമനം. ജീരകത്തോടൊപ്പം മൂത്ര ഉത്തേജനത്തിനും ഉപയോഗിക്കുന്നു.',
    UsesEnglish: 'Relief of anxiety and insomnia; diuretic (combined with cumin seed).',
    UsesMalayalam: 'ഉത്കണ്ഠ, ഉറക്കക്കുറവ്; മൂത്ര ഉത്തേജനം (ജീരകത്തോടൊപ്പം).',
    PageReference: '10v-18',
    SourcePage: 198,
  },
  {
    id: 23,
    category: 'spice',
    ArabicName: 'سليحة',
    EnglishName: 'Cinnamon',
    MalayalamName: 'ഇലവംഗം',
    ScientificName: 'Cinnamomum Cassia',
    DescriptionEnglish: 'Appears on page 26v-16. Used to treat diarrhea and kidney disorders, as well as to warm the body, promote circulation, and heal colds.',
    DescriptionMalayalam: 'വയറിളക്കം, വൃക്ക ക്രമക്കേട് ചികിത്സ. ശരീരം ചൂടാക്കൽ, രക്ത ചംക്രമണം, ജലദോഷം ഭേദപ്പെടുത്തൽ.',
    UsesEnglish: 'Diarrhea; kidney disorders; warm the body; promote circulation; heal colds.',
    UsesMalayalam: 'വയറിളക്കം; വൃക്ക ചികിത്സ; ശരീര ചൂട്; രക്ത ചംക്രമണം; ജലദോഷം.',
    PageReference: '26v-16',
    SourcePage: 198,
  },
  {
    id: 24,
    category: 'other',
    ArabicName: 'دهن كادير',
    EnglishName: 'Cloudy Salve',
    MalayalamName: 'മേഘ ലേഹ്യം',
    ScientificName: '',
    DescriptionEnglish: 'Found on pages 14v-6, 28-4, and 29v-1. Called cloudy (rose) salve or grease. Used as a base for other ingredients.',
    DescriptionMalayalam: 'മേഘ (റോസ്) ലേഹ്യം അല്ലെങ്കിൽ കൊഴുപ്പ് എന്ന് വിളിക്കുന്നു. മറ്റ് ഔഷധ ഘടകങ്ങളുടെ അടിത്തറ.',
    UsesEnglish: 'Base for other ingredients.',
    UsesMalayalam: 'ഔഷധ ഘടക അടിത്തറ.',
    PageReference: '14v-6, 28-4, 29v-1',
    SourcePage: 198,
  },
  {
    id: 25,
    category: 'spice',
    ArabicName: 'قرنفل',
    EnglishName: 'Cloves',
    MalayalamName: 'ഗ്രാമ്പൂ',
    ScientificName: 'Caryophyllus aromaticus',
    DescriptionEnglish: 'Appears on page 8v-7. Long history of use in natural medicine East and West. Used to treat nausea, indigestion, vomiting, and diarrhea. Also for infertility, war wounds, and toothaches.',
    DescriptionMalayalam: 'കിഴക്ക്, പടിഞ്ഞാറൻ പ്രകൃതി ചികിത്സയിൽ നദീം. ഓക്കാനം, ദഹനക്കേട്, ഛർദ്ദി, വയറിളക്കം. വന്ധ്യത, യുദ്ധ മുറിവ്, പല്ലുവേദന ചികിത്സ.',
    UsesEnglish: 'Nausea; indigestion; vomiting; diarrhea; infertility; war wounds; toothaches.',
    UsesMalayalam: 'ഓക്കാനം; ദഹനക്കേട്; ഛർദ്ദി; വയറിളക്കം; വന്ധ്യത; മുറിവ്; പല്ലുവേദന.',
    PageReference: '8v-7',
    SourcePage: 198,
  },
  {
    id: 26,
    category: 'seed',
    ArabicName: 'شونس',
    EnglishName: 'Corncockle',
    MalayalamName: 'കർൺകോക്കിൾ',
    ScientificName: 'Nigella sativa',
    DescriptionEnglish: 'Appears on page 19v-14. More commonly known as black cumin. Used for respiratory health, stomach and intestinal health, kidney and liver function, circulatory and immune support, and general well-being. Also used to treat abscesses and tumors of the abdomen, eyes, and liver, and highly efficacious against intestinal parasites.',
    DescriptionMalayalam: 'കരിഞ്ജീരകം എന്ന് കൂടുതൽ അറിയപ്പെടുന്നു. ശ്വസനം, ദഹനം, വൃക്ക, കരൾ, രക്ത, പ്രതിരോധ ആരോഗ്യം. വയർ, കണ്ണ്, കരൾ കഴലകൾ, കുടൽ പരാദ ചികിത്സ.',
    UsesEnglish: 'Respiratory, digestive, kidney, liver, circulatory, immune health; abscesses and tumors; intestinal parasites.',
    UsesMalayalam: 'ശ്വസന, ദഹന, വൃക്ക, കരൾ ആരോഗ്യം; കഴലകൾ; കുടൽ പരാദ നിർമ്മാർജ്ജനം.',
    PageReference: '19v-14',
    SourcePage: 198,
  },
  {
    id: 27,
    category: 'root',
    ArabicName: 'قسط',
    EnglishName: 'Costus Root',
    MalayalamName: 'കോഷ്ഠം',
    ScientificName: 'Saussurea iappa',
    DescriptionEnglish: 'Appears on page 13r-16. Used in the treatment of bronchial asthma, cholera, cough, dyspepsia, edema, gas, hiccup, jaundice, leprosy, phlegm, rheumatism, and skin diseases. Applied externally as an ointment for wounds, ulcerations, skin diseases, and tumors. Can also be used as a narcotic when smoked.',
    DescriptionMalayalam: 'ബ്രോങ്കിയൽ ആസ്ത്മ, കോളറ, ചുമ, ദഹനക്കേട്, നീർക്കെട്ട്, ഗ്യാസ്, ഓക്കൾ, മഞ്ഞപ്പിത്തം, കുഷ്ഠം, ശ്ലേഷ്മം, സന്ധിവാതം, ചർമ്മ രോഗം ചികിത്സ.',
    UsesEnglish: 'Bronchial asthma; cholera; cough; dyspepsia; edema; jaundice; leprosy; rheumatism; skin diseases; external ointment for wounds and tumors; narcotic when smoked.',
    UsesMalayalam: 'ആസ്ത്മ; കോളറ; ചുമ; ദഹനക്കേട്; നീർക്കെട്ട്; മഞ്ഞപ്പിത്തം; കുഷ്ഠം; സന്ധിവാതം; ചർമ്മ ചികിത്സ.',
    PageReference: '13r-16',
    SourcePage: 199,
  },
  {
    id: 28,
    category: 'other',
    ArabicName: 'ماء دينادى',
    EnglishName: 'Croton',
    MalayalamName: 'ക്രോട്ടൺ',
    ScientificName: 'Croton tiglium',
    DescriptionEnglish: 'Appears on page 25r-15. Used as a purgative.',
    DescriptionMalayalam: 'ശുദ്ധീകരണ ഔഷധം ആയി ഉപയോഗിക്കുന്നു.',
    UsesEnglish: 'Purgative.',
    UsesMalayalam: 'ശുദ്ധീകരണം.',
    PageReference: '25r-15',
    SourcePage: 199,
  },
  {
    id: 29,
    category: 'resin',
    ArabicName: 'شبان',
    EnglishName: "Dragon's Blood",
    MalayalamName: 'ഡ്രാഗൺസ് ബ്ലഡ്',
    ScientificName: 'Dracaena Cinnabari',
    DescriptionEnglish: "Appears on page 16r-6. The dragon's blood tree stretched from the Canaries through the Mediterranean to Southern Russia. Cinnabar extracted from leaves and barks was used as a pigment in paint and in treating burns, dysentery, stomach problems, and tightening loose teeth.",
    DescriptionMalayalam: 'കനറി ദ്വീപ് മുതൽ ദക്ഷിണ റഷ്യ വരെ വ്യാപിച്ചിരുന്ന വൃക്ഷം. ഇലകളിൽ നിന്നുള്ള ചായം, പൊള്ളൽ, ഒഴിച്ചിൽ, ഉദരരോഗം, പല്ല് ബലഹീനത ചികിത്സ.',
    UsesEnglish: 'Pigment in paint; burns; dysentery; stomach problems; tightening loose teeth.',
    UsesMalayalam: 'ചായം; പൊള്ളൽ; ഒഴിച്ചിൽ; ഉദര ചികിത്സ; പല്ല് ബലഹീനത.',
    PageReference: '16r-6',
    SourcePage: 199,
  },
  {
    id: 30,
    category: 'herb',
    ArabicName: 'بقل',
    EnglishName: 'Endive',
    MalayalamName: 'എൻഡൈവ്',
    ScientificName: 'Cichorium endivia',
    DescriptionEnglish: 'Appears on page 23v-13. First mentioned by Arabic physicians in the 10th and 11th centuries. A kind of wild dandelion known as Taraxcacon. Used as a general system tonic, especially for the urinary organs, and mainly to treat kidney and liver disorders.',
    DescriptionMalayalam: '10-11 നൂറ്റാണ്ടിലെ അറബി വൈദ്യന്മാർ ആദ്യം പരാമർശിച്ചു. ടരാക്സകോൺ എന്ന കാട്ടു ഡാൻഡെലിയോൺ. മൂത്രാശയ അവയവ ടോണിക്ക്; വൃക്ക, കരൾ ക്രമക്കേട്.',
    UsesEnglish: 'General system tonic; urinary organ tonic; kidney and liver disorders.',
    UsesMalayalam: 'പൊതു ടോണിക്ക്; മൂത്രാശയ ടോണിക്ക്; വൃക്ക, കരൾ ചികിത്സ.',
    PageReference: '23v-13',
    SourcePage: 199,
  },
  {
    id: 31,
    category: 'herb',
    ArabicName: 'فربيون',
    EnglishName: 'Euphorbia',
    MalayalamName: 'യൂഫോർബിയ',
    ScientificName: 'Euphorbia spp.',
    DescriptionEnglish: 'Appears on pages 4r-16, 5v-5, 8r-6, 29r-21, 20v-4, and 5v-15. Has more than two thousand species. Named after Greek surgeon Euphorbus who used the milky latex in potions. Main use was as a purgative.',
    DescriptionMalayalam: 'രണ്ടായിരത്തിലധികം ഇനങ്ങൾ. ഗ്രീക്ക് ശസ്ത്രക്രിയാ വിദഗ്ധൻ യൂഫോർബസിന്റെ പേരിൽ. പ്രധാന ഉപയോഗം ശുദ്ധീകരണം.',
    UsesEnglish: 'Purgative.',
    UsesMalayalam: 'ശുദ്ധീകരണ ഔഷധം.',
    PageReference: '4r-16, 5v-5, 8r-6, 29r-21, 20v-4, 5v-15',
    SourcePage: 199,
  },
  {
    id: 32,
    category: 'other',
    ArabicName: 'بعر التيس',
    EnglishName: 'Goat Excrement',
    MalayalamName: 'ആട്ടിൻ കാഷ്ഠം',
    ScientificName: '',
    DescriptionEnglish: 'Appears on page 5v, line 3. Mixed with goat hooves, euphorbia, saffron, and asafetida in compound remedies.',
    DescriptionMalayalam: 'ആട്ടിൻ കുളമ്പ്, യൂഫോർബിയ, കുങ്കുമം, കായം ചേർത്ത് ഉപയോഗിക്കുന്നു.',
    UsesEnglish: 'Component in compound remedies with goat hooves, euphorbia, saffron, and asafetida.',
    UsesMalayalam: 'സംയുക്ത ഔഷധ ഘടകം.',
    PageReference: '5v',
    SourcePage: 200,
  },
  {
    id: 33,
    category: 'other',
    ArabicName: 'شحم حية سودا',
    EnglishName: 'Fat — Black Snake',
    MalayalamName: 'കറുത്ത പാമ്പിന്റെ കൊഴുപ്പ്',
    ScientificName: '',
    DescriptionEnglish: 'Appears on page 16v-20. The fat of a black snake was used as a remedy for hemorrhoids.',
    DescriptionMalayalam: 'കറുത്ത പാമ്പിന്റെ കൊഴുപ്പ് മൂലരോഗ ചികിത്സ.',
    UsesEnglish: 'Remedy for hemorrhoids.',
    UsesMalayalam: 'മൂലരോഗ ചികിത്സ.',
    PageReference: '16v-20',
    SourcePage: 200,
  },
  {
    id: 34,
    category: 'other',
    ArabicName: 'شحم سنور',
    EnglishName: 'Fat — Cat',
    MalayalamName: 'പൂച്ചക്കൊഴുപ്പ്',
    ScientificName: '',
    DescriptionEnglish: 'Appears in the manuscript on page 13r. Animal fat used mainly for emollient purposes.',
    DescriptionMalayalam: 'പ്രധാനമായും മൃദൂകരണ ആവശ്യങ്ങൾക്ക് ഉപയോഗിക്കുന്നു.',
    UsesEnglish: 'Emollient purposes.',
    UsesMalayalam: 'മൃദൂകരണം.',
    PageReference: '13r',
    SourcePage: 200,
  },
  {
    id: 35,
    category: 'other',
    ArabicName: 'شحم حمار وحش',
    EnglishName: 'Fat — Wild Donkey',
    MalayalamName: 'കാട്ടു കഴുതക്കൊഴുപ്പ്',
    ScientificName: '',
    DescriptionEnglish: 'Appears on page 29r, lines 14 and 15. Animal fat used mainly for emollient purposes.',
    DescriptionMalayalam: 'പ്രധാനമായും മൃദൂകരണ ആവശ്യങ്ങൾക്ക് ഉപയോഗിക്കുന്നു.',
    UsesEnglish: 'Emollient purposes.',
    UsesMalayalam: 'മൃദൂകരണം.',
    PageReference: '29r',
    SourcePage: 200,
  },
  {
    id: 36,
    category: 'other',
    ArabicName: 'سمن البقر',
    EnglishName: 'Fat — Cow Tallow',
    MalayalamName: 'പശുവിൻ കൊഴുപ്പ്',
    ScientificName: '',
    DescriptionEnglish: 'Found on pages 10r-7, 18r-16, and 22r-10. Animal fat used mainly for emollient purposes.',
    DescriptionMalayalam: 'പ്രധാനമായും മൃദൂകരണ ആവശ്യങ്ങൾക്ക് ഉപയോഗിക്കുന്നു.',
    UsesEnglish: 'Emollient purposes.',
    UsesMalayalam: 'മൃദൂകരണം.',
    PageReference: '10r-7, 18r-16, 22r-10',
    SourcePage: 200,
  },
  {
    id: 37,
    category: 'other',
    ArabicName: 'سمن الغنم',
    EnglishName: 'Fat — Sheep Tallow',
    MalayalamName: 'ആടിൻ കൊഴുപ്പ്',
    ScientificName: '',
    DescriptionEnglish: 'Found on page 25r-10. Animal fat used mainly for emollient purposes.',
    DescriptionMalayalam: 'പ്രധാനമായും മൃദൂകരണ ആവശ്യങ്ങൾക്ക് ഉപയോഗിക്കുന്നു.',
    UsesEnglish: 'Emollient purposes.',
    UsesMalayalam: 'മൃദൂകരണം.',
    PageReference: '25r-10',
    SourcePage: 200,
  },
  {
    id: 38,
    category: 'resin',
    ArabicName: 'لبان / الكرنزون',
    EnglishName: 'Frankincense',
    MalayalamName: 'കുന്തിരിക്കം',
    ScientificName: 'Boswellia carterii',
    DescriptionEnglish: 'Appears on pages 15v and 16r-6. A natural antiseptic resin. Used in treatment of womb disorders (hot compresses soaked in frankincense tea applied to belly) and chronic respiratory illnesses (patient inhales fumes from burning resin).',
    DescriptionMalayalam: 'പ്രകൃതിദത്ത അണുനാശിനി. ഗർഭപാത്ര ക്രമക്കേട് (ചൂട് കമ്പ്രസ്), ദീർഘകാല ശ്വസന രോഗം (ദഹന ആവി ശ്വസനം) ചികിത്സ.',
    UsesEnglish: 'Natural antiseptic; womb disorders (hot compress); chronic respiratory illness (inhaling burning fumes).',
    UsesMalayalam: 'അണുനാശിനി; ഗർഭാശയ ചികിത്സ; ശ്വസന രോഗ ചികിത്സ.',
    PageReference: '15v, 16r-6',
    SourcePage: 200,
  },
  {
    id: 39,
    category: 'other',
    ArabicName: 'دماغ الضفدع',
    EnglishName: 'Frog Brain',
    MalayalamName: 'തവളയുടെ തലച്ചോർ',
    ScientificName: '',
    DescriptionEnglish: 'Found on page 25r-10. Used to treat hemorrhoids, wounds, bleeding and rheumatism.',
    DescriptionMalayalam: 'മൂലം, മുറിവ്, രക്തസ്രാവം, സന്ധിവാതം ചികിത്സ.',
    UsesEnglish: 'Hemorrhoids; wounds; bleeding; rheumatism.',
    UsesMalayalam: 'മൂലം; മുറിവ്; രക്തസ്രാവം; സന്ധിവാതം.',
    PageReference: '25r-10',
    SourcePage: 200,
  },
  {
    id: 40,
    category: 'resin',
    ArabicName: 'غلبله / عروق القنه',
    EnglishName: 'Galbanum',
    MalayalamName: 'ഗൽബനം',
    ScientificName: 'Ferula gummosa',
    DescriptionEnglish: 'Appears on pages 7v-7 and 17v-8. Used in healing remedies and in liturgical perfumes in Jewish prayers. Valued for its sedative and analgesic properties.',
    DescriptionMalayalam: 'ഉദ്ഗ്രഥനം, ജൂത പ്രാർഥന ധൂപ ദ്രവ്യം. ഉറക്ക ഔഷധ, വേദന ശമന ഗുണങ്ങൾ.',
    UsesEnglish: 'Healing remedies; liturgical perfume; sedative; analgesic.',
    UsesMalayalam: 'ഉദ്ഗ്രഥന ഔഷധം; ആരാധനാ ധൂപം; ഉറക്ക ഔഷധം; വേദന ശമനം.',
    PageReference: '7v-7, 17v-8',
    SourcePage: 200,
  },
  {
    id: 41,
    category: 'root',
    ArabicName: 'زنجبيل',
    EnglishName: 'Ginger',
    MalayalamName: 'ഇഞ്ചി',
    ScientificName: 'Zingiber officinale',
    DescriptionEnglish: 'Appears on page 23v-12. Name derives from Sanskrit Shringavera (horn body). Used in traditional medicine for more than 5,000 years. Used to treat stomachache, indigestion, motion sickness, fever, malaria, rheumatoid arthritis, and migraine. Also used to improve circulation and reduce fat deposits in the arteries.',
    DescriptionMalayalam: 'സംസ്കൃത ശ്രിംഗാവേര (കൊമ്പ് ശരീരം) എന്ന വാക്കിൽ നിന്ന്. 5000 വർഷം ഔഷധ ഉപയോഗം. ഉദര വേദന, ദഹനക്കേട്, ചലന രോഗം, ജ്വരം, മലേറിയ, സന്ധിവാതം, മൈഗ്രൈൻ. രക്ത ചംക്രമണ മെച്ചം, ധമനി കൊഴുപ്പ് കുറക്കൽ.',
    UsesEnglish: 'Stomachache; indigestion; motion sickness; fever; malaria; rheumatoid arthritis; migraine; improve circulation; reduce arterial fat deposits.',
    UsesMalayalam: 'ഉദര വേദന; ദഹനക്കേട്; ചലന രോഗം; ജ്വരം; മലേറിയ; സന്ധിവാതം; മൈഗ്രൈൻ; രക്ത ചംക്രമണം.',
    PageReference: '23v-12',
    SourcePage: 200,
  },
  {
    id: 42,
    category: 'other',
    ArabicName: 'ظفر التيس',
    EnglishName: 'Goat Hooves',
    MalayalamName: 'ആടിൻ കുളമ്പ്',
    ScientificName: '',
    DescriptionEnglish: 'Appears on page 5v, line 2. Hooves and excrement of male goats were used in the cure of illnesses caused by evil jinni residing in ruins and in the deserts.',
    DescriptionMalayalam: 'ആണ്‍ ആടിന്റെ കുളമ്പും കാഷ്ഠവും, ഭൂതോച്ചാടനം, ജിന്ന് ബാധ ചികിത്സ.',
    UsesEnglish: 'Cure of illnesses caused by evil jinni (combined with goat excrement).',
    UsesMalayalam: 'ജിന്ന് ബാധ ചികിത്സ.',
    PageReference: '5v',
    SourcePage: 200,
  },
  {
    id: 43,
    category: 'other',
    ArabicName: 'عصير العنب',
    EnglishName: 'Grape Wine',
    MalayalamName: 'മുന്തിരി വീഞ്ഞ്',
    ScientificName: '',
    DescriptionEnglish: 'Appears on page 24r-4. An alcoholic drink made from grapes or dry dates. The manuscript admonishes abstinence from it as part of the recommended nutritional treatment.',
    DescriptionMalayalam: 'മുന്തിരിയിൽ നിന്നോ ഉണക്ക ഈത്തപ്പഴത്തിൽ നിന്നോ ഉണ്ടാക്കുന്ന ലഹരി. ഗ്രന്ഥം പോഷകചികിത്സ ഭാഗമായി ഇതിൽ നിന്ന് വിരമിക്കാൻ ഉദ്ബോധിപ്പിക്കുന്നു.',
    UsesEnglish: 'Referenced in nutritional context; manuscript advises abstinence.',
    UsesMalayalam: 'പോഷകചികിത്സ; ഗ്രന്ഥം ഒഴിവാക്കാൻ ഉദ്ബോധിപ്പിക്കുന്നു.',
    PageReference: '24r-4',
    SourcePage: 200,
  },
  {
    id: 44,
    category: 'oil',
    ArabicName: 'زيت انفاق',
    EnglishName: 'Green Olive Oil',
    MalayalamName: 'പച്ച ഒലിവ് എണ്ണ',
    ScientificName: '',
    DescriptionEnglish: 'Appears on page 3v-16. Green olive oil used in cooking. Considered one of the healthier cooking oils.',
    DescriptionMalayalam: 'പാചകത്തിന് ഉപയോഗിക്കുന്ന പച്ച ഒലിവ് എണ്ണ. ആരോഗ്യകരമായ പാചക എണ്ണ.',
    UsesEnglish: 'Cooking oil.',
    UsesMalayalam: 'പാചക എണ്ണ.',
    PageReference: '3v-16',
    SourcePage: 200,
  },
  {
    id: 45,
    category: 'herb',
    ArabicName: 'حناء',
    EnglishName: 'Henna',
    MalayalamName: 'മൈലാഞ്ചി',
    ScientificName: 'Lawsonia inermis',
    DescriptionEnglish: 'Appears on pages 7v-8 and 14v-20. Traditionally used medicinally and cosmetically. Used for treatment of burns, ulcers of the mouth and stomach, and hot swellings. Mixed with butter or oil as a poultice, and as a treatment for scabies, mites and mange.',
    DescriptionMalayalam: 'ഔഷധ, സൗന്ദര്യ ആവശ്യങ്ങൾക്ക് പരമ്പരാഗതമായി ഉപയോഗിക്കുന്നു. പൊള്ളൽ, വായ്, ഉദര വ്രണം, ചൂട് നീർക്കെട്ട്, ചൊറി, ചേർ, കുഷ്ഠ ചർമ്മ രോഗം ചികിത്സ.',
    UsesEnglish: 'Burns; mouth and stomach ulcers; hot swellings; poultice (with butter or oil); scabies; mites; mange.',
    UsesMalayalam: 'പൊള്ളൽ; വായ്, ഉദര വ്രണം; ചൂട് നീർക്കെട്ട്; ചൊറി; ചേർ; ചർമ്മ രോഗം.',
    PageReference: '7v-8, 14v-20',
    SourcePage: 200,
  },
  {
    id: 46,
    category: 'oil',
    ArabicName: 'دهن الرند',
    EnglishName: 'Laurel Ointment',
    MalayalamName: 'ലോറൽ അരക്ക്',
    ScientificName: 'Laurus nobilis',
    DescriptionEnglish: 'Appears on page 9v-12. Ointment derived from the laurel plant. Used in the treatment of skin diseases.',
    DescriptionMalayalam: 'ലോറൽ ചെടിയിൽ നിന്ന് ഉണ്ടാക്കിയ അരക്ക്. ചർമ്മ രോഗ ചികിത്സ.',
    UsesEnglish: 'Skin diseases.',
    UsesMalayalam: 'ചർമ്മ രോഗ ചികിത്സ.',
    PageReference: '9v-12',
    SourcePage: 201,
  },
  {
    id: 47,
    category: 'herb',
    ArabicName: 'الاستدوش',
    EnglishName: 'Lavender',
    MalayalamName: 'ലാവൻഡർ',
    ScientificName: 'Lavandula angustifolia',
    DescriptionEnglish: 'Appears on page 13v-14. Used in ancient Arab medicine as an expectorant and antispasmodic. In ancient and medieval Europe as a wound herb and worm remedy.',
    DescriptionMalayalam: 'പ്രാചീന അറബ് ചികിത്സയിൽ കഫം നീക്കൽ, ഞരമ്പ് ശമനം. യൂറോപ്പിൽ മുറിവ് ഔഷധം, കൃമി നാശം.',
    UsesEnglish: 'Expectorant; antispasmodic; wound herb; worm remedy.',
    UsesMalayalam: 'കഫ നിർഗ്ഗമനം; ഞരമ്പ് ശമനം; മുറിവ് ഭേദം; കൃമി നാശം.',
    PageReference: '13v-14',
    SourcePage: 201,
  },
  {
    id: 48,
    category: 'herb',
    ArabicName: 'الكراث',
    EnglishName: 'Leek',
    MalayalamName: 'ലീക്ക്',
    ScientificName: 'Allium ampeloprasum var. porrum',
    DescriptionEnglish: 'Appears on pages 8r-9, 8v-5, and 18r-16. Widely used as a diuretic and laxative, with antiseptic and tonic properties.',
    DescriptionMalayalam: 'മൂത്ര ഉത്തേജകം, വിരേചകം. അണുനാശിനി, ടോണിക് ഗുണങ്ങൾ.',
    UsesEnglish: 'Diuretic; laxative; antiseptic; tonic.',
    UsesMalayalam: 'മൂത്ര ഉത്തേജനം; വിരേചനം; അണുനാശിനി; ടോണിക്.',
    PageReference: '8r-9, 8v-5, 18r-16',
    SourcePage: 201,
  },
  {
    id: 49,
    category: 'herb',
    ArabicName: 'ترنجان',
    EnglishName: 'Lemon Balm',
    MalayalamName: 'ലെമൺ ബാം',
    ScientificName: 'Melissa officinalis',
    DescriptionEnglish: 'Appears on page 19r-18. Used in all complaints from disordered nervous system. Carminative, diaphoretic and febrifuge.',
    DescriptionMalayalam: 'നാഡി ക്രമക്കേടിൽ നിന്നുള്ള എല്ലാ ആവലാതികൾക്കും ഉപയോഗിക്കുന്നു. വായുനാശം, വിയർ ഉത്തേജകം, ജ്വര നിവാരണം.',
    UsesEnglish: 'Nervous system disorders; carminative; diaphoretic; febrifuge.',
    UsesMalayalam: 'നാഡി ക്രമക്കേട്; വായുനാശം; വിയർ ഉത്തേജനം; ജ്വര നിവാരണം.',
    PageReference: '19r-18',
    SourcePage: 201,
  },
  {
    id: 50,
    category: 'herb',
    ArabicName: 'كشوث',
    EnglishName: 'Lesser Dodder',
    MalayalamName: 'ലെസ്സർ ഡോഡർ',
    ScientificName: 'Cuscuta epithymum',
    DescriptionEnglish: 'Appears on page 14v-5. A parasite on small plants; the version on thyme is most used medicinally. Traditionally used to treat liver, gallbladder, and spleen disorders. Also mild laxative, scurvy treatment, and for kidney deficiency symptoms: blurred vision, dizziness, tinnitus, and lower back pain.',
    DescriptionMalayalam: 'ചെറിയ സസ്യങ്ങളിൽ വളരുന്ന പരാദ സസ്യം. കരൾ, പിത്തസഞ്ചി, പ്ലീഹ ചികിത്സ. കുറ്റി വിരേചകം, സ്കർവി, വൃക്ക ദൗർബല്യ ലക്ഷണ (കാഴ്ച മങ്ങൽ, തലചുറ്റൽ, ടിന്നിറ്റസ്, അരക്കഴൽ) ചികിത്സ.',
    UsesEnglish: 'Liver, gallbladder, spleen disorders; mild laxative; scurvy; kidney deficiency (blurred vision, dizziness, tinnitus, lower back pain).',
    UsesMalayalam: 'കരൾ, പിത്തസഞ്ചി, പ്ലീഹ; വിരേചകം; സ്കർവി; വൃക്ക ദൗർബല്യം.',
    PageReference: '14v-5',
    SourcePage: 201,
  },
  {
    id: 51,
    category: 'root',
    ArabicName: 'عروق سوس',
    EnglishName: 'Licorice Root',
    MalayalamName: 'ഇരട്ടിമധുരം',
    ScientificName: 'Glycyrrhiza glabra',
    DescriptionEnglish: 'Appears on page 26r-20. Used in treatment of infections and mouth and peptic ulcers. An effective expectorant used since ancient times. Also a mild laxative and topical antiviral agent for shingles.',
    DescriptionMalayalam: 'അണുബാധ, വായ്, ആമാശയ വ്രണ ചികിത്സ. പ്രാചീന കാലം മുതൽ കഫ നിർഗ്ഗമനി. കുറ്റി വിരേചകം, ഹെർപ്പസ് ബാഹ്യ ഔഷധം.',
    UsesEnglish: 'Infections; mouth and peptic ulcers; expectorant; mild laxative; topical antiviral (shingles).',
    UsesMalayalam: 'അണുബാധ; വ്രണ ചികിത്സ; കഫ നിർഗ്ഗമനം; വിരേചകം; ഹെർപ്പസ് ചികിത്സ.',
    PageReference: '26r-20',
    SourcePage: 201,
  },
  {
    id: 52,
    category: 'spice',
    ArabicName: 'فلفل طويل',
    EnglishName: 'Long Pepper',
    MalayalamName: 'തിപ്പലി',
    ScientificName: 'Piper longum',
    DescriptionEnglish: 'Appears on page 23v-11. Long recognized as an ingredient for stimulating the appetite and as an aid in the relief of nausea.',
    DescriptionMalayalam: 'വിശപ്പ് ഉത്തേജനം, ഓക്കാനം ശമനം.',
    UsesEnglish: 'Stimulate appetite; relieve nausea.',
    UsesMalayalam: 'വിശപ്പ് ഉത്തേജനം; ഓക്കാനം ശമനം.',
    PageReference: '23v-11',
    SourcePage: 201,
  },
  {
    id: 53,
    category: 'root',
    ArabicName: 'عروق يبروح',
    EnglishName: 'Mandrake',
    MalayalamName: 'മാൻഡ്രേക്ക്',
    ScientificName: 'Mandragora officinarum',
    DescriptionEnglish: 'Found on pages 25v-9 and 17v-8. Used as a narcotic, an antispasmodic, and for its moderating effect.',
    DescriptionMalayalam: 'ലഹരി, ഞരമ്പ് ശമനം, ഉദ്ദീപനം ലഘൂകരണ ഔഷധം.',
    UsesEnglish: 'Narcotic; antispasmodic; moderating effect.',
    UsesMalayalam: 'ലഹരി ഔഷധം; ഞരമ്പ് ശമനം; ഉദ്ദീപക ലഘൂകരണം.',
    PageReference: '25v-9, 17v-8',
    SourcePage: 202,
  },
  {
    id: 54,
    category: 'wood',
    ArabicName: 'القرم',
    EnglishName: 'Mangrove',
    MalayalamName: 'കണ്ടൽ മരം',
    ScientificName: 'Avicenna germinas',
    DescriptionEnglish: 'Appears on page 4r-13. Used as a treatment for ringworm, sores and boils, and as a suppressant for coughs.',
    DescriptionMalayalam: 'ചൊറിക്കുത്ത്, ചെളിക്കുരു, ഉദ്ദ ചികിത്സ. ചുമ ദമനം.',
    UsesEnglish: 'Ringworm; sores and boils; cough suppressant.',
    UsesMalayalam: 'ചൊറിക്കുത്ത്; ചെളിക്കുരു; ചുമ ദമനം.',
    PageReference: '4r-13',
    SourcePage: 202,
  },
  {
    id: 55,
    category: 'herb',
    ArabicName: 'مزرنجوش',
    EnglishName: 'Marjoram',
    MalayalamName: 'മർജ്ജോറം',
    ScientificName: 'Origanum majorana',
    DescriptionEnglish: 'Appears on page 14v-5. Native to Middle East, North Africa and parts of India. Used by ancient Greeks for dropsy, convulsion, and narcotic poisons. Also treats asthma, rheumatism, toothache, indigestion, flatulence, epilepsy, and externally as liniment for bruises and sprains.',
    DescriptionMalayalam: 'ഗ്രീക്കുകാർ ജലശേഖരം, ഞരമ്പ് ആക്ഷേപം, ലഹരി വിഷ ചികിത്സ. ആസ്ത്മ, സന്ധിവാതം, പല്ലുവേദന, ദഹനക്കേട്, വാതം, അപസ്മാരം, ചതവ്, ഞരമ്പ് ഭ്രംശ ലേഹ്യം.',
    UsesEnglish: 'Dropsy; convulsion; narcotic poisons; asthma; rheumatism; toothache; indigestion; flatulence; epilepsy; liniment for bruises and sprains.',
    UsesMalayalam: 'ജലശേഖരം; ഞരമ്പ് ആക്ഷേപം; ആസ്ത്മ; സന്ധിവാതം; പല്ലുവേദന; ദഹനക്കേട്; അപസ്മാരം.',
    PageReference: '14v-5',
    SourcePage: 202,
  },
  {
    id: 56,
    category: 'resin',
    ArabicName: 'المصطقي / المصقا / علق رومي',
    EnglishName: 'Mastic',
    MalayalamName: 'മാസ്റ്റിക്',
    ScientificName: 'Pistacia lentiscus',
    DescriptionEnglish: 'Appears on pages 15v-13, 19v-14, and 20v-18. Used as medicine for gastrointestinal ailments since ancient times. Has antibacterial and antifungal properties. Traditionally chewed like gum in the Middle East; demonstrated to reduce bacterial plaque by up to 40%.',
    DescriptionMalayalam: 'ദഹനേന്ദ്രിയ ചികിത്സ. ആന്റിബാക്ടീരിയൽ, ആന്റിഫംഗൽ ഗുണങ്ങൾ. മദ്ധ്യപൂർവ്വ ദേശത്ത് ചവക്കുമ്പോൾ ദന്ത ബാക്ടീരിയ 40% കുറക്കും.',
    UsesEnglish: 'Gastrointestinal ailments; antibacterial; antifungal; dental plaque reduction (chewed as gum).',
    UsesMalayalam: 'ദഹനേന്ദ്രിയ ചികിത്സ; ആന്റിബാക്ടീരിയൽ; ആന്റിഫംഗൽ; ദന്ത പ്ലാക്ക് കുറക്കൽ.',
    PageReference: '15v-13, 19v-14, 20v-18',
    SourcePage: 202,
  },
  {
    id: 57,
    category: 'other',
    ArabicName: 'لبن حمارة سودا',
    EnglishName: 'Milk (Yoghurt) of a Black She Donkey',
    MalayalamName: 'കറുത്ത പെൺ കഴുതയുടെ പാൽ',
    ScientificName: '',
    DescriptionEnglish: 'Appears on page 4r-12. Historically used as an antidote to poison.',
    DescriptionMalayalam: 'വിഷഹരണ ഔഷധം ആയി ഉപയോഗിക്കുന്നു.',
    UsesEnglish: 'Antidote to poison.',
    UsesMalayalam: 'വിഷഹരണം.',
    PageReference: '4r-12',
    SourcePage: 202,
  },
  {
    id: 58,
    category: 'other',
    ArabicName: 'مسك',
    EnglishName: 'Musk',
    MalayalamName: 'മൃഗനാഭി',
    ScientificName: 'Moschidae',
    DescriptionEnglish: 'Appears on page 7r, line 15. Fragrant substance from the musk deer gland. Used as a stimulant to the nervous and vascular systems. Possesses narcotic properties. Used to treat hiccoughs, irregular or tremulous pulse, muscle spasms, and insomnia from fatigue. Combined with ammonia, used to stop gangrene.',
    DescriptionMalayalam: 'മൃഗനാഭി മാനിന്റെ ഗ്രന്ഥിയിൽ നിന്ന്. നാഡി, രക്തനാള ഉത്തേജകം. ഓക്കൾ, ക്രമക്കേടുള്ള നാഡി, പേശി ആക്ഷേപം, ക്ഷീണ ഉറക്കക്കുറവ് ചികിത്സ. അമോണിയ ചേർത്ത് ഗ്യാംഗ്രീൻ ചികിത്സ.',
    UsesEnglish: 'Stimulant to nervous and vascular systems; hiccoughs; irregular pulse; muscle spasms; insomnia; (with ammonia) stopping gangrene.',
    UsesMalayalam: 'നാഡി, രക്തനാള ഉത്തേജനം; ഓക്കൾ; ക്രമക്കേടുള്ള നാഡി; പേശി ആക്ഷേപം; ഉറക്കക്കുറവ്; ഗ്യാംഗ്രീൻ.',
    PageReference: '7r',
    SourcePage: 202,
  },
  {
    id: 59,
    category: 'resin',
    ArabicName: 'مر / معرة',
    EnglishName: 'Myrrh',
    MalayalamName: 'മൂർ',
    ScientificName: 'Commiphora myrrha',
    DescriptionEnglish: 'Appears on page 15r-20. Used in medieval medicine for circulatory problems due to tonic and rejuvenating properties. Also used as a disinfectant since ancient times.',
    DescriptionMalayalam: 'രക്ത ചംക്രമണ പ്രശ്നങ്ങൾ, ടോണിക്, ഉജ്ജീവന ഗുണങ്ങൾ. പ്രാചീന കാലം മുതൽ അണുനാശിനി.',
    UsesEnglish: 'Circulatory problems; tonic; rejuvenating; disinfectant.',
    UsesMalayalam: 'രക്ത ചംക്രമണ ചികിത്സ; ടോണിക്; ഉജ്ജീവനം; അണുനാശിനി.',
    PageReference: '15r-20',
    SourcePage: 202,
  },
  {
    id: 60,
    category: 'herb',
    ArabicName: 'مورد',
    EnglishName: 'Myrtle',
    MalayalamName: 'മേർട്ടിൽ',
    ScientificName: 'Myrtus communis',
    DescriptionEnglish: 'Appears on page 27r-14. Astringent, antiseptic and tonic properties of leaves used for wound healing. Taken internally for digestive and urinary system disorders.',
    DescriptionMalayalam: 'ഇലകളുടെ ചൂണൽ, അണുനാശ, ടോണിക് ഗുണങ്ങൾ — മുറിവ് ഭേദം. ദഹന, മൂത്രനാള ക്രമക്കേട് ചികിത്സ.',
    UsesEnglish: 'Wound healing (astringent, antiseptic, tonic); digestive and urinary system disorders.',
    UsesMalayalam: 'മുറിവ് ഭേദം; ദഹന, മൂത്രനാള ചികിത്സ.',
    PageReference: '27r-14',
    SourcePage: 203,
  },
  {
    id: 61,
    category: 'other',
    ArabicName: 'نفط ابيض',
    EnglishName: 'Naphtha (White)',
    MalayalamName: 'വെള്ള നഫ്ത',
    ScientificName: '',
    DescriptionEnglish: 'Found on page 25v-17. Ingested in small doses for suppressing cough, asthma, bladder discomfort and arthritis. Taken internally to relieve belly cramps and aches. Applied topically for skin rashes and infections. Also used in incense preparations.',
    DescriptionMalayalam: 'ചുമ ദമനം, ആസ്ത്മ, മൂത്രാശയ ദൗർ ബല്യം, സന്ധിവാതം. ഉദര ഞരക്കം. ചർമ്മ ചൊറിച്ചിൽ, അണുബാധ. ധൂപ ദ്രവ്യം.',
    UsesEnglish: 'Cough suppressant; asthma; bladder discomfort; arthritis; belly cramps; skin rashes and infections; incense.',
    UsesMalayalam: 'ചുമ; ആസ്ത്മ; മൂത്രാശയ ദൗർബല്യം; സന്ധിവാതം; ഉദര ഞരക്കം; ചർമ്മ അണുബാധ.',
    PageReference: '25v-17',
    SourcePage: 203,
  },
  {
    id: 62,
    category: 'resin',
    ArabicName: 'وشق',
    EnglishName: 'North African Giant Fennel',
    MalayalamName: 'നോർത്ത് ആഫ്രിക്കൻ ഫെന്നൽ',
    ScientificName: 'Ferula tingitana',
    DescriptionEnglish: 'Appears on page 8v-8. Grows in North Africa. Produces ammoniacum (gum ammoniac). Used in fumigation and as a component in recipes for curing eye diseases.',
    DescriptionMalayalam: 'വടക്കേ ആഫ്രിക്കയിൽ വളരുന്നു. അമ്മോണിയം ഗം ഉൽ‌പ്പാദിപ്പിക്കുന്നു. ധൂപ, കണ്ണ് ചികിത്സ ഘടകം.',
    UsesEnglish: 'Fumigation; component in eye disease remedies.',
    UsesMalayalam: 'ധൂപം; കണ്ണ് ചികിത്സ ഘടകം.',
    PageReference: '8v-8',
    SourcePage: 203,
  },
  {
    id: 63,
    category: 'resin',
    ArabicName: 'لبان ذكر',
    EnglishName: 'Olibanum (Male Frankincense)',
    MalayalamName: 'പുരുഷ കുന്തിരിക്കം',
    ScientificName: 'Boswellia spp.',
    DescriptionEnglish: 'Appears on pages 4r, 7r, and 7 lines 14-15. Called Male Frankincense, often synonymous with incense. Resin extracted from Boswellia trees in Arabia and Somalia. Traditionally used to heal abrasions and cuts, bronchitis, and gingivitis. Avicenna recommended it for tumors, ulcers, vomiting, dysentery and fevers. Modern science found it increases white blood cell count.',
    DescriptionMalayalam: 'അറേബ്യ, സൊമാലിയ ബൊസ്‌വെലിയ വൃക്ഷത്തിൽ നിന്ന്. മുറിവ്, ബ്രോങ്കൈറ്റിസ്, ദന്ത ജ്വലനം ഭേദം. ഇബ്ൻ സീന: കഴലകൾ, വ്രണം, ഛർദ്ദി, ഒഴിച്ചിൽ, ജ്വരം. ശ്വേതരക്താണു വർദ്ധന.',
    UsesEnglish: 'Abrasions and cuts; bronchitis; gingivitis; tumors; ulcers; vomiting; dysentery; fevers; increases white blood cell count.',
    UsesMalayalam: 'മുറിവ്; ബ്രോങ്കൈറ്റിസ്; ദന്ത ജ്വലനം; കഴലകൾ; ഛർദ്ദി; ഒഴിച്ചിൽ; ജ്വരം.',
    PageReference: '4r, 7r',
    SourcePage: 203,
  },
  {
    id: 64,
    category: 'other',
    ArabicName: 'أفيون',
    EnglishName: 'Opium',
    MalayalamName: 'കറുക്ക (അഫ്യൂൺ)',
    ScientificName: 'Papaver somniferum',
    DescriptionEnglish: 'Appears on pages 3v-16, 4r-16, 8r-6, 8v-8, 29r-21, 20v-3, and 23r-19. The earliest written reference is from 4000 BC. By the 8th century AD its use had spread to Arabia, India and China. Commonly used to treat severe diarrhea and as an effective painkiller. Considered the first authentic anti-depressant.',
    DescriptionMalayalam: '4000 ബി.സി. ആദ്യ പരാമർശം. ക്രി.ശ. 8-ആം നൂറ്റാണ്ട് അറേബ്യ, ഇന്ത്യ, ചൈന ഉപയോഗം. കടുത്ത വയറിളക്കം, വേദനനിവാരണം, ആദ്യ ആന്റി ഡിപ്രസ്സന്റ്.',
    UsesEnglish: 'Severe diarrhea; painkiller; first anti-depressant.',
    UsesMalayalam: 'കടുത്ത വയറിളക്കം; വേദനനിവാരണം; ആന്റി ഡിപ്രസ്സന്റ്.',
    PageReference: '3v-16, 4r-16, 8r-6, 8v-8, 29r-21, 20v-3, 23r-19',
    SourcePage: 204,
  },
  {
    id: 65,
    category: 'resin',
    ArabicName: 'ببنق / جوشير',
    EnglishName: 'Opopanax',
    MalayalamName: 'ഓപ്പോപ്പനാക്സ്',
    ScientificName: 'Opopanax chironium',
    DescriptionEnglish: 'Appears on pages 5v, 6v, 21r, and 9v. A species of parsnip also known as sweet myrrh. Tea from roots used for women\'s complaints. Poultice of roots for inflammations and sores. Insect spray made from leaves and roots.',
    DescriptionMalayalam: 'മധുര മൂർ (sweet myrrh) എന്നും അറിയപ്പെടുന്ന പർസ്‌നിപ്. വേര് കഷായം: സ്ത്രീ ശാരീരിക ആവലാതി. വേര് ലേഹ്യം: ജ്വലനം, ചൊറി. ഇല-വേര് കീടനാശിനി.',
    UsesEnglish: 'Women\'s complaints (root tea); inflammations and sores (root poultice); insect repellent (leaves and roots).',
    UsesMalayalam: 'സ്ത്രീ ആരോഗ്യ ചികിത്സ; ജ്വലനം, ചൊറി; കീടനാശിനി.',
    PageReference: '5v, 6v, 21r, 9v',
    SourcePage: 204,
  },
  {
    id: 66,
    category: 'herb',
    ArabicName: 'زبيب الجبل',
    EnglishName: 'Palmated Larkspur (Stavesacre)',
    MalayalamName: 'സ്റ്റേവ്‌സേക്കർ',
    ScientificName: 'Delphinium staphysagria',
    DescriptionEnglish: 'Appears on page 10v-2. Taken internally to cause vomiting and purge the bowels. Applied externally as an ointment as antidote to stings and bites. Seeds kill head lice.',
    DescriptionMalayalam: 'ആന്തരിക: ഛർദ്ദി, കുടൽ ശുദ്ധി. ബാഹ്യ ലേഹ്യം: കടി, കുത്ത് നിർവ്വിഷം. വിത്ത്: കേശ ഊകൻ (lice) നാശം.',
    UsesEnglish: 'Emetic; purge bowels; antidote for stings and bites; kills head lice.',
    UsesMalayalam: 'ഛർദ്ദി; കുടൽ ശുദ്ധി; കടി, കുത്ത് നിർവ്വിഷം; കേശ ഊകൻ നാശം.',
    PageReference: '10v-2',
    SourcePage: 205,
  },
  {
    id: 67,
    category: 'root',
    ArabicName: 'عاقر قرحا',
    EnglishName: 'Pellitory',
    MalayalamName: 'അക്കർകര',
    ScientificName: 'Anacyclus pyrethrum / Pyrethrum radix',
    DescriptionEnglish: 'Appears on pages 3r, 8v-4, and 19r-3. An aphrodisiac, tonic for the nervous system, remedy against inflammations of the gums and toothaches, rheumatic conditions, and to aid digestion. Used in treatments of sore throat, paralysis, and epilepsy. Originated from Morocco and Syria; found across North Africa, North India, Mediterranean and Arabia.',
    DescriptionMalayalam: 'ലൈംഗിക ഉത്തേജകം, നാഡി ടോണിക്, ദന്ത ജ്വലനം, പല്ലുവേദന, സന്ധിവാതം, ദഹന സഹായം. ഗളഭ്രംശം, തളർവാതം, അപസ്മാരം ചികിത്സ.',
    UsesEnglish: 'Aphrodisiac; nerve tonic; gum inflammation; toothache; rheumatism; digestion; sore throat; paralysis; epilepsy.',
    UsesMalayalam: 'ലൈംഗിക ഉത്തേജകം; നാഡി ടോണിക്; ദന്ത ജ്വലനം; സന്ധിവാതം; ഗളഭ്രംശം; അപസ്മാരം.',
    PageReference: '3r, 8v-4, 19r-3',
    SourcePage: 205,
  },
  {
    id: 68,
    category: 'spice',
    ArabicName: 'فلفل اسود',
    EnglishName: 'Pepper',
    MalayalamName: 'കുരുമുളക്',
    ScientificName: 'Piper nigrum',
    DescriptionEnglish: 'Appears on page 23v-11. Used historically in wine mixtures as medication for stomach pain and diseases involving excessive cold humors such as overproduction of phlegm in respiratory illness. Beverages with pepper used as aphrodisiacs, digestives, cold prevention and bronchitis therapy.',
    DescriptionMalayalam: 'ഉദര വേദന, ശ്ലേഷ്മ ശ്വസന രോഗ ചികിത്സ. ലൈംഗിക ഉത്തേജകം, ദഹന, ജലദോഷ, ബ്രോങ്കൈറ്റിസ് ചികിത്സ.',
    UsesEnglish: 'Stomach pain; phlegm/respiratory illness; aphrodisiac; digestive; cold prevention; bronchitis.',
    UsesMalayalam: 'ഉദര വേദന; ശ്ലേഷ്മ ശ്വസനം; ലൈംഗിക ഉത്തേജകം; ദഹനം; ജലദോഷം; ബ്രോങ്കൈറ്റിസ്.',
    PageReference: '23v-11',
    SourcePage: 205,
  },
  {
    id: 69,
    category: 'other',
    ArabicName: 'عطر',
    EnglishName: 'Perfume',
    MalayalamName: 'സുഗന്ധം',
    ScientificName: '',
    DescriptionEnglish: 'Appears on page 9r-6. Part of the "kingly compounds." Used for aromatherapy, strengthening body\'s vitality, overcoming migraines and headaches, as an aphrodisiac, and for back pain and women\'s disorders.',
    DescriptionMalayalam: '"രാജ സംയോഗ" ഭാഗം. ആരോമ തെറാപ്പി, ശരീര ഊർജ്ജ വർദ്ധന, മൈഗ്രൈൻ, തലവേദന, ലൈംഗിക ഉത്തേജകം, നടുവേദന, സ്ത്രീ ശാരീരിക ആവലാതി.',
    UsesEnglish: 'Aromatherapy; body vitality; migraines; headaches; aphrodisiac; back pain; women\'s disorders.',
    UsesMalayalam: 'ആരോമ തെറാപ്പി; ഊർജ്ജ വർദ്ധന; മൈഗ്രൈൻ; ലൈംഗിക ഉത്തേജകം; നടുവേദന; സ്ത്രീ ആരോഗ്യം.',
    PageReference: '9r-6',
    SourcePage: 205,
  },
  {
    id: 70,
    category: 'herb',
    ArabicName: 'الما ميران',
    EnglishName: 'Pilewort (Greater Celandine)',
    MalayalamName: 'പൈൽവർട്ട്',
    ScientificName: 'Chelidonium majus',
    DescriptionEnglish: 'Appears on page 14v-19. Called pilewort for its cure of hemorrhoids and scurvywort for treating scurvy. Leaves are very high in Vitamin C.',
    DescriptionMalayalam: 'മൂലരോഗ ചികിത്സ (pilewort). സ്കർവി ചികിത്സ (scurvywort). ഇലകളിൽ വളരെ കൂടുതൽ വിറ്റാമിൻ C.',
    UsesEnglish: 'Hemorrhoids; scurvy.',
    UsesMalayalam: 'മൂലരോഗ ചികിത്സ; സ്കർവി ചികിത്സ.',
    PageReference: '14v-19',
    SourcePage: 205,
  },
  {
    id: 71,
    category: 'flower',
    ArabicName: 'طلع النخل',
    EnglishName: 'Pollen of the Male Palm Tree',
    MalayalamName: 'പനം പൂമ്പൊടി',
    ScientificName: 'Arecaceae phoenix',
    DescriptionEnglish: 'Found on pages 25r-9 and 6v-18. Pollen mixed with water used as a charm against childlessness. Modern science has discovered it contains the estrogenic hormone estrone and exhibits gonadotrophic activity.',
    DescriptionMalayalam: 'പൂമ്പൊടി വെള്ളത്തിൽ കലർത്തി നിർഭാഗ്യ ചികിത്സ. ആധുനിക ശാസ്ത്രം: ഈസ്ട്രോൺ ഹോർമോൺ, ഗോണഡോട്രോഫിക് ഗുണം.',
    UsesEnglish: 'Charm against childlessness; contains estrone (estrogenic hormone); gonadotrophic activity.',
    UsesMalayalam: 'നിർഭാഗ്യ ചികിത്സ; ഈസ്ട്രോൺ ഹോർമോൺ; ഗോണഡോട്രോഫിക് ഗുണം.',
    PageReference: '25r-9, 6v-18',
    SourcePage: 205,
  },
  {
    id: 72,
    category: 'flower',
    ArabicName: 'ماء الورد',
    EnglishName: 'Rosewater',
    MalayalamName: 'റോസ് ജലം',
    ScientificName: '',
    DescriptionEnglish: 'Appears on pages 8v-6 and 9r-6. Ibn Sina recommended bathing in herbal mixture including rosewater for removal of urinary tract stones. Mildly astringent; valuable lotion for inflamed and sore eyes.',
    DescriptionMalayalam: 'ഇബ്ൻ സീന: മൂത്രനാൾ കല്ല് നീക്കാൻ ഔഷധ കുളി. ചൂലൽ ഗുണം; ചുകന്ന, വേദനിക്കുന്ന കണ്ണ് ലോഷൻ.',
    UsesEnglish: 'Urinary tract stones (herbal bath); lotion for inflamed and sore eyes.',
    UsesMalayalam: 'മൂത്രനാൾ കല്ല്; ചുകന്ന കണ്ണ് ലോഷൻ.',
    PageReference: '8v-6, 9r-6',
    SourcePage: 206,
  },
  {
    id: 73,
    category: 'herb',
    ArabicName: 'ماء السداب',
    EnglishName: 'Rue Liquid Extract',
    MalayalamName: 'റൂ ദ്രാവക സത്ത്',
    ScientificName: 'Ruta graveolens',
    DescriptionEnglish: 'Appears on pages 6v-23, 23v-12, 26r-20, and 26v-1. Used to prepare eyewashes and stomach tonics. Also used as a defense against the evil eye.',
    DescriptionMalayalam: 'കണ്ണ് കഴുകൽ, ഉദര ടോണിക്. ദൃഷ്ടിദോഷ നിവാരണം.',
    UsesEnglish: 'Eyewashes; stomach tonics; defense against evil eye.',
    UsesMalayalam: 'കണ്ണ് കഴുകൽ; ഉദര ടോണിക്; ദൃഷ്ടിദോഷ നിവാരണം.',
    PageReference: '6v-23, 23v-12, 26r-20, 26v-1',
    SourcePage: 206,
  },
  {
    id: 74,
    category: 'flower',
    ArabicName: 'عروق القرطم / عصفور',
    EnglishName: 'Safflower',
    MalayalamName: 'കുസുമ്പ',
    ScientificName: 'Carthamus tinctorius',
    DescriptionEnglish: 'Appears on page 16v-20. Cultivated in Egypt and South Asia for food and medicine. Produces yellow dye. Used in traditional medicine as a laxative, sedative, and diaphoretic. Seeds treat inflammatory tumors of the liver and rheumatism and sores.',
    DescriptionMalayalam: 'ഈജിപ്ത്, ദക്ഷിണ ഏഷ്യ. മഞ്ഞ ചായം. വിരേചകം, ഉറക്ക ഔഷധം, വിയർ ഉത്തേജകം. വിത്ത്: കരൾ കഴല, സന്ധിവാതം, ചൊറി ചികിത്സ.',
    UsesEnglish: 'Laxative; sedative; diaphoretic; liver inflammatory tumors; rheumatism; sores.',
    UsesMalayalam: 'വിരേചകം; ഉറക്ക ഔഷധം; വിയർ ഉത്തേജകം; കരൾ കഴല; സന്ധിവാതം.',
    PageReference: '16v-20',
    SourcePage: 206,
  },
  {
    id: 75,
    category: 'spice',
    ArabicName: 'زعفران',
    EnglishName: 'Saffron',
    MalayalamName: 'കുങ്കുമം',
    ScientificName: 'Crocus sativus',
    DescriptionEnglish: 'Appears throughout the manuscript on pages 5v, 8v, 9r, 14v, 20v, and 29v. Long used as drug and condiment. Originally called Kurkum in Hebrew and Aramaic. Used to treat arthritis, asthma, reduce fever and heal the liver. Still highly valued in Unani and Ayurvedic medicine.',
    DescriptionMalayalam: 'ഹീബ്രു, അരമായ: കുർകും. സന്ധിവാതം, ആസ്ത്മ, ജ്വര ശമനം, കരൾ ഭേദം. ഉനാനി, ആയുർവേദ ചികിത്സ.',
    UsesEnglish: 'Arthritis; asthma; fever reduction; liver healing.',
    UsesMalayalam: 'സന്ധിവാതം; ആസ്ത്മ; ജ്വര ശമനം; കരൾ ഭേദം.',
    PageReference: '5v, 8v, 9r, 14v, 20v, 29v',
    SourcePage: 206,
  },
  {
    id: 76,
    category: 'resin',
    ArabicName: 'سكبينج',
    EnglishName: 'Sagapenum',
    MalayalamName: 'സഗപീനം',
    ScientificName: 'Ferula Persica',
    DescriptionEnglish: 'Appears on pages 8r-7 and 20v-18. A gum-resin with a garlicky smell. Less pungent than asafetida but more powerful than olibanum. Used in treatment of amenorrhea and hysteria.',
    DescriptionMalayalam: 'വെളുത്തുള്ളി ഗന്ധം ഉള്ള ഗം-റെസിൻ. കായത്തേക്കാൾ കുറഞ്ഞ, കുന്തിരിക്കത്തേക്കാൾ ശക്തം. ആർത്തവ, ഹിസ്റ്റീരിയ ചികിത്സ.',
    UsesEnglish: 'Amenorrhea; hysteria.',
    UsesMalayalam: 'ആർത്തവ ക്രമക്കേട്; ഹിസ്റ്റീരിയ.',
    PageReference: '8r-7, 20v-18',
    SourcePage: 207,
  },
  {
    id: 77,
    category: 'other',
    ArabicName: 'زبد البحر',
    EnglishName: 'Sea Sponge',
    MalayalamName: 'സമുദ്ര സ്‌പോഞ്ച്',
    ScientificName: '',
    DescriptionEnglish: 'Appears on pages 8v-4 and 17v-8. In medieval times thought to be sea foam or pumice (magnesium silicate). Used for hair removal and in ointments with beeswax for treatment of scabies and other skin problems such as ringworm.',
    DescriptionMalayalam: 'മദ്ധ്യകാലം: കടൽ നുര / പ്യൂമിസ്. രോമ നീക്കം, തേൻ മൈക്ക് ചേർന്ന ലേഹ്യം: ചൊറി, ചൊറിക്കുത്ത് ചികിത്സ.',
    UsesEnglish: 'Hair removal; ointment (with beeswax) for scabies and ringworm.',
    UsesMalayalam: 'രോമ നീക്കം; ചൊറി, ചൊറിക്കുത്ത് ചികിത്സ.',
    PageReference: '8v-4, 17v-8',
    SourcePage: 207,
  },
  {
    id: 78,
    category: 'seed',
    ArabicName: 'سمسم / جلجلان',
    EnglishName: 'Sesame',
    MalayalamName: 'എള്ള്',
    ScientificName: 'Sesamum orientale',
    DescriptionEnglish: 'Appears on page 24r-4. Native to India. Used to treat cholera, constipation, cough, scalds, ulcers, burns, and amenorrhea. Mixed with almond, honey and sugar, recommended as part of a nutritional regimen.',
    DescriptionMalayalam: 'ഇന്ത്യ സ്വദേശി. കോളറ, മലബന്ധം, ചുമ, തൊലിപ്പൊള്ളൽ, വ്രണം, പൊള്ളൽ, ആർത്തവ ക്രമക്കേട് ചികിത്സ. ബദാം, തേൻ, പഞ്ചസാര ചേർത്ത് പോഷക ഭക്ഷണ ക്രമം.',
    UsesEnglish: 'Cholera; constipation; cough; scalds; ulcers; burns; amenorrhea; nutritional regimen (with almond, honey, sugar).',
    UsesMalayalam: 'കോളറ; മലബന്ധം; ചുമ; പൊള്ളൽ; വ്രണം; ആർത്തവ ക്രമക്കേട്.',
    PageReference: '24r-4',
    SourcePage: 207,
  },
  {
    id: 79,
    category: 'resin',
    ArabicName: 'سقمونيا',
    EnglishName: 'Scammony',
    MalayalamName: 'സ്കാമോണി',
    ScientificName: 'Convolvulus Scammonia',
    DescriptionEnglish: 'Appears on page 5v, line 16. Arabic name translates as "the praised one." Juices made into a resin used as a drastic cathartic and hydragogue causing abundant watery discharge. Must be used with extreme caution.',
    DescriptionMalayalam: 'അറബിക്: "പ്രശംസിക്കപ്പെട്ടവൻ". ശക്തമായ ജലോദര-ശുദ്ധീകരണ ഔഷധം. ജാഗ്രതയോടെ ഉപയോഗിക്കണം.',
    UsesEnglish: 'Drastic cathartic; hydragogue (causes watery discharge). Use with extreme caution.',
    UsesMalayalam: 'ശക്തമായ ശുദ്ധീകരണ ഔഷധം; ജലോദര. ജാഗ്രതയോടെ ഉപയോഗിക്കണം.',
    PageReference: '5v',
    SourcePage: 207,
  },
  {
    id: 80,
    category: 'herb',
    ArabicName: 'الزروند الطويل',
    EnglishName: 'Smearwort',
    MalayalamName: 'അരിസ്റ്റോലോക്കിയ',
    ScientificName: 'Aristolochia rotunda',
    DescriptionEnglish: 'Appears on pages 8r-7 and 19v-13. Considered toxic; its active ingredient aristolochic acid has shown mixed research results — potentially carcinogenic but also anticancerous. Can increase cellular immunity but is damaging to kidneys in large doses. Has been used to suppress menstrual flow.',
    DescriptionMalayalam: 'വിഷകരം കണക്കാക്കുന്നു. അരിസ്റ്റോലോക്കിക് ആസിഡ് — കാൻസർ കാരണ / നാശക ഗുണം ഒരേ സമയം. ദീർഘ ഉപയോഗം വൃക്ക ദോഷം. ആർത്തവ ഒഴുക്ക് ദമനം.',
    UsesEnglish: 'Suppress menstrual flow. CAUTION: Toxic; potentially carcinogenic; damaging to kidneys in large doses.',
    UsesMalayalam: 'ആർത്തവ ദമനം. ജാഗ്രത: വിഷകരം; വൃക്ക ദോഷകരം.',
    PageReference: '8r-7, 19v-13',
    SourcePage: 208,
  },
  {
    id: 81,
    category: 'root',
    ArabicName: 'جنتيانا',
    EnglishName: 'Soapwort Gentian',
    MalayalamName: 'ജെന്റ്ഷ്യൻ',
    ScientificName: 'Saponaria officinalis',
    DescriptionEnglish: 'Appears on pages 6r, 15r, 21v, and 23r. Root is yellow inside and black outside. Used as an emetic and in purging medicine. Also as treatment for ringworm. Sniffed as powder to strengthen tired eyes and stop blindness.',
    DescriptionMalayalam: 'വേര് ഉള്ളിൽ മഞ്ഞ, പുറത്ത് കറുത്ത. ഛർദ്ദിക്കുന്ന ഔഷധം, ശുദ്ധീകരണ ഔഷധം. ചൊറിക്കുത്ത് ചികിത്സ. പൊടി: ക്ഷീണ കണ്ണ്, അന്ധത ചികിത്സ.',
    UsesEnglish: 'Emetic; purging; ringworm; strengthen tired eyes; stop blindness (sniffed as powder).',
    UsesMalayalam: 'ഛർദ്ദി ഔഷധം; ശുദ്ധീകരണം; ചൊറിക്കുത്ത്; ക്ഷീണ കണ്ണ്; അന്ധത.',
    PageReference: '6r, 15r, 21v, 23r',
    SourcePage: 208,
  },
  {
    id: 82,
    category: 'other',
    ArabicName: 'خل',
    EnglishName: 'Sour Wine (Vinegar)',
    MalayalamName: 'അമ്ലം (വിനിഗർ)',
    ScientificName: '',
    DescriptionEnglish: 'Appears on page 27v-14. Used as antimicrobial for thousands of years. Kills most bacteria on contact. Recommended as rinse for mouth ulcers and gargle for sore throats. Internally in moderation for remedying melancholy and mood disorders.',
    DescriptionMalayalam: 'ആയിരക്കണക്കിന് വർഷം ആന്റിമൈക്രോബിയൽ. വായ്‌പ്പുണ്ണ് കഴുകൽ, ഗള വേദന ഗ്ലർഗ്ഗൾ. അളവ് അനുസരിച്ച് ഉദ്വേഗം, മൂഡ് ക്രമക്കേട് ചികിത്സ.',
    UsesEnglish: 'Antimicrobial; mouth ulcer rinse; sore throat gargle; melancholy and mood disorders (internal, moderate).',
    UsesMalayalam: 'ആന്റിമൈക്രോബിയൽ; വായ്‌പ്പുണ്ണ്; ഗളവേദന; ഉദ്വേഗ, മൂഡ് ക്രമക്കേട്.',
    PageReference: '27v-14',
    SourcePage: 208,
  },
  {
    id: 83,
    category: 'resin',
    ArabicName: 'استوراكس',
    EnglishName: 'Storax',
    MalayalamName: 'സ്റ്റോറാക്‌സ്',
    ScientificName: 'Styrax officinale / Liquidambar',
    DescriptionEnglish: 'Appears on page 24r-13. Also known as benzoin. Burned as incense to cleanse the surrounding area.',
    DescriptionMalayalam: 'ബെൻസോയിൻ എന്നും അറിയപ്പെടുന്നു. ചുറ്റുപാട് ശുദ്ധിക്ക് ധൂപ ദ്രവ്യം.',
    UsesEnglish: 'Incense for cleansing.',
    UsesMalayalam: 'ശുദ്ധി ധൂപം.',
    PageReference: '24r-13',
    SourcePage: 208,
  },
  {
    id: 84,
    category: 'herb',
    ArabicName: 'ماء السلق',
    EnglishName: 'Swiss Chard Juice',
    MalayalamName: 'ചീര നീര്',
    ScientificName: 'Beta vulgaris',
    DescriptionEnglish: 'Appears on pages 6r, line 11 and 21v, line 13. Juice of Swiss chard or spinach beets. Used as a remedy for anemia and yellow fever.',
    DescriptionMalayalam: 'ചീര നീര്. വിളർച്ച, മഞ്ഞ ജ്വര ചികിത്സ.',
    UsesEnglish: 'Anemia; yellow fever.',
    UsesMalayalam: 'വിളർച്ച; മഞ്ഞ ജ്വരം.',
    PageReference: '6r, 21v',
    SourcePage: 208,
  },
  {
    id: 85,
    category: 'other',
    ArabicName: 'قطران شامى',
    EnglishName: 'Syrian Tar',
    MalayalamName: 'സിറിയൻ ടാർ',
    ScientificName: '',
    DescriptionEnglish: 'Appears on page 29r-15. A preparation of vegetable tar from the borders of the Red Sea, obtained from branches of a small shrub in Syria. One of the earliest known antiseptics, used in ancient Egyptian mummification.',
    DescriptionMalayalam: 'ചെങ്കടൽ തീരം, സിറിയൻ കുറ്റിക്കാട്ടിൽ നിന്നുള്ള സസ്യ ടാർ. ഏറ്റവും പഴക്കം ചെന്ന അണുനാശിനി — ഈജിപ്ത് মমीfication.',
    UsesEnglish: 'Antiseptic.',
    UsesMalayalam: 'അണുനാശിനി.',
    PageReference: '29r-15',
    SourcePage: 208,
  },
  {
    id: 86,
    category: 'resin',
    ArabicName: 'غم غرند',
    EnglishName: 'Syrian Tragacanth',
    MalayalamName: 'ട്രഗകാൻഥ്',
    ScientificName: 'Astragalus gummifer',
    DescriptionEnglish: 'Appears on page 10v-18. Its gummy exudate was used for giving consistency to lozenges and in the making of emulsions.',
    DescriptionMalayalam: 'ഗം സ്രാവം: ലോസഞ്ചർ ഉറപ്പ്, ഇമൽഷൻ നിർമ്മാണം.',
    UsesEnglish: 'Consistency in lozenges; making emulsions.',
    UsesMalayalam: 'ലോസഞ്ചർ ഉറപ്പ്; ഇമൽഷൻ നിർമ്മാണം.',
    PageReference: '10v-18',
    SourcePage: 208,
  },
  {
    id: 87,
    category: 'wood',
    ArabicName: 'الطرفا',
    EnglishName: 'Tamarisk',
    MalayalamName: 'ഉപ്പൻ മരം',
    ScientificName: 'Tamarix aphylla',
    DescriptionEnglish: 'Root appears on page 19v-14; wood on page 23v-14. Decoction of leaves used to treat eye inflammation and fevers. Roots and bark used to repel insects, preventing diseases carried by them such as black fever (carried by sand fleas).',
    DescriptionMalayalam: 'ഇല കഷായം: കണ്ണ് ജ്വലനം, ജ്വരം. വേര്, പുറന്തൊലി: കീടനിവാരണം (ഉണക്ക ഈച്ച — കറുത്ത ജ്വരം) .',
    UsesEnglish: 'Eye inflammation; fevers; insect repellent (prevent black fever from sand fleas).',
    UsesMalayalam: 'കണ്ണ് ജ്വലനം; ജ്വരം; കീടനിവാരണം; കറുത്ത ജ്വർ നിവാരണം.',
    PageReference: '19v-14, 23v-14',
    SourcePage: 209,
  },
  {
    id: 88,
    category: 'other',
    ArabicName: 'عصير العنب غير المخمر',
    EnglishName: 'Unfermented Grape Juice (Must)',
    MalayalamName: 'പുളിക്കാത്ത മുന്തിരി നീര്',
    ScientificName: '',
    DescriptionEnglish: 'Appears on page 24r-4. Unfermented grape juice (mosto / must). The manuscript admonishes abstinence from it as part of the recommended nutritional treatment.',
    DescriptionMalayalam: 'പുളിക്കാത്ത മുന്തിരി നീര്. ഗ്രന്ഥം പോഷകചികിത്സ ഭാഗമായി ഒഴിവാക്കാൻ ഉദ്ബോധിപ്പിക്കുന്നു.',
    UsesEnglish: 'Referenced in nutritional context; manuscript advises abstinence.',
    UsesMalayalam: 'പോഷകചികിത്സ; ഗ്രന്ഥം ഒഴിവാക്കാൻ ഉദ്ബോധിപ്പിക്കുന്നു.',
    PageReference: '24r-4',
    SourcePage: 209,
  },
  {
    id: 89,
    category: 'other',
    ArabicName: 'بول',
    EnglishName: 'Urine (Various Animals)',
    MalayalamName: 'മൂത്രം (വിവിധ ജന്തുക്കൾ)',
    ScientificName: '',
    DescriptionEnglish: 'Boy urine (pages 3r-20, 3v-2); Black bull urine (3v-2); Generic bull urine (4v-11, 13r-1, 23r-19); Siring bull urine (16v-6, 16-7); Male goat urine (11r-5). Listed as ingredients in healing mixtures, generally sniffed, with a salutary effect on those possessed by malefic entities.',
    DescriptionMalayalam: 'ബാലൻ, കറുത്ത കാള, ആൺ ആട് മൂത്രം ഉൾക്കൊള്ളുന്ന ഔഷധ മിശ്രിതങ്ങൾ — ഭൂതബാധ, ദൈവ ശക്തി ചികിത്സ.',
    UsesEnglish: 'Ingredient in healing mixtures (generally sniffed); treatment of possession by malefic entities.',
    UsesMalayalam: 'ഭൂതബാധ ചികിത്സ; ഔഷധ മിശ്രിതം (ആഘ്രാണം).',
    PageReference: '3r-20, 3v-2, 4v-11, 11r-5, 13r-1, 16v-6',
    SourcePage: 209,
  },
  {
    id: 90,
    category: 'herb',
    ArabicName: 'ورق الجوز',
    EnglishName: 'Walnut Leaf',
    MalayalamName: 'വാൾനട്ട് ഇല',
    ScientificName: 'Juglandaceae',
    DescriptionEnglish: 'Appears on page 27r-13. Used as an antiseptic and as an infusion to treat toxic blood conditions.',
    DescriptionMalayalam: 'അണുനാശിനി. കഷായം: വിഷ രക്ത ദോഷ ചികിത്സ.',
    UsesEnglish: 'Antiseptic; infusion to treat toxic blood conditions.',
    UsesMalayalam: 'അണുനാശിനി; വിഷ രക്ത ദോഷ ചികിത്സ.',
    PageReference: '27r-13',
    SourcePage: 209,
  },
  {
    id: 91,
    category: 'herb',
    ArabicName: 'ورس',
    EnglishName: 'Warrus',
    MalayalamName: 'വർഷ്',
    ScientificName: 'Flemingia rhodocarpa Baker',
    DescriptionEnglish: 'Appears on page 5v, line 16. Common in Morocco. A red coloring substance used in dyes. Made into a decoction for bathing sores and swellings, and as antipyretic for postpartum fever and paralysis and pain in the joints. Grows in India, South Arabia, and Abyssinia.',
    DescriptionMalayalam: 'ചുകന്ന ചായ ദ്രവ്യം. ചൊറി, നീർക്കെട്ട് കഷായം. പ്രസവ ജ്വരം, തളർവാതം, സന്ധി വേദന ചികിത്സ.',
    UsesEnglish: 'Red dye; decoction for sores and swellings; antipyretic for postpartum fever; paralysis and joint pain.',
    UsesMalayalam: 'ചുകന്ന ചായ; ചൊറി, നീർക്കെട്ട്; പ്രസവ ജ്വരം; തളർവാതം; സന്ധി വേദന.',
    PageReference: '5v',
    SourcePage: 209,
  },
  {
    id: 92,
    category: 'other',
    ArabicName: 'جوار خالص',
    EnglishName: 'Water — Abundant Spring Water',
    MalayalamName: 'ധാരാളം ഉറവ് ജലം',
    ScientificName: '',
    DescriptionEnglish: 'Found on page 25v-17. Used for protection. One of the Rivers of Paradise is called "Tasnim," spring of abundant water.',
    DescriptionMalayalam: 'സംരക്ഷണ ആവശ്യങ്ങൾക്ക് ഉപയോഗിക്കുന്നു. സ്വർഗ്ഗ നദി "തസ്നീം".',
    UsesEnglish: 'Protection.',
    UsesMalayalam: 'സംരക്ഷണം.',
    PageReference: '25v-17',
    SourcePage: 209,
  },
  {
    id: 93,
    category: 'other',
    ArabicName: 'ماء الصافى',
    EnglishName: 'Water — Distilled',
    MalayalamName: 'ആസവ ജലം',
    ScientificName: '',
    DescriptionEnglish: 'Appears on page 16r-7. Used to wash Quranic verses and names of power from vellum or parchment, and given to the sick person to drink.',
    DescriptionMalayalam: 'ചർമ്മ ലിഖിത ഖുർആൻ ആയതുകൾ, ശക്തി നാമങ്ങൾ കഴുകി രോഗിക്ക് കുടിക്കാൻ നൽകുന്നു.',
    UsesEnglish: 'Wash Quranic verses from parchment for sick person to drink.',
    UsesMalayalam: 'ഖുർആൻ ആയത് കഴുകൽ; രോഗി പ്രയോഗം.',
    PageReference: '16r-7',
    SourcePage: 209,
  },
  {
    id: 94,
    category: 'other',
    ArabicName: 'ماء الزمزم',
    EnglishName: 'Zamzam Water',
    MalayalamName: 'സംസം ജലം',
    ScientificName: '',
    DescriptionEnglish: 'Appears on page 15v-14. Water from the holy well in Mecca, believed to have miraculous healing powers in Islamic tradition. Modern Zamzam water used to clean the Kaaba has rosewater added to it.',
    DescriptionMalayalam: 'മക്കയിലെ പരിശുദ്ധ കിണർ. ഇസ്ലാമിക പാരമ്പര്യത്തിൽ അദ്ഭുത സൗഖ്യ ഗുണം.',
    UsesEnglish: 'Miraculous healing (Islamic tradition).',
    UsesMalayalam: 'അദ്ഭുത സൗഖ്യം (ഇസ്ലാമിക പാരമ്പര്യം).',
    PageReference: '15v-14',
    SourcePage: 209,
  },
  {
    id: 95,
    category: 'seed',
    ArabicName: 'حرمل',
    EnglishName: 'Wild Rue / Mountain Rue',
    MalayalamName: 'ഹർമൽ',
    ScientificName: 'Peganum harmala / Ruta montana',
    DescriptionEnglish: 'Appears on pages 3v-16, 7r-14, 7r-15, 10r-7, and 13r-1. Mountain Rue on pages 7r-14 and 21v-13. Popular in North Africa for medicinal and magical applications. Seeds used by al-Batriq to remove moisture and heat from ill body. Treats insanity, epilepsy, hemorrhoids and baldness. Used to preserve sight. Relieves headaches and hysterical spasms. Treats chronic bronchitis. Seeds used for purification and as aphrodisiac. Has psychedelic properties. Mountain rue used for perfumery and food flavoring.',
    DescriptionMalayalam: 'വടക്കേ ആഫ്രിക്ക ഔഷധ, ആദ്ധ്യാത്മിക ഉപയോഗം. ഭ്രാന്ത്, അപസ്മാരം, മൂലം, കഷണ്ടി. കാഴ്ച സംരക്ഷണം, തലവേദന, ഹിസ്റ്റീരിയ, ദീർഘ ബ്രോങ്കൈറ്റിസ്. വിത്ത്: ശുദ്ധി, ലൈംഗിക ഉത്തേജകം. ഭ്രമ ഗുണം.',
    UsesEnglish: 'Insanity; epilepsy; hemorrhoids; baldness; preserve sight; headaches; hysterical spasms; chronic bronchitis; purification; aphrodisiac.',
    UsesMalayalam: 'ഭ്രാന്ത്; അപസ്മാരം; മൂലം; കഷണ്ടി; കാഴ്ച; തലവേദന; ബ്രോങ്കൈറ്റിസ്; ലൈംഗിക ഉത്തേജകം.',
    PageReference: '3v-16, 7r-14, 7r-15, 10r-7, 13r-1, 21v-13',
    SourcePage: 210,
  },
  {
    id: 96,
    category: 'herb',
    ArabicName: 'حزبق ابيض',
    EnglishName: 'White Hellebore',
    MalayalamName: 'വെള്ള ഹെല്ലിബോർ',
    ScientificName: 'Veratrum album',
    DescriptionEnglish: 'Appears on page 23v-11. A violent, irritant poison. Formerly used in cerebral affections such as mania and epilepsy, and externally against scabies and mange.',
    DescriptionMalayalam: 'അതിശക്തമായ ചൊറിയ്ക്കുന്ന വിഷം. ഭ്രാന്ത്, അപസ്മാരം ചികിത്സ. ബാഹ്യ: ചൊറി, ചേർ ചികിത്സ.',
    UsesEnglish: 'Mania; epilepsy; scabies; mange (external). CAUTION: violent poison.',
    UsesMalayalam: 'ഭ്രാന്ത്; അപസ്മാരം; ചൊറി; ചേർ. ജാഗ്രത: വിഷകരം.',
    PageReference: '23v-11',
    SourcePage: 210,
  },
  {
    id: 97,
    category: 'other',
    ArabicName: 'بهم ابيض',
    EnglishName: 'White Lead Ore',
    MalayalamName: 'വെള്ള ഈയ അയിര്',
    ScientificName: '',
    DescriptionEnglish: 'Appears on page 23r-1. A lead carbonate and lead hydrate made by corroding lead with vinegar (not found in nature). Used as a pigment and medicine, generally for eye ointments.',
    DescriptionMalayalam: 'ഈയ കാർബണേറ്റ്, ഈയ ഹൈഡ്രേറ്റ്. ചായം, ഔഷധം — പ്രധാനമായും കണ്ണ് ലേഹ്യം.',
    UsesEnglish: 'Pigment; eye ointments.',
    UsesMalayalam: 'ചായം; കണ്ണ് ലേഹ്യം.',
    PageReference: '23r-1',
    SourcePage: 210,
  },
  {
    id: 98,
    category: 'flower',
    ArabicName: 'شقايق الورد',
    EnglishName: 'Windflower (Pasque Flower)',
    MalayalamName: 'വിൻഡ്‌ഫ്ലവർ',
    ScientificName: 'Pulsatilla vulgaris',
    DescriptionEnglish: 'Appears on page 13v, lines 13 and 14. Used to lower arterial tension, dilate the pupils and reduce respiration. Except in small amounts, it is poisonous.',
    DescriptionMalayalam: 'ധമനി സമ്മർദ്ദം കുറക്കൽ, കണ്ണ് വിദ്യാർഥി വിസ്തരണം, ശ്വസനം കുറക്കൽ. അളവ് കൂടിയാൽ വിഷകരം.',
    UsesEnglish: 'Lower arterial tension; dilate pupils; reduce respiration. CAUTION: poisonous except in small amounts.',
    UsesMalayalam: 'ധമനി സമ്മർദ്ദം; കണ്ണ് വിദ്യാർഥി വിസ്തരണം; ശ്വസനം. ജാഗ്രത: വിഷകരം.',
    PageReference: '13v',
    SourcePage: 210,
  },
];