// ═══════════════════════════════════════════════════════════════
// PLANTS DATA — BATCH 3 (entries 46–98)
// Continuation of lib/plantsData.js
// ═══════════════════════════════════════════════════════════════

export const PLANTS_DATA_2 = [
  {
    id: 46,
    category: 'oil',
    ArabicName: 'دهن الرند',
    EnglishName: 'Laurel Ointment',
    MalayalamName: 'ലോറൽ തൈലം',
    ScientificName: 'Laurus nobilis',
    DescriptionEnglish: 'Appears on page 9v-12. An ointment derived from the laurel plant. Used in the treatment of skin diseases.',
    DescriptionMalayalam: 'ലോറൽ സസ്യത്തിൽ നിന്ന് ഉണ്ടാക്കിയ തൈലം. ചർമ്മ രോഗ ചികിത്സ.',
    UsesEnglish: 'Skin diseases.',
    UsesMalayalam: 'ചർമ്മ രോഗ ചികിത്സ.',
    PageReference: '9v-12',
    SourcePage: 201,
  },
  {
    id: 47,
    category: 'flower',
    ArabicName: 'الاستدوش',
    EnglishName: 'Lavender',
    MalayalamName: 'ലാവൻഡർ',
    ScientificName: 'Lavandula angustifolia',
    DescriptionEnglish: 'Appears on page 13v-14. Used in ancient Arab medicine as an expectorant and antispasmodic. In ancient and medieval Europe it was used as a wound herb and worm remedy.',
    DescriptionMalayalam: 'പ്രാചീന അറബ് ചികിത്സയിൽ ശ്വാസ ഉത്തേജക, ആക്ഷേപ നിവാരണ ഔഷധം. മധ്യകാല യൂറോപ്പിൽ മുറിവ് ഔഷധം, കൃമി ഔഷധം.',
    UsesEnglish: 'Expectorant; antispasmodic; wound herb; worm remedy.',
    UsesMalayalam: 'ശ്വാസ ഉത്തേജകം; ആക്ഷേപ ശമനം; മുറിവ് ഭേദം; കൃമി ചികിത്സ.',
    PageReference: '13v-14',
    SourcePage: 201,
  },
  {
    id: 48,
    category: 'herb',
    ArabicName: 'كراث',
    EnglishName: 'Leek',
    MalayalamName: 'ലീക്ക്',
    ScientificName: 'Allium ampeloprasum var porrum',
    DescriptionEnglish: 'Appears on pages 8r-9, 8v-5, and 18r-16. Widely used as a diuretic and laxative, with antiseptic and tonic properties.',
    DescriptionMalayalam: 'മൂത്ര ഉത്തേജകം, വിരേചകം, അണുനാശിനി, ടോണിക് ഗുണങ്ങൾ.',
    UsesEnglish: 'Diuretic; laxative; antiseptic; tonic.',
    UsesMalayalam: 'മൂത്ര ഉത്തേജകം; വിരേചനം; അണുനാശം; ടോണിക്.',
    PageReference: '8r-9, 8v-5, 18r-16',
    SourcePage: 201,
  },
  {
    id: 49,
    category: 'herb',
    ArabicName: 'ترنجان',
    EnglishName: 'Lemon Balm',
    MalayalamName: 'ലെമൺ ബാം',
    ScientificName: 'Melissa officinalis',
    DescriptionEnglish: 'Appears on page 19r-18. Used in all complaints proceeding from a disordered state of the nervous system. Carminative, diaphoretic and febrifuge.',
    DescriptionMalayalam: 'നാഡീ വ്യൂഹ ക്രമക്കേടുകൾ. വാതനാശകം, വിയർപ്പ് ഉത്തേജകം, ജ്വര നിവാരണം.',
    UsesEnglish: 'Nervous system disorders; carminative; diaphoretic; febrifuge.',
    UsesMalayalam: 'നാഡീ ക്രമക്കേട്; വാതനാശം; വിയർപ്പ് ഉത്തേജനം; ജ്വര ശമനം.',
    PageReference: '19r-18',
    SourcePage: 201,
  },
  {
    id: 50,
    category: 'herb',
    ArabicName: 'كشوت',
    EnglishName: 'Lesser Dodder',
    MalayalamName: 'ലെസ്സർ ഡോഡർ',
    ScientificName: 'Cuscuta epithymum',
    DescriptionEnglish: 'Appears on page 14v-5. A parasite on small plants; the version growing on thyme is most used medicinally. Used to treat liver, gallbladder, and spleen disorders. Used as a mild laxative and to treat scurvy. Also for kidney deficiency symptoms: blurred vision, dizziness, tinnitus, and lower back pain.',
    DescriptionMalayalam: 'ചെറു സസ്യ പരാദം. കരൾ, പിത്താശയ, പ്ലീഹ ക്രമക്കേട്. മൃദു വിരേചകം, സ്കർവി ചികിത്സ. വൃക്ക ദൗർബല്യ ലക്ഷണങ്ങൾ: ദൃഷ്ടി മങ്ങൽ, തലകറക്കം, ചെവിയടക്കം, നടുവ്‌വേദന.',
    UsesEnglish: 'Liver, gallbladder, spleen disorders; mild laxative; scurvy; blurred vision; dizziness; tinnitus; lower back pain.',
    UsesMalayalam: 'കരൾ, പ്ലീഹ ചികിത്സ; വിരേചനം; സ്കർവി; ദൃഷ്ടി ശമനം; തലകറക്കം; ചെവിയടക്കം; നടുവ്‌വേദന.',
    PageReference: '14v-5',
    SourcePage: 201,
  },
  {
    id: 51,
    category: 'root',
    ArabicName: 'عروق سوس',
    EnglishName: 'Licorice Root',
    MalayalamName: 'ഇരട്ടിമധുരം',
    ScientificName: 'Glycyrrhiza glabra',
    DescriptionEnglish: 'Appears on page 26r-20. Used in the treatment of infections and both mouth and peptic ulcers. An effective expectorant since ancient times. Also a mild laxative and topical antiviral for shingles.',
    DescriptionMalayalam: 'അണുബാധ, വായ്‌പ്പുണ്ണ്, ആമാശയ വ്രണ ചികിത്സ. ശ്വാസ ഉത്തേജകം, മൃദു വിരേചകം, ഹെർപ്പസ് ആൻറിവൈറൽ.',
    UsesEnglish: 'Infections; mouth and peptic ulcers; expectorant; mild laxative; topical antiviral for shingles.',
    UsesMalayalam: 'അണുബാധ; വ്രണ ചികിത്സ; ശ്വാസ ഉത്തേജകം; വിരേചനം; ഹെർപ്പസ് ആൻറിവൈറൽ.',
    PageReference: '26r-20',
    SourcePage: 201,
  },
  {
    id: 52,
    category: 'spice',
    ArabicName: 'فلفل طويل',
    EnglishName: 'Long Pepper',
    MalayalamName: 'തിപ്പലി',
    ScientificName: 'Piper longum',
    DescriptionEnglish: 'Appears on page 23v-11. Long recognized as an ingredient for stimulating the appetite and as an aid in the relief of nausea.',
    DescriptionMalayalam: 'വിശപ്പ് ഉത്തേജനം, ഓക്കാനം ശമനം.',
    UsesEnglish: 'Stimulate appetite; nausea relief.',
    UsesMalayalam: 'വിശപ്പ് ഉത്തേജനം; ഓക്കാനം ശമനം.',
    PageReference: '23v-11',
    SourcePage: 202,
  },
  {
    id: 53,
    category: 'root',
    ArabicName: 'عروق يبروح',
    EnglishName: 'Mandrake',
    MalayalamName: 'മാൻഡ്രേക്ക്',
    ScientificName: 'Mandragora officinarum',
    DescriptionEnglish: 'Found on pages 25v-9 and 17v-8. Used as a narcotic, an antispasmodic, and for its moderating effect.',
    DescriptionMalayalam: 'മയക്ക ഔഷധം, ആക്ഷേപ ശമനം, ശരീര സന്തുലനം.',
    UsesEnglish: 'Narcotic; antispasmodic; moderating effect.',
    UsesMalayalam: 'മയക്ക ഔഷധം; ആക്ഷേപ ശമനം; ശരീര സന്തുലനം.',
    PageReference: '25v-9, 17v-8',
    SourcePage: 202,
  },
  {
    id: 54,
    category: 'wood',
    ArabicName: 'قرم',
    EnglishName: 'Mangrove',
    MalayalamName: 'കണ്ടൽ',
    ScientificName: 'Avicenna germinas',
    DescriptionEnglish: 'Appears on page 4r-13. Used as a treatment for ringworm, sores and boils, and as a suppressant for coughs.',
    DescriptionMalayalam: 'താമ്രകൃമി, ചൊറിച്ചിൽ, ചെളിക്കുരു ചികിത്സ. ചുമ ഒടുക്കൽ.',
    UsesEnglish: 'Ringworm; sores and boils; cough suppressant.',
    UsesMalayalam: 'താമ്രകൃമി; ചൊറിച്ചിൽ, ചെളിക്കുരു; ചുമ ശമനം.',
    PageReference: '4r-13',
    SourcePage: 202,
  },
  {
    id: 55,
    category: 'herb',
    ArabicName: 'مزرنجوش',
    EnglishName: 'Marjoram',
    MalayalamName: 'മജ്ജോറം',
    ScientificName: 'Origanum majorana',
    DescriptionEnglish: 'Appears on page 14v-5. Native to Middle East, North Africa, and parts of India. Used extensively by ancient Greeks for dropsy, convulsion, and narcotic poisons. Traditional uses include asthma, rheumatism, toothache, indigestion, flatulence, epilepsy, and externally as a liniment for bruises and sprains.',
    DescriptionMalayalam: 'മദ്ധ്യ പൂർവ്വ, വടക്കൻ ആഫ്രിക്ക, ഇന്ത്യ സ്വദേശി. ജലശേഖരം, ആക്ഷേപം, നാർക്കോട്ടിക് വിഷ ചികിത്സ. ആസ്ത്മ, സന്ധിവാതം, പല്ലുവേദന, ദഹനക്കേട്, വായുക്കുഴപ്പം, അപസ്മാരം, ചതവ്, ഉളുക്ക് ലേഹ്യം.',
    UsesEnglish: 'Dropsy; convulsion; narcotic poisons; asthma; rheumatism; toothache; indigestion; flatulence; epilepsy; liniment for bruises and sprains.',
    UsesMalayalam: 'ജലശേഖരം; ആക്ഷേപം; ആസ്ത്മ; സന്ധിവാതം; പല്ലുവേദന; ദഹനക്കേട്; അപസ്മാരം; ചതവ് ലേഹ്യം.',
    PageReference: '14v-5',
    SourcePage: 202,
  },
  {
    id: 56,
    category: 'resin',
    ArabicName: 'المصطقي / المصقا / علق رومي',
    EnglishName: 'Mastic',
    MalayalamName: 'മാസ്റ്റിക്',
    ScientificName: 'Pistacia lentiscus',
    DescriptionEnglish: 'Appears on pages 15v-13, 19v-14, and 20v-18. Used as a medicine for gastrointestinal ailments. Modern research confirms antibacterial and antifungal properties. Traditionally chewed like gum in the Middle East and Southeast Asia, reducing bacterial plaque by up to 40%.',
    DescriptionMalayalam: 'ദഹനേന്ദ്രിയ ക്രമക്കേട് ഔഷധം. ആധുനിക ഗവേഷണം ബാക്ടീരിയ, ഫംഗസ് നിരോധക ഗുണം സ്ഥിരീകരിക്കുന്നു. ഗം ആയി ചവക്കൽ — ബാക്ടീരിയ 40% കുറക്കൽ.',
    UsesEnglish: 'Gastrointestinal ailments; antibacterial; antifungal; dental plaque reduction (chewed as gum).',
    UsesMalayalam: 'ദഹന ചികിത്സ; ബാക്ടീരിയ, ഫംഗസ് ചെറുക്കൽ; ദന്ത ഫലകം കുറക്കൽ.',
    PageReference: '15v-13, 19v-14, 20v-18',
    SourcePage: 202,
  },
  {
    id: 57,
    category: 'other',
    ArabicName: 'لبن حمارة سودا',
    EnglishName: 'Milk (Yoghurt) of a Black She Donkey',
    MalayalamName: 'കറുത്ത പെണ്ണകുതിര പാൽ',
    ScientificName: '',
    DescriptionEnglish: 'Appears on page 4r-12. Historically used as an antidote to poison.',
    DescriptionMalayalam: 'വിഷ പ്രതിവിധി ആയി ഉപയോഗിക്കുന്നു.',
    UsesEnglish: 'Antidote to poison.',
    UsesMalayalam: 'വിഷ പ്രതിവിധി.',
    PageReference: '4r-12',
    SourcePage: 202,
  },
  {
    id: 58,
    category: 'other',
    ArabicName: 'مسك',
    EnglishName: 'Musk',
    MalayalamName: 'കസ്തൂരി',
    ScientificName: 'Moschidae',
    DescriptionEnglish: 'Appears on page 7r, line 15. A fragrant substance from the gland of the musk deer. Played an important part in creating fragrances. Used as a stimulant to the nervous and vascular systems, with narcotic properties. Used for hiccoughs, irregular pulse, muscle spasms, and insomnia. United with ammonia, used to stop gangrene.',
    DescriptionMalayalam: 'കസ്തൂരി മൃഗ ഗ്രന്ഥിയിൽ നിന്ന്. സുഗന്ധ ദ്രവ്യം. നാഡീ, രക്തനാള ഉത്തേജകം. ഓക്കൾ, ഹൃദയ താള ക്രമക്കേട്, പേശി ആക്ഷേപം, ഉറക്കക്കുറവ്. അമോണിയ ചേർത്ത് ഗ്യാൻഗ്രീൻ തടയൽ.',
    UsesEnglish: 'Nervous and vascular stimulant; narcotic; hiccoughs; irregular pulse; muscle spasms; insomnia; stop gangrene (with ammonia).',
    UsesMalayalam: 'നാഡീ ഉത്തേജകം; ഓക്കൾ; ഹൃദയ താളം; പേശി ആക്ഷേപം; ഉറക്കക്കുറവ്; ഗ്യാൻഗ്രീൻ.',
    PageReference: '7r',
    SourcePage: 203,
  },
  {
    id: 59,
    category: 'resin',
    ArabicName: 'مر / معرة',
    EnglishName: 'Myrrh',
    MalayalamName: 'മൂർ',
    ScientificName: 'Commiphora myrrha',
    DescriptionEnglish: 'Appears on page 15r-20. Used in medieval medicine for circulatory problems due to its tonic and rejuvenating properties. Also used as a disinfectant since ancient times.',
    DescriptionMalayalam: 'ടോണിക്, ഉൽജ്ജീവന ഗുണം കൊണ്ട് രക്ത ചംക്രമണ ചികിത്സ. പ്രാചീനകാലം മുതൽ അണുനാശിനി.',
    UsesEnglish: 'Circulatory problems; tonic; disinfectant.',
    UsesMalayalam: 'രക്ത ചംക്രമണ ചികിത്സ; ടോണിക്; അണുനാശകം.',
    PageReference: '15r-20',
    SourcePage: 203,
  },
  {
    id: 60,
    category: 'herb',
    ArabicName: 'آس',
    EnglishName: 'Myrtle',
    MalayalamName: 'മർടിൽ',
    ScientificName: 'Myrtus communis',
    DescriptionEnglish: 'Appears on page 27r-14. Astringent, antiseptic and tonic properties of its leaves made it ideal for wound healing. Taken internally for digestive and urinary system disorders.',
    DescriptionMalayalam: 'ഇലകളിലെ ഖര, അണുനാശ, ടോണിക് ഗുണം — മുറിവ് ഉണക്കൽ. ദഹന, മൂത്ര വ്യൂഹ ക്രമക്കേട്.',
    UsesEnglish: 'Wound healing; digestive disorders; urinary disorders.',
    UsesMalayalam: 'മുറിവ് ഉണക്കൽ; ദഹന ക്രമക്കേട്; മൂത്ര ക്രമക്കേട്.',
    PageReference: '27r-14',
    SourcePage: 203,
  },
  {
    id: 61,
    category: 'other',
    ArabicName: 'نفط ابيض',
    EnglishName: 'Naphtha (White)',
    MalayalamName: 'വെള്ള നഫ്ത',
    ScientificName: '',
    DescriptionEnglish: 'Found on page 25v-17. Ingested in small doses for cough, asthma, bladder discomfort and arthritis. Taken internally to relieve cramps and belly aches. Applied topically for skin rashes and infections. Also used in incense preparations.',
    DescriptionMalayalam: 'ചെറിയ ഡോസ്: ചുമ, ആസ്ത്മ, മൂത്രാശയ ബുദ്ധിമുട്ട്, സന്ധിവാതം. ഉദര വേദന, ക്രമ്പ്. ബാഹ്യ പ്രയോഗം: ചർമ്മ ചൊറിച്ചിൽ, അണുബാധ. ധൂപ ദ്രവ്യം.',
    UsesEnglish: 'Cough; asthma; bladder discomfort; arthritis; cramps; skin rashes; incense.',
    UsesMalayalam: 'ചുമ; ആസ്ത്മ; മൂത്രാശയ ബുദ്ധിമുട്ട്; സന്ധിവാതം; ക്രമ്പ്; ചർമ്മ ചൊറിച്ചിൽ.',
    PageReference: '25v-17',
    SourcePage: 203,
  },
  {
    id: 62,
    category: 'resin',
    ArabicName: 'وشق',
    EnglishName: 'North African Giant Fennel',
    MalayalamName: 'വടക്കൻ ആഫ്രിക്കൻ ഫെന്നൽ',
    ScientificName: 'Ferula tingitana',
    DescriptionEnglish: 'Appears on page 8v-8. Grows in North Africa. Produces ammoniacum (gum ammoniac) mentioned by Dioscorides. Used in fumigation and as a component in recipes for curing eye diseases.',
    DescriptionMalayalam: 'വടക്കൻ ആഫ്രിക്ക. ഗം അമ്മോണിയക് ഉൽപ്പാദിപ്പിക്കുന്നു. ധൂപ ആവശ്യം, നേത്ര രോഗ ചിട്ടവട്ടങ്ങൾ.',
    UsesEnglish: 'Fumigation; eye disease remedies.',
    UsesMalayalam: 'ധൂപം; നേത്ര രോഗ ചികിത്സ.',
    PageReference: '8v-8',
    SourcePage: 203,
  },
  {
    id: 63,
    category: 'resin',
    ArabicName: 'كندر',
    EnglishName: 'Olibanum (Male Frankincense)',
    MalayalamName: 'ഒലിബനം',
    ScientificName: 'Boswellia',
    DescriptionEnglish: 'Appears on pages 4r, 7r lines 14–15. A resin from Boswellia trees in Arabia and Somalia used since ancient Egyptian times. Used to heal abrasions, cuts, and bronchitis, and for gingivitis. Avicenna recommended it for tumors, ulcers, vomiting, dysentery, and fevers. Its aroma is considered healing. Modern science finds it increases white blood cell count.',
    DescriptionMalayalam: 'അറേബ്യ, സൊമാലിയ ബോസ്‌വെല്ല മരത്തിൽ നിന്ന്. ഉരസൽ, മുറിവ്, ബ്രോങ്കൈറ്റിസ്, ദന്ത ജ്വലനം. ഇബ്നു സീന: മുഴ, വ്രണം, ഛർദ്ദി, ഒഴിച്ചിൽ, ജ്വരം. ശ്വേത രക്താണു വർദ്ധനവ്.',
    UsesEnglish: 'Abrasions; cuts; bronchitis; gingivitis; tumors; ulcers; vomiting; dysentery; fevers; increases white blood cell count.',
    UsesMalayalam: 'ഉരസൽ, മുറിവ്; ബ്രോങ്കൈറ്റിസ്; ദന്ത ജ്വലനം; മുഴ; വ്രണം; ഛർദ്ദി; ഒഴിച്ചിൽ; ജ്വരം.',
    PageReference: '4r, 7r',
    SourcePage: 204,
  },
  {
    id: 64,
    category: 'herb',
    ArabicName: 'أفيون',
    EnglishName: 'Opium',
    MalayalamName: 'കറുപ്പ്',
    ScientificName: 'Papaver somniferum',
    DescriptionEnglish: 'Appears on pages 3v-16, 4r-16, 8r-6, 8v-8, 29r-21, 20v-3, and 23r-19. Known since 4000 BC. Used by ancient Macedonians, Egyptians, Arabs, and Romans. Commonly used for severe diarrhea and as an effective painkiller. Considered the first authentic anti-depressant. Unripe seed pods were used to prevent excessive crying in children. Use spread to Arabia, India and China by the 8th century AD.',
    DescriptionMalayalam: 'ക്രി.മു. 4000 മുതൽ അറിവ്. ഗുരുതര വയറിളക്കം, ഫലപ്രദ വേദന ശമനം. ആദ്യ ആൻറി-ഡിപ്രസന്റ്. കുട്ടികളിൽ അനിയന്ത്രിത കരച്ചിൽ.',
    UsesEnglish: 'Severe diarrhea; pain relief; anti-depressant; prevent excessive crying in children.',
    UsesMalayalam: 'ഗുരുതര വയറിളക്കം; വേദന ശമനം; ആൻറി-ഡിപ്രസന്റ്; കുട്ടി കരച്ചിൽ.',
    PageReference: '3v-16, 4r-16, 8r-6, 8v-8, 29r-21, 20v-3, 23r-19',
    SourcePage: 204,
  },
  {
    id: 65,
    category: 'resin',
    ArabicName: 'ببنق / جوشير',
    EnglishName: 'Opopanax',
    MalayalamName: 'ഒപ്പൊപ്പനാക്സ്',
    ScientificName: 'Opopanax chironium',
    DescriptionEnglish: 'Appears on pages 5v, 6v, 21r, and 9v. A species of parsnip, also known as sweet myrrh. Tea from roots used for women\'s complaints. Poultice of roots for inflammations and sores. Leaves and roots used as insect spray for plants.',
    DescriptionMalayalam: 'പാർസ്‌നിപ് ഇനം, സ്വീറ്റ് മൂർ എന്നും അറിയപ്പെടുന്നു. വേർ ചായ: സ്ത്രീ ആരോഗ്യ ചികിത്സ. വേർ ലേഹ്യം: ജ്വലനം, ചൊറിച്ചിൽ. ഇല, വേർ: സസ്യ കീടനാശിനി.',
    UsesEnglish: 'Women\'s complaints (root tea); inflammations and sores (poultice); insect spray for plants.',
    UsesMalayalam: 'സ്ത്രീ ആരോഗ്യ ചായ; ജ്വലന ലേഹ്യം; സസ്യ കീടനാശിനി.',
    PageReference: '5v, 6v, 21r, 9v',
    SourcePage: 205,
  },
  {
    id: 66,
    category: 'seed',
    ArabicName: 'زبيب الجبل',
    EnglishName: 'Palmated Larkspur (Stavesacre)',
    MalayalamName: 'സ്റ്റേവ്‌സേക്ർ',
    ScientificName: 'Delphinium staphysagria',
    DescriptionEnglish: 'Appears on page 10v-2. Taken internally to cause vomiting and purge the bowels. Applied externally as an ointment as an antidote to stings and bites. Seeds contain an ingredient that kills head lice.',
    DescriptionMalayalam: 'ഛർദ്ദി ഉണ്ടാക്കൽ, കുടൽ ശുദ്ധീകരണം. കുത്ത്, കടി പ്രതിവിധി (ബാഹ്യ). വിത്ത്: ചൂണ്ടൻ കൃമി നാശം.',
    UsesEnglish: 'Induce vomiting; purge bowels; antidote to stings and bites; kill head lice.',
    UsesMalayalam: 'ഛർദ്ദി; കുടൽ ശുദ്ധീകരണം; കടി പ്രതിവിധി; ചൂണ്ടൻ കൃമി നാശം.',
    PageReference: '10v-2',
    SourcePage: 205,
  },
  {
    id: 67,
    category: 'root',
    ArabicName: 'عاقر قرحا',
    EnglishName: 'Pellitory',
    MalayalamName: 'അക്കർകര',
    ScientificName: 'Anacyclus pyrethrum',
    DescriptionEnglish: 'Appears on pages 3r, 8v-4, and 19r-3. Aphrodisiac; tonic for the nervous system; remedy for gum inflammations and toothaches; rheumatic conditions; aid digestion. Also for sore throat, paralysis, and epilepsy. Originally from Morocco and Syria, found across North Africa, North India, Mediterranean and Arabia.',
    DescriptionMalayalam: 'ആദ്യ ലൈംഗിക ഉത്തേജകം. നാഡീ ടോണിക്. ദന്ത ജ്വലനം, പല്ലുവേദന, സന്ധിവാതം, ദഹന സഹായം. തൊണ്ട വേദന, തളർവാതം, അപസ്മാരം.',
    UsesEnglish: 'Aphrodisiac; nervous system tonic; gum inflammation; toothache; rheumatism; digestion; sore throat; paralysis; epilepsy.',
    UsesMalayalam: 'ലൈംഗിക ഉത്തേജകം; നാഡീ ടോണിക്; ദന്ത ജ്വലനം; പല്ലുവേദന; സന്ധിവാതം; ദഹനം; തൊണ്ട വേദന; അപസ്മാരം.',
    PageReference: '3r, 8v-4, 19r-3',
    SourcePage: 205,
  },
  {
    id: 68,
    category: 'spice',
    ArabicName: 'فلفل',
    EnglishName: 'Pepper',
    MalayalamName: 'കുരുമുളക്',
    ScientificName: 'Piper nigrum',
    DescriptionEnglish: 'Appears on page 23v-11. Used in wine mixtures for stomach pain and diseases involving excessive cold humors such as overproduction of phlegm in respiratory illness. Beverages ranged from aphrodisiacs and digestives to cold prevention and bronchitis therapy.',
    DescriptionMalayalam: 'ഉദര വേദന, ശ്ലേഷ്മ ശ്വസന രോഗ ചികിത്സ. ലൈംഗിക ഉത്തേജക, ദഹന, ജലദോഷ, ബ്രോങ്കൈറ്റിസ് ചികിത്സ.',
    UsesEnglish: 'Stomach pain; phlegm excess; respiratory illness; digestive; cold prevention; bronchitis.',
    UsesMalayalam: 'ഉദര വേദന; ശ്ലേഷ്മ ശ്വസന; ദഹനം; ജലദോഷ; ബ്രോങ്കൈറ്റിസ്.',
    PageReference: '23v-11',
    SourcePage: 206,
  },
  {
    id: 69,
    category: 'other',
    ArabicName: 'عطر',
    EnglishName: 'Perfume',
    MalayalamName: 'സുഗന്ധദ്രവ്യം',
    ScientificName: '',
    DescriptionEnglish: 'Appears on page 9r-6. Part of the "kingly compounds." Used for aromatherapy, strengthening the body\'s vitality, overcoming migraines and headaches, as an aphrodisiac, and for back pain and women\'s disorders.',
    DescriptionMalayalam: '"രാജകീയ ഔഷധ" ഭാഗം. അരോമ ചികിത്സ, ഊർജ്ജ ശക്തിവർദ്ധനം, മൈഗ്രൈൻ, തലവേദന ശമനം, ലൈംഗിക ഉത്തേജകം, നടുവ്‌വേദന, സ്ത്രീ ആരോഗ്യ ക്രമക്കേട്.',
    UsesEnglish: 'Aromatherapy; strengthen vitality; migraines; headaches; aphrodisiac; back pain; women\'s disorders.',
    UsesMalayalam: 'അരോമ ചികിത്സ; ഊർജ്ജ ശക്തി; മൈഗ്രൈൻ; തലവേദന; ലൈംഗിക ഉത്തേജകം; നടുവ്‌വേദന; സ്ത്രീ ആരോഗ്യം.',
    PageReference: '9r-6',
    SourcePage: 206,
  },
  {
    id: 70,
    category: 'herb',
    ArabicName: 'الما ميران',
    EnglishName: 'Pilewort (Greater Celandine)',
    MalayalamName: 'ഗ്രേറ്റർ സെലൻഡൈൻ',
    ScientificName: 'Chelidonium majus',
    DescriptionEnglish: 'Appears on page 14v-19. Called pilewort because it was used in the cure of hemorrhoids, and scurvywort because it could treat scurvy. Its leaves are very high in Vitamin C.',
    DescriptionMalayalam: 'മൂലം ചികിത്സ (pilewort). സ്കർവി ചികിത്സ (scurvywort). ഇലകൾ വിറ്റാമിൻ C ഉൾള്ളവ.',
    UsesEnglish: 'Hemorrhoids; scurvy.',
    UsesMalayalam: 'മൂലം; സ്കർവി.',
    PageReference: '14v-19',
    SourcePage: 206,
  },
  {
    id: 71,
    category: 'flower',
    ArabicName: 'طلع النخل',
    EnglishName: 'Pollen of the Male Palm Tree',
    MalayalamName: 'ആൺ ഈന്തപ്പന പൂമ്പൊടി',
    ScientificName: 'Arecaceae phoenix',
    DescriptionEnglish: 'Found on pages 25r-9 and 6v-18. Pollen of the male date palm mixed with water was used as a charm against childlessness. Modern science has discovered that the pollen contains the estrogenic hormone estrone and exhibits gonadotrophic activity.',
    DescriptionMalayalam: 'ആൺ ഈന്തപ്പന പൂമ്പൊടി വെള്ളത്തിൽ കലക്കൽ — ന്ത്ര്യ ചികിത്സ. ആധുനിക ഗവേഷണം: ഈസ്ട്രോൺ ഹോർമോൺ, ഗൊണഡോട്രോഫിക് ഗുണം.',
    UsesEnglish: 'Charm against childlessness; estrogenic activity.',
    UsesMalayalam: 'ന്ത്ര്യ ചികിത്സ; ഈസ്ട്രോജൻ ഗുണം.',
    PageReference: '25r-9, 6v-18',
    SourcePage: 206,
  },
  {
    id: 72,
    category: 'flower',
    ArabicName: 'ماء الورد',
    EnglishName: 'Rosewater',
    MalayalamName: 'റോസ് ജലം',
    ScientificName: '',
    DescriptionEnglish: 'Appears on pages 8v-6 and 9r-6. Ibn Sina recommended bathing in a herbal mixture including rosewater for removal of stones in the urinary tract. Mildly astringent and used as a lotion for inflamed and sore eyes.',
    DescriptionMalayalam: 'ഇബ്നു സീന: മൂത്ര കല്ല് നീക്കം — ഔഷധ കുളി. നേത്ര ജ്വലനം, ചൊറിച്ചിൽ ലോഷൻ.',
    UsesEnglish: 'Urinary tract stone removal (herbal bath); inflamed and sore eye lotion.',
    UsesMalayalam: 'മൂത്ര കല്ല്; നേത്ര ജ്വലന ലോഷൻ.',
    PageReference: '8v-6, 9r-6',
    SourcePage: 207,
  },
  {
    id: 73,
    category: 'herb',
    ArabicName: 'ماء السداب',
    EnglishName: 'Rue Liquid Extract',
    MalayalamName: 'റൂ തൈലം',
    ScientificName: 'Ruta graveolens',
    DescriptionEnglish: 'Appears on pages 6v-23, 23v-12, 26r-20, and 26v-1. Rue liquid extract used to prepare eyewashes and stomach tonics. Also used as a defense against the evil eye.',
    DescriptionMalayalam: 'കണ്ണ് കഴുകൽ, ഉദര ടോണിക് തയ്യാറാക്കൽ. ദൃഷ്ടി ദോഷ നിർമ്മാർജ്ജനം.',
    UsesEnglish: 'Eyewashes; stomach tonics; defense against evil eye.',
    UsesMalayalam: 'കണ്ണ് കഴുകൽ; ഉദര ടോണിക്; ദൃഷ്ടി ദോഷ നിർമ്മാർജ്ജനം.',
    PageReference: '6v-23, 23v-12, 26r-20, 26v-1',
    SourcePage: 207,
  },
  {
    id: 74,
    category: 'flower',
    ArabicName: 'عروق القرطم / عصفور',
    EnglishName: 'Safflower',
    MalayalamName: 'കുസുംഭ',
    ScientificName: 'Carthamus tinctorius',
    DescriptionEnglish: 'Appears on page 16v-20. Cultivated in Egypt and South Asia for food and medicine. Produces yellow dye. Used as a laxative, sedative, and diaphoretic. Seeds used for liver tumors and rheumatism and sores.',
    DescriptionMalayalam: 'ഈജിപ്ത്, ദക്ഷിണ ഏഷ്യ. മഞ്ഞ ചായം. വിരേചകം, ഉറക്ക ഔഷധം, വിയർപ്പ് ഉത്തേജകം. കരൾ മുഴ, സന്ധിവാതം, ചൊറിച്ചിൽ ചികിത്സ.',
    UsesEnglish: 'Yellow dye; laxative; sedative; diaphoretic; liver tumors; rheumatism; sores.',
    UsesMalayalam: 'ചായം; വിരേചനം; ഉറക്ക ഔഷധം; കരൾ മുഴ; സന്ധിവാതം.',
    PageReference: '16v-20',
    SourcePage: 207,
  },
  {
    id: 75,
    category: 'spice',
    ArabicName: 'زعفران',
    EnglishName: 'Saffron',
    MalayalamName: 'കുങ്കുമം',
    ScientificName: 'Crocus sativus',
    DescriptionEnglish: 'Appears on many pages (5v, 8v, 9r, 14v, 20v, 29v). Originally called Kurkum in Hebrew and Aramaic. Used as a drug and condiment. Uses include treatment of arthritis and asthma, reducing fever, and healing the liver. Highly valued in Unani and Ayurvedic medicine.',
    DescriptionMalayalam: 'ഹീബ്രൂ, അരാമിക്കിൽ കുർകും. ഔഷധ, സുഗന്ധ ദ്രവ്യം. സന്ധിവാതം, ആസ്ത്മ, ജ്വര ശമനം, കരൾ ഉണക്കൽ. യൂനാനി, ആയുർവേദ ചികിത്സ.',
    UsesEnglish: 'Arthritis; asthma; reduce fever; liver healing. Valued in Unani and Ayurvedic medicine.',
    UsesMalayalam: 'സന്ധിവാതം; ആസ്ത്മ; ജ്വര ശമനം; കരൾ ഉണക്കൽ.',
    PageReference: '5v, 8v, 9r, 14v, 20v, 29v',
    SourcePage: 207,
  },
  {
    id: 76,
    category: 'resin',
    ArabicName: 'ساقبينج',
    EnglishName: 'Sagapenum',
    MalayalamName: 'സഗേപ്പിനം',
    ScientificName: 'Ferula Persica',
    DescriptionEnglish: 'Appears on pages 8r-7 and 20v-18. Grows in Arabia and Persia. A gum-resin with a garlicky smell, less pungent than asafetida but more powerful than olibanum. Used in the treatment of amenorrhea and hysteria.',
    DescriptionMalayalam: 'അറേബ്യ, പേർഷ്യ. ഉള്ളി മണം ഉള്ള ഗം-റെസിൻ. ആർത്തവ ക്രമക്കേട്, ഹിസ്റ്റീരിയ ചികിത്സ.',
    UsesEnglish: 'Amenorrhea; hysteria.',
    UsesMalayalam: 'ആർത്തവ ക്രമക്കേട്; ഹിസ്റ്റീരിയ.',
    PageReference: '8r-7, 20v-18',
    SourcePage: 208,
  },
  {
    id: 77,
    category: 'other',
    ArabicName: 'زبد البحر',
    EnglishName: 'Sea Sponge (Pumice)',
    MalayalamName: 'കടൽ സ്പോഞ്ച്',
    ScientificName: '',
    DescriptionEnglish: 'Appears on pages 8v-4 and 17v-8. In medieval times, pumice (magnesium silicate) was thought to be sea sponge or sea foam. Used for hair removal and in ointments mixed with beeswax for scabies and skin problems such as ringworm.',
    DescriptionMalayalam: 'മധ്യകാലം: പ്യൂമൈസ് — കടൽ സ്പോഞ്ച് ആണെന്ന് കരുതി. രോമ നീക്കം, ചൊറിച്ചിൽ, ചർമ്മ ക്രമക്കേട് ലേഹ്യം (ഇളക്ക മെഴുക് ചേർത്ത്).',
    UsesEnglish: 'Hair removal; scabies ointment (with beeswax); ringworm and skin problems.',
    UsesMalayalam: 'രോമ നീക്കം; ചൊറിച്ചിൽ ലേഹ്യം; ചർമ്മ ചികിത്സ.',
    PageReference: '8v-4, 17v-8',
    SourcePage: 208,
  },
  {
    id: 78,
    category: 'seed',
    ArabicName: 'سمسم / جلجلان',
    EnglishName: 'Sesame',
    MalayalamName: 'എള്ള്',
    ScientificName: 'Sesamum orientale',
    DescriptionEnglish: 'Appears on page 24r-4. Native to India. Medicinal uses include treatment of cholera, constipation, cough, scalds, ulcers, burns, and amenorrhea. Mixed with almond, honey, and sugar as a nutritional regimen in the manuscript.',
    DescriptionMalayalam: 'ഇന്ത്യ സ്വദേശി. കോളറ, മലബന്ധം, ചുമ, പൊള്ളൽ, വ്രണം, ആർത്തവ ക്രമക്കേട് ചികിത്സ. ബദാം, തേൻ, പഞ്ചസാര ചേർത്ത് പോഷക ഭക്ഷണം.',
    UsesEnglish: 'Cholera; constipation; cough; scalds; ulcers; burns; amenorrhea; nutritional regimen.',
    UsesMalayalam: 'കോളറ; മലബന്ധം; ചുമ; പൊള്ളൽ; വ്രണം; ആർത്തവ ക്രമക്കേട്.',
    PageReference: '24r-4',
    SourcePage: 208,
  },
  {
    id: 79,
    category: 'resin',
    ArabicName: 'سقمونيا',
    EnglishName: 'Scammony',
    MalayalamName: 'സ്കാമ്മോണി',
    ScientificName: 'Convolvulus Scammonia',
    DescriptionEnglish: 'Appears on page 5v, line 16. Arabic name translates as "the praised one." Still used in Egypt. Its juices make a resin used as a drastic cathartic and hydragogue — a purgative causing abundant watery discharge. Had to be used with extreme caution.',
    DescriptionMalayalam: 'അറബി: "പ്രശംസിക്കപ്പെട്ടത്." ഈജിപ്തിൽ ഇന്നും ഉപയോഗം. ജ്യൂസ് — ശക്തമായ ഉദര ശുദ്ധീകരണ, ജലം-ഒഴുക്ക് ഔഷധം. ജാഗ്രത ആവശ്യം.',
    UsesEnglish: 'Drastic cathartic; hydragogue (purgative causing abundant watery discharge). Use with extreme caution.',
    UsesMalayalam: 'ശക്ത ഉദര ശുദ്ധീകരണം; ജലം-ഒഴുക്ക് ഔഷധം.',
    PageReference: '5v',
    SourcePage: 208,
  },
  {
    id: 80,
    category: 'herb',
    ArabicName: 'الزروند الطويل',
    EnglishName: 'Smearwort',
    MalayalamName: 'സ്മിയർ‌വർട്ട്',
    ScientificName: 'Aristolochia rotunda',
    DescriptionEnglish: 'Appears on pages 8r-7 and 19v-13. Considered toxic; its active ingredient aristolochic acid has mixed research results — possibly carcinogenic but also potentially anticancerous. May increase cellular immunity. Can harm kidneys. Large doses can cause abortions and mucous inflammations. Used to suppress menstrual flow.',
    DescriptionMalayalam: 'വിഷകരം. അരിസ്റ്റോലോക്കിക് ആസിഡ് — ഗവേഷണ ഫലം മിശ്രിതം. ആർത്തവ ഒഴുക്ക് ശമനം. വൃക്ക ദ്രോഹ സാധ്യത, ഗർഭ ഭ്രംശ അപകടം.',
    UsesEnglish: 'Suppress menstrual flow. CAUTION: toxic; potentially carcinogenic; harmful to kidneys; large doses may cause abortion.',
    UsesMalayalam: 'ആർത്തവ ഒഴുക്ക് ശമനം. ജാഗ്രത: വിഷകരം, വൃക്ക ദ്രോഹം.',
    PageReference: '8r-7, 19v-13',
    SourcePage: 208,
  },
  {
    id: 81,
    category: 'root',
    ArabicName: 'جنطيانا',
    EnglishName: 'Soapwort Gentian',
    MalayalamName: 'സോപ്‌വർട്ട് ജന്റിയൻ',
    ScientificName: 'Saponaria officinalis',
    DescriptionEnglish: 'Appears on pages 6r, 15r, 21v, and 23r. Root yellow inside, black outside. Used as an emetic and in purging medicine. Treatment for ringworm. Also sniffed as a powder to strengthen tired eyes and stop blindness.',
    DescriptionMalayalam: 'ഉൾ ഭാഗം മഞ്ഞ, പുറം കറുപ്പ്. ഛർദ്ദി ഉണ്ടാക്കൽ, ശുദ്ധീകരണ ഔഷധം. താമ്ര കൃമി ചികിത്സ. ക്ഷീണിച്ച കണ്ണ് ശക്തിപ്പെടുത്തൽ, അന്ധത തടയൽ (ഘ്രാണം).',
    UsesEnglish: 'Emetic; purging; ringworm; strengthen tired eyes (sniffed as powder); stop blindness.',
    UsesMalayalam: 'ഛർദ്ദി; ശുദ്ധീകരണം; താമ്ര കൃമി; നേത്ര ശക്തി; അന്ധത ചികിത്സ.',
    PageReference: '6r, 15r, 21v, 23r',
    SourcePage: 209,
  },
  {
    id: 82,
    category: 'other',
    ArabicName: 'خل',
    EnglishName: 'Sour Wine (Vinegar)',
    MalayalamName: 'വിനാഗിരി',
    ScientificName: '',
    DescriptionEnglish: 'Appears on page 27v-14. Vinegar has been used as an antimicrobial for thousands of years, killing a large majority of bacteria on contact. Though alcohol is prohibited in Islamic law, physicians recommended it as a rinse for mouth ulcers, gargle for sore throats, and internally in moderation for melancholy and mood disorders.',
    DescriptionMalayalam: 'ആയിരം വർഷത്തിലധികം ബാക്ടീരിയ നാശകം. ഇസ്ലാം നിയമം ഒഴിവാക്കുമ്പോഴും വൈദ്യന്മാർ: വായ്‌പ്പുണ്ണ് കഴുകൽ, തൊണ്ട ഗ്ലർഗ്ഗൾ, ഉദ്വേഗം, മൂഡ് ക്രമക്കേട്.',
    UsesEnglish: 'Antimicrobial; mouth ulcer rinse; sore throat gargle; melancholy and mood disorders (internal, moderate).',
    UsesMalayalam: 'ബാക്ടീരിയ നാശം; വായ്‌പ്പുണ്ണ്; തൊണ്ട ഗ്ലർഗ്ഗൾ; ഉദ്വേഗ ശമനം.',
    PageReference: '27v-14',
    SourcePage: 209,
  },
  {
    id: 83,
    category: 'resin',
    ArabicName: 'المَيْعة',
    EnglishName: 'Storax (Benzoin)',
    MalayalamName: 'സ്റ്റൊറാക്സ്',
    ScientificName: 'Liquidambar / Styrax officinale',
    DescriptionEnglish: 'Appears on page 24r-13. Also known as benzoin. Burned as incense to cleanse the surrounding area.',
    DescriptionMalayalam: 'ബെൻസോയിൻ എന്നും അറിയപ്പെടുന്നു. ചുറ്റുപാട് ശുദ്ധീകരിക്കാൻ ധൂപം ആയി കത്തിക്കുന്നു.',
    UsesEnglish: 'Burned as incense to cleanse surroundings.',
    UsesMalayalam: 'ചുറ്റുപാട് ശുദ്ധീകരണ ധൂപം.',
    PageReference: '24r-13',
    SourcePage: 209,
  },
  {
    id: 84,
    category: 'herb',
    ArabicName: 'ماء اوصل السلق',
    EnglishName: 'Swiss Chard Juice',
    MalayalamName: 'ചീര ജ്യൂസ്',
    ScientificName: 'Beta vulgaris',
    DescriptionEnglish: 'Appears on pages 6r, line 11 and 21v, line 13. Juice of Swiss chard or spinach beets. Used as a remedy for anemia and yellow fever.',
    DescriptionMalayalam: 'ചീര അല്ലെങ്കിൽ ചീര-ബീറ്റ് ജ്യൂസ്. വിളർച്ച, മഞ്ഞപ്പനി ചികിത്സ.',
    UsesEnglish: 'Anemia; yellow fever.',
    UsesMalayalam: 'വിളർച്ച; മഞ്ഞപ്പനി.',
    PageReference: '6r, 21v',
    SourcePage: 209,
  },
  {
    id: 85,
    category: 'other',
    ArabicName: 'قطران شامى',
    EnglishName: 'Syrian Tar',
    MalayalamName: 'സിറിയൻ ടാർ',
    ScientificName: '',
    DescriptionEnglish: 'Appears on page 29r-15. A vegetable tar from a small shrub near the Red Sea and Syria. One of the earliest known antiseptics, used in ancient Egyptian mummification.',
    DescriptionMalayalam: 'ചെങ്കടൽ, സിറിയ ഭാഗത്തെ ചെറു ഗ്ലൌ. ആദ്യകാല അണുനാശിനി — പ്രാചീന ഈജിപ്ത് മമ്മി സൂക്ഷ്മ.',
    UsesEnglish: 'Antiseptic; historically used in mummification.',
    UsesMalayalam: 'അണുനാശിനി; മമ്മി സൂക്ഷ്മ.',
    PageReference: '29r-15',
    SourcePage: 209,
  },
  {
    id: 86,
    category: 'resin',
    ArabicName: 'غم غرند',
    EnglishName: 'Syrian Tragacanth',
    MalayalamName: 'ട്രാഗകാന്ത്',
    ScientificName: 'Astragalus gummifer',
    DescriptionEnglish: 'Appears on page 10v-18. Its gummy exudate was used to give consistency to lozenges and in making emulsions.',
    DescriptionMalayalam: 'ഗം: ലോസഞ്ചർ (throat drops) ഉണ്ടാക്കൽ, ഇമൾഷൻ തയ്യാറാക്കൽ.',
    UsesEnglish: 'Binder for lozenges; making emulsions.',
    UsesMalayalam: 'ലോസഞ്ചർ ഘടകം; ഇമൾഷൻ.',
    PageReference: '10v-18',
    SourcePage: 210,
  },
  {
    id: 87,
    category: 'wood',
    ArabicName: 'الطرفا',
    EnglishName: 'Tamarisk',
    MalayalamName: 'തമരിക്ക്',
    ScientificName: 'Tamarix aphylla',
    DescriptionEnglish: 'Root on page 19v-14; wood on page 23v-14. Leaf decoction for eye inflammation and fevers. Roots and bark used to repel insects, thus preventing insect-borne diseases such as black fever carried by sand fleas.',
    DescriptionMalayalam: 'ഇല കഷായം: നേത്ര ജ്വലനം, ജ്വരം. വേര്, തൊലി: കീടനിരോധകം — മണൽ ചെള്ള് കറുത്ത പനി തടയൽ.',
    UsesEnglish: 'Eye inflammation; fevers (leaf decoction); insect repellent; prevent insect-borne diseases.',
    UsesMalayalam: 'നേത്ര ജ്വലനം; ജ്വരം; കീടനിരോധകം; കീടജന്യ രോഗ തടയൽ.',
    PageReference: '19v-14, 23v-14',
    SourcePage: 210,
  },
  {
    id: 88,
    category: 'fruit',
    ArabicName: 'عصير العنب غير مخمر',
    EnglishName: 'Unfermented Grape Juice (Must)',
    MalayalamName: 'ഉണക്ക മുന്തിരി ജ്യൂസ്',
    ScientificName: '',
    DescriptionEnglish: 'Appears on page 24r-4. Unfermented grape juice (Spanish: mosto; French: must). The manuscript admonishes abstinence from it as part of the recommended nutritional treatment.',
    DescriptionMalayalam: 'ഉണക്ക മുന്തിരി ജ്യൂസ് (mosto/must). ഗ്രന്ഥം: പോഷക ചികിത്സ ഭാഗമായി ഒഴിവാക്കൽ ശുപാർശ.',
    UsesEnglish: 'Referenced in nutritional context; manuscript advises abstinence.',
    UsesMalayalam: 'പോഷക ചികിത്സ സന്ദർഭം; ഒഴിവാക്കൽ ശുപാർശ.',
    PageReference: '24r-4',
    SourcePage: 210,
  },
  {
    id: 89,
    category: 'other',
    ArabicName: 'بول / روث',
    EnglishName: 'Urine (Various Animals)',
    MalayalamName: 'ജന്തു മൂത്രം',
    ScientificName: '',
    DescriptionEnglish: 'Various urines appear: boy urine (3r-20, 3v-2), black bull urine (3v-2), generic bull urine (4v-11, 13r-1, 23r-19), siring bull urine (16v-6, 16-7), male goat urine (11r-5). Generally sniffed as an ingredient in healing mixtures. Had a salutary effect on those possessed by malefic entities.',
    DescriptionMalayalam: 'ആൺ കുട്ടി, കറുത്ത കാള, ഒട്ടകം, ആട് മൂത്രം. ഘ്രാണ ഔഷധ ഭാഗം. ദുഷ്ടാത്മ ബാധ ചികിത്സ.',
    UsesEnglish: 'Sniffed as component in healing mixtures; treatment of those possessed by malefic entities.',
    UsesMalayalam: 'ഘ്രാണ ഔഷധ ഘടകം; ദുഷ്ടാത്മ ബാധ ചികിത്സ.',
    PageReference: '3r-20, 3v-2, 4v-11, 11r-5, 16v-6',
    SourcePage: 210,
  },
  {
    id: 90,
    category: 'herb',
    ArabicName: 'ورق الجوز',
    EnglishName: 'Walnut Leaf',
    MalayalamName: 'വാൽനട്ട് ഇല',
    ScientificName: 'Juglandaceae',
    DescriptionEnglish: 'Appears on page 27r-13. Used as an antiseptic and as an infusion to treat toxic blood conditions.',
    DescriptionMalayalam: 'അണുനാശിനി, വിഷ രക്ത ചികിത്സ (ഇൻഫ്യൂഷൻ).',
    UsesEnglish: 'Antiseptic; treat toxic blood conditions.',
    UsesMalayalam: 'അണുനാശകം; വിഷ രക്ത ചികിത്സ.',
    PageReference: '27r-13',
    SourcePage: 210,
  },
  {
    id: 91,
    category: 'herb',
    ArabicName: 'ورس',
    EnglishName: 'Warrus',
    MalayalamName: 'വോർഴ്‌സ്',
    ScientificName: 'Flemingia rhodocarpa Baker',
    DescriptionEnglish: 'Appears on page 5v, line 16. A red coloring substance used in dyes. Grows in India, South Arabia, and Abyssinia. Decoction used for bathing sores and swellings. Also an antipyretic for postpartum fever and for paralysis and joint pain.',
    DescriptionMalayalam: 'ഇന്ത്യ, ദക്ഷിണ അറേബ്യ, ഇത്യോപ്യ. ചുവന്ന ചായ. ചൊറിച്ചിൽ, നീർക്കെട്ട് കുളി. പ്രസവ ശേഷ ജ്വര ശമനം, തളർവാതം, സന്ധി വേദന.',
    UsesEnglish: 'Red dye; bathe sores and swellings; antipyretic for postpartum fever; paralysis; joint pain.',
    UsesMalayalam: 'ചുവന്ന ചായം; ചൊറിച്ചിൽ, നീർക്കെട്ട് കഴുകൽ; പ്രസവ ജ്വരം; തളർവാതം; സന്ധി വേദന.',
    PageReference: '5v',
    SourcePage: 211,
  },
  {
    id: 92,
    category: 'other',
    ArabicName: 'ماء',
    EnglishName: 'Water (Various Sacred & Medicinal Types)',
    MalayalamName: 'ജലം (വിവിധ ഇനങ്ങൾ)',
    ScientificName: '',
    DescriptionEnglish: 'Several types: Abundant Spring Water (جوار خالص, 25v-17) for protection; Deep Sea Water (25r-8); Distilled Water (16r-7) to wash Quranic verses from vellum for the sick to drink; Water From Under a Bridge (25r, 7-8); Zamzam Water (15v-14) from the holy well in Mecca, believed to have miraculous healing powers in Islamic tradition.',
    DescriptionMalayalam: 'വിവിധ ഇനം: ഉറവ ജലം (സംരക്ഷണം), ആഴക്കടൽ ജലം, ശുദ്ധ ജലം (ഖുർആൻ ആയതുകൾ കഴുകൽ), പാലം ജലം, സംസം ജലം (മക്ക — ഇസ്ലാമിൽ അദ്ഭുത സൗഖ്യ ഗുണം).',
    UsesEnglish: 'Zamzam water: miraculous healing; Distilled water: wash Quranic verses for the sick; Spring water: protection; various ritual and medicinal uses.',
    UsesMalayalam: 'സംസം ജലം: അദ്ഭുത സൗഖ്യം; ശുദ്ധ ജലം: ആയത് കഴുകൽ; ഉറവ ജലം: സംരക്ഷണം.',
    PageReference: '25v-17, 25r-8, 16r-7, 25r-7-8, 15v-14',
    SourcePage: 211,
  },
  {
    id: 93,
    category: 'herb',
    ArabicName: 'حرمل / سداب جبلي',
    EnglishName: 'Wild Rue / Mountain Rue',
    MalayalamName: 'കാട്ടു റൂ / പർവ്വത റൂ',
    ScientificName: 'Peganum harmala / Ruta Montana',
    DescriptionEnglish: 'Wild Rue on pages 3v-16, 7r-14, 7r-15, 10r-7, 13r-1. Mountain Rue on pages 7r-14 and 21v-13. Popular in North Africa for medicinal and magical uses. Used for insanity, epilepsy, hemorrhoids and baldness. Preserves and sharpens sight. Relieves headaches, hysterical spasms, and chronic bronchitis. Seeds used for purification and as aphrodisiac. Has psychedelic properties. Mountain rue used in perfumery and food flavoring.',
    DescriptionMalayalam: 'വടക്കൻ ആഫ്രിക്ക — ഔഷധ, മന്ത്ര ഉപയോഗം. ഭ്രാന്ത്, അപസ്മാരം, മൂലം, കഷണ്ടി. കാഴ്ച ശക്തി, തലവേദന, ഹിസ്റ്റീരിക്കൽ ആക്ഷേപം, ദീർഘകാല ബ്രോങ്കൈറ്റിസ്. ശുദ്ധീകരണ, ലൈംഗിക ഉത്തേജകം. മനോഭ്രമ ഗുണം.',
    UsesEnglish: 'Insanity; epilepsy; hemorrhoids; baldness; sharpen sight; headaches; bronchitis; purification; aphrodisiac; psychedelic.',
    UsesMalayalam: 'ഭ്രാന്ത്; അപസ്മാരം; മൂലം; കഷണ്ടി; കാഴ്ച ശക്തി; ബ്രോങ്കൈറ്റിസ്; ശുദ്ധീകരണം; ലൈംഗിക ഉത്തേജകം.',
    PageReference: '3v-16, 7r-14, 7r-15, 10r-7, 21v-13',
    SourcePage: 211,
  },
  {
    id: 94,
    category: 'herb',
    ArabicName: 'حزبق ابيض',
    EnglishName: 'White Hellebore',
    MalayalamName: 'വെള്ള ഹെല്ലിബോർ',
    ScientificName: 'Veratrum album',
    DescriptionEnglish: 'Appears on page 23v-11. A violent, irritant poison. Formerly used in cerebral affections such as mania and epilepsy, as well as externally against scabies and mange.',
    DescriptionMalayalam: 'ശക്തമായ ക്ഷോഭകര വിഷം. ഭ്രാന്ത്, അപസ്മാരം ചികിത്സ. ചൊറിച്ചിൽ, മഞ്ഞ (ബാഹ്യ).',
    UsesEnglish: 'Mania; epilepsy (cerebral affections); externally for scabies and mange. CAUTION: violent poison.',
    UsesMalayalam: 'ഭ്രാന്ത്; അപസ്മാരം; ചൊറിച്ചിൽ (ബാഹ്യ). ജാഗ്രത: ശക്ത വിഷം.',
    PageReference: '23v-11',
    SourcePage: 211,
  },
  {
    id: 95,
    category: 'other',
    ArabicName: 'بهم ابيض',
    EnglishName: 'White Lead Ore',
    MalayalamName: 'വെള്ള ലെഡ് ധാതു',
    ScientificName: '',
    DescriptionEnglish: 'Appears on page 23r-1. A lead carbonate and lead hydrate. Not natural — made by corroding lead with vinegar. Used as a pigment and medicine, generally for eye ointments.',
    DescriptionMalayalam: 'ലെഡ് കാർബണേറ്റ്, ലെഡ് ഹൈഡ്രേറ്റ്. ലെഡ് + വിനാഗിരി. ചായക്കൂട്ട്, നേത്ര ലേഹ്യം.',
    UsesEnglish: 'Pigment; eye ointments.',
    UsesMalayalam: 'ചായക്കൂട്ട്; നേത്ര ലേഹ്യം.',
    PageReference: '23r-1',
    SourcePage: 211,
  },
  {
    id: 96,
    category: 'flower',
    ArabicName: 'شقايق الورد',
    EnglishName: 'Windflower (Pasque Flower)',
    MalayalamName: 'വിൻഡ്ഫ്ലവർ',
    ScientificName: 'Pulsatilla vulgaris',
    DescriptionEnglish: 'Appears on page 13v, lines 13 and 14. Used to lower arterial tension, dilate the pupils and reduce respiration. Except in small amounts, it is poisonous.',
    DescriptionMalayalam: 'ധമനി ടെൻഷൻ കുറക്കൽ, കണ്ണ് മണി വികസനം, ശ്വസനം കുറക്കൽ. ചെറിയ ഡോസ് ഒഴിച്ചാൽ വിഷകരം.',
    UsesEnglish: 'Lower arterial tension; dilate pupils; reduce respiration. CAUTION: poisonous except in small amounts.',
    UsesMalayalam: 'ധമനി ടെൻഷൻ; കണ്ണ് മണി വികസനം; ശ്വസനം. ജാഗ്രത: വിഷകരം.',
    PageReference: '13v',
    SourcePage: 212,
  },
  {
    id: 97,
    category: 'spice',
    ArabicName: 'سعتر / زعتر',
    EnglishName: "Za'atar",
    MalayalamName: 'സആ\'ത്തർ',
    ScientificName: 'Thymus / Origanum',
    DescriptionEnglish: "Found on page 26r-20. A thyme/oregano spice mixture. Considered antiseptic, antispasmodic and antifungal. Used as an expectorant and a vermifuge.",
    DescriptionMalayalam: 'തൈം/ഒറഗാനോ സുഗന്ധ മിശ്രിതം. അണുനാശ, ആക്ഷേപ ശമന, ഫംഗസ് നിരോധക ഗുണങ്ങൾ. ശ്വാസ ഉത്തേജകം, കൃമി ഔഷധം.',
    UsesEnglish: 'Antiseptic; antispasmodic; antifungal; expectorant; vermifuge.',
    UsesMalayalam: 'അണുനാശകം; ആക്ഷേപ ശമനം; ഫംഗസ് നിരോധം; ശ്വാസ ഉത്തേജകം; കൃമി ഔഷധം.',
    PageReference: '26r-20',
    SourcePage: 212,
  },
  {
    id: 98,
    category: 'root',
    ArabicName: 'زدوار',
    EnglishName: 'Zedoary',
    MalayalamName: 'കിച്ചലി കിഴങ്ങ്',
    ScientificName: 'Curcuma zedoaria',
    DescriptionEnglish: 'Appears on pages 10v-1, 12r-17, and 23r-1. Used as an aid to digestion, to give relief from colic, and for purifying the blood.',
    DescriptionMalayalam: 'ദഹന സഹായം, കോളിക് ശമനം, രക്ത ശുദ്ധീകരണം.',
    UsesEnglish: 'Digestion aid; colic relief; blood purification.',
    UsesMalayalam: 'ദഹന സഹായം; കോളിക്; രക്ത ശുദ്ധീകരണം.',
    PageReference: '10v-1, 12r-17, 23r-1',
    SourcePage: 212,
  },
];