// ═══════════════════════════════════════════════════════════════
//  MULTILINGUAL LABELS — English / Arabic
// ═══════════════════════════════════════════════════════════════
const L = {
  en: {
    title:         "Magic Square — Sacred Vefk",
    subtitle:      "Traditional Construction System",
    baseNumber:    "🔢 Base Number",
    gridSize:      "Grid Size",
    element:       "Element",
    generate:      "Generate Magic Square",
    suffix:        "Suffix System",
    suffixNone:      "No Suffix",
    suffixArAngel:   "Arabic Angel (−41)",
    suffixArJinn:    "Arabic Sher Jinn (−319)",
    suffixHebAngel:  "Hebrew Angel (−31)",
    suffixHebJinn:   "Hebrew Jinn (−329)",
    suffixSufliHadim:"Arabic Sufli Hadim (−316)",
    inputLabel:    "Input Number",
    workingMC:     "Magic Constant (MC)",
    usurper:       "Usurper (Min Cell)",
    guide:         "Guide (Max Cell)",
    mystery:       "Mystery",
    adjuster:      "Adjuster (Magic Constant)",
    leader:        "Leader",
    regulator:     "Regulator",
    genGov:        "General Governor",
    highOver:      "High Overseer",
    angelAr:       "Angel (Arabic)",
    angelHeb:      "Angel (Hebrew)",
    jinnAr:        "Jinn (Arabic)",
    jinnHeb:       "Jinn (Hebrew)",
    hierarchy:     "📜 Hierarchy Table",
    compatible:    "Compatible Sizes",
    incompatible:  "⚠️ Incompatible with this grid size",
    compatSizes:   "Compatible Grid Sizes",
    planet:        "🪐 Associated Planet",
    negFix:        "+360 applied (negative fix)",
    subtracted:    "Suffix subtracted",
    verification:  "⚖ Verification Report",
    mcLabel:       "Magic Constant",
    rows:          "Rows",
    columns:       "Columns",
    diag1:         "Diagonal ↘",
    diag2:         "Diagonal ↙",
    trueSquare:    "✦ True Magic Square",
    letterTable:   "📖 Letter Value Tables",
    arabicTable:   "Arabic Abjad",
    hebrewTable:   "Hebrew Gematria",
    nameConstruct: "Spiritual Name Construction",
    inputValue:    "Input Value",
    letterResult:  "Letter Result",
    planetReport:  "🪐 Planet Report",
    totalCells:    "Total Cells",
    totalValue:    "Total Square Value (Leader)",
    fire: "Fire", air: "Air", earth: "Earth", water: "Water",
    saturn:"Saturn", jupiter:"Jupiter", mars:"Mars", sun:"Sun",
    venus:"Venus", mercury:"Mercury", moon:"Moon",
  },
  ar: {
    title:         "المربع السحري — وفق مقدس",
    subtitle:      "نظام البناء التقليدي",
    baseNumber:    "🔢 الرقم الأساسي",
    gridSize:      "حجم المربع",
    element:       "العنصر",
    generate:      "توليد المربع السحري",
    suffix:        "نظام اللاحقة",
    suffixNone:      "بدون لاحقة",
    suffixArAngel:   "ملاك عربي (−٤١)",
    suffixArJinn:    "جن عربي (−٣١٩)",
    suffixHebAngel:  "ملاك عبري (−٣١)",
    suffixHebJinn:   "جن عبري (−٣٢٩)",
    suffixSufliHadim:"سفلي هادم (−٣١٦)",
    inputLabel:    "الرقم المُدخل",
    workingMC:     "الثابت السحري (MC)",
    usurper:       "المغتصب (أصغر خانة)",
    guide:         "الدليل (أكبر خانة)",
    mystery:       "الغموض",
    adjuster:      "المُعدِّل (الثابت السحري)",
    leader:        "القائد",
    regulator:     "المنظِّم",
    genGov:        "الحاكم العام",
    highOver:      "المراقب الأعلى",
    angelAr:       "قيمة الملاك (عربي)",
    angelHeb:      "قيمة الملاك (عبري)",
    jinnAr:        "قيمة الجن (عربي)",
    jinnHeb:       "قيمة الجن (عبري)",
    hierarchy:     "📜 جدول التسلسل الهرمي",
    compatible:    "أحجام متوافقة",
    incompatible:  "⚠️ الرقم غير متوافق مع هذا الحجم",
    compatSizes:   "الأحجام المتوافقة",
    planet:        "🪐 الكوكب المرتبط",
    negFix:        "تم إضافة ٣٦٠ لتصحيح القيمة السالبة",
    subtracted:    "تم طرح اللاحقة",
    verification:  "⚖ تقرير التحقق",
    mcLabel:       "الثابت السحري",
    rows:          "الصفوف",
    columns:       "الأعمدة",
    diag1:         "القطر ↘",
    diag2:         "القطر ↙",
    trueSquare:    "✦ مربع سحري حقيقي",
    letterTable:   "📖 جدول قيم الحروف",
    arabicTable:   "الأبجد العربي",
    hebrewTable:   "الجماتريا العبرية",
    nameConstruct: "نظام استخراج الأسماء الروحية",
    inputValue:    "القيمة المُدخلة",
    letterResult:  "نتيجة الحروف",
    planetReport:  "🪐 تقرير الكوكب",
    totalCells:    "إجمالي الخلايا",
    totalValue:    "القيمة الكلية للمربع (القائد)",
    fire:"النار", air:"الهواء", earth:"التراب", water:"الماء",
    saturn:"الزحل", jupiter:"المشتري", mars:"المريخ", sun:"الشمس",
    venus:"الزهرة", mercury:"العطارد", moon:"القمر",
  },
};

export default L;