with payload(id,name_id,expected_meaning,malayalam_meaning) as (values
('8815b1a7-92b1-40db-8b0d-697b929232ac'::uuid, 'HNK-MHC-001', '''Holy'' and some say ''Glorified''', '‘പരിശുദ്ധം’ എന്നാണ് അർത്ഥം. ‘മഹത്വപ്പെടുത്തപ്പെട്ടത്’ എന്നും ചിലർ പറയുന്നു.'),
('3272d6de-b461-4535-8f00-9900d653883e'::uuid, 'HNK-MHC-002', '''God of all-things'' and some say ''O God''', '‘എല്ലാറ്റിന്റെയും ദൈവം’ എന്നാണ് അർത്ഥം. ‘ദൈവമേ’ എന്നും ചിലർ പറയുന്നു.'),
('3eeeaa7b-e1e3-48dc-a0d6-36eaa9386419'::uuid, 'HNK-MHC-003', '''the Holy, the Powerful/the Powerfully Holy'' and it is also said ''Glorified, Holy'' and some say ''The Well-Informed'' and it is said ''The Protector from Oppression''', '‘പരിശുദ്ധനായവൻ, ശക്തനായവൻ / ശക്തമായി പരിശുദ്ധനായവൻ’ എന്നാണ് അർത്ഥം. ‘മഹത്വപ്പെടുത്തപ്പെട്ടവൻ, പരിശുദ്ധനായവൻ’ എന്നും പറയുന്നു. ‘നന്നായി അറിവുള്ളവൻ’ എന്നും ചിലർ പറയുന്നു; ‘അടിച്ചമർത്തലിൽനിന്ന് സംരക്ഷിക്കുന്നവൻ’ എന്നും പറയുന്നു.'),
('74e83a2e-bfb7-45fa-988e-257d88c5115e'::uuid, 'HNK-MHC-004', '''O Alive/Living'' and some say ''O Revivifier''', '‘ജീവനുള്ളവനേ / ജീവിക്കുന്നവനേ’ എന്നാണ് അർത്ഥം. ‘ജീവൻ പുനർനൽകുന്നവനേ’ എന്നും ചിലർ പറയുന്നു.'),
('2c6bd8d2-6f5c-444b-acb3-9c293ce6abf8'::uuid, 'HNK-MHC-005', '''O Peerless/Self-Subsistent'' and some say ''O Ariser''', '‘സമാനതകളില്ലാത്തവനേ / സ്വയം നിലനിൽക്കുന്നവനേ’ എന്നാണ് അർത്ഥം. ‘എഴുന്നേൽക്കുന്നവനേ (Ariser)’ എന്നും ചിലർ പറയുന്നു.'),
('50b4926e-729d-48ee-9c8b-ae63b5fbfbea'::uuid, 'HNK-MHC-006', '''O Adored One'' and some say ''O God'' and it is said ''O Victorious'' and some say ''O One/Primary'' and it is said ''O One/First''', '‘ആരാധിക്കപ്പെടുന്നവനേ’ എന്നാണ് അർത്ഥം. ‘ദൈവമേ’ എന്നും ചിലർ പറയുന്നു. ‘വിജയശാലിയായവനേ’ എന്നും പറയുന്നു. ‘ഏകനായവനേ / പ്രാഥമികനായവനേ’ എന്നും ചിലർ പറയുന്നു; ‘ഏകനായവനേ / ആദിയായവനേ’ എന്നും പറയുന്നു.'),
('fc9d7e08-6217-4e3a-80ed-999e4f1ef672'::uuid, 'HNK-MHC-007', '''O Peace''', '‘സമാധാനമേ’ എന്നാണ് അർത്ഥം.'),
('8c8d0bfe-8642-419d-a25a-8efa63ad4dc6'::uuid, 'HNK-MHC-008', '''O God, thy servant. Respond to him'' and some say ''O Powerful/Capable''', '‘ദൈവമേ, നിന്റെ ദാസൻ. അവന് മറുപടി നൽകേണമേ’ എന്നാണ് അർത്ഥം. ‘ശക്തനായവനേ / കഴിവുള്ളവനേ’ എന്നും ചിലർ പറയുന്നു.'),
('6360b1cc-f3dd-441a-81a2-b1d9bc0068d7'::uuid, 'HNK-MHC-009', '''O Praised One, O Glorious One'' and some say ''O Sovereign''', '‘സ്തുതിക്കപ്പെടുന്നവനേ, മഹിമയുള്ളവനേ’ എന്നാണ് അർത്ഥം. ‘പരമാധികാരിയായവനേ’ എന്നും ചിലർ പറയുന്നു.'),
('2b5b1a41-0a72-4c0a-855a-3fe48587e4cc'::uuid, 'HNK-MHC-010', '''O Powerful'' and it is said ''O Impregnable, O Knowing, O Wise''', '‘ശക്തനായവനേ’ എന്നാണ് അർത്ഥം. ‘അജയ്യനായവനേ, അറിവുള്ളവനേ, ജ്ഞാനിയായവനേ’ എന്നും പറയുന്നു.'),
('5c524bed-d248-414b-8cff-37d1b45b0133'::uuid, 'HNK-MHC-011', '''O Impregnable'' and it is said ''O Hearer, O Seer'' and it is said ''O Hearing, O Wondrous/Fashioner'' and some say ''O Self-Sufficient'' and it is said ''O All-Encompassing''', '‘അജയ്യനായവനേ’ എന്നാണ് അർത്ഥം. ‘കേൾക്കുന്നവനേ, കാണുന്നവനേ’ എന്നും പറയുന്നു. ‘കേൾക്കുന്നവനേ, വിസ്മയകരനായവനേ / രൂപം നൽകുന്നവനേ’ എന്നും പറയുന്നു. ‘സ്വയംപര്യാപ്തനായവനേ’ എന്നും ചിലർ പറയുന്നു; ‘എല്ലാം ഉൾക്കൊള്ളുന്നവനേ’ എന്നും പറയുന്നു.'),
('17bcf734-10bf-48e8-95f8-e893a646b486'::uuid, 'HNK-MHC-012', '''O All-Encompassing'' and it is said ''O Godhead, O Dearly Precious/Grandiose''', '‘എല്ലാം ഉൾക്കൊള്ളുന്നവനേ’ എന്നാണ് അർത്ഥം. ‘ദൈവത്വമേ, അതിപ്രിയപ്പെട്ടവനേ / മഹാമഹിമയുള്ളവനേ’ എന്നും പറയുന്നു.'),
('42d20d43-9915-4663-97c4-a971e5b290eb'::uuid, 'HNK-MHC-013', '''Glory be to God'' and it is said ''O Powerful, O Impregnable'' and some say ''O Merciful''', '‘മഹത്വം ദൈവത്തിനാകട്ടെ’ എന്നാണ് അർത്ഥം. ‘ശക്തനായവനേ, അജയ്യനായവനേ’ എന്നും പറയുന്നു. ‘ദയാലുവായവനേ’ എന്നും ചിലർ പറയുന്നു.'),
('b858a490-bf70-4ec5-a032-8475c55f5f0e'::uuid, 'HNK-MHC-014', '''O God, O Dearly Precious/Grandiose/Tremendous'' and it is said ''I Am God, the refuge of the fearful'' And it is also said its meaning denotes ''O Dearly Precious/Grandiose/ Thou art God'' and others say ''O God, O Powerful, O Impregnable'' and it is said ''O God, O It/he''', '‘ദൈവമേ, അതിപ്രിയപ്പെട്ടവനേ / മഹാമഹിമയുള്ളവനേ / അതിമഹത്തായവനേ’ എന്നാണ് അർത്ഥം. ‘ഞാനാണ് ദൈവം, ഭയപ്പെടുന്നവരുടെ അഭയം’ എന്നും പറയുന്നു. ‘അതിപ്രിയപ്പെട്ടവനേ / മഹാമഹിമയുള്ളവനേ / നീയാണ് ദൈവം’ എന്ന അർത്ഥവും ഇതിന് പറയപ്പെടുന്നു. ‘ദൈവമേ, ശക്തനായവനേ, അജയ്യനായവനേ’ എന്നും മറ്റുചിലർ പറയുന്നു; ‘ദൈവമേ, ഹേ അത് / അവൻ (It/he)’ എന്നും പറയുന്നു.'),
('18b50d61-1f64-4a73-a995-1db5bed082f4'::uuid, 'HNK-MHC-015', '''Glory be to God'' and some say ''I Am God, the refuge of the fearful'' and others say ''O Sufficient, O Hearer'' and it is said ''O God, may my soul be raised by Thy Spirit to Thy Will''', '‘മഹത്വം ദൈവത്തിനാകട്ടെ’ എന്നാണ് അർത്ഥം. ‘ഞാനാണ് ദൈവം, ഭയപ്പെടുന്നവരുടെ അഭയം’ എന്നും ചിലർ പറയുന്നു. ‘മതിയായവനേ, കേൾക്കുന്നവനേ’ എന്നും മറ്റുചിലർ പറയുന്നു; ‘ദൈവമേ, നിന്റെ ആത്മാവിനാൽ എന്റെ ആത്മാവ് നിന്റെ ഇച്ഛയിലേക്ക് ഉയർത്തപ്പെടട്ടെ’ എന്നും പറയുന്നു.'),
('241ec1d6-ca9e-49ed-8200-cf628d68efb8'::uuid, 'HNK-MHC-016', '''O Protector of Faith'' and it is said ''Lofty be God, the Compassionate, the Merciful''', '‘വിശ്വാസത്തെ സംരക്ഷിക്കുന്നവനേ’ എന്നാണ് അർത്ഥം. ‘കരുണാനിധിയും ദയാലുവുമായ ദൈവം ഉന്നതനായിരിക്കട്ടെ’ എന്നും പറയുന്നു.'),
('d1e0d702-fafc-4e23-b342-99f8791cc3f9'::uuid, 'HNK-MHC-017', '''O Protector'' and it is said ''Lofty be God, the Compassionate, the Merciful''', '‘സംരക്ഷിക്കുന്നവനേ’ എന്നാണ് അർത്ഥം. ‘കരുണാനിധിയും ദയാലുവുമായ ദൈവം ഉന്നതനായിരിക്കട്ടെ’ എന്നും പറയുന്നു.'),
('47fb160e-3afa-496f-9f69-df2cd4e0e027'::uuid, 'HNK-MHC-018', '''O Mighty, O Judge/Wise'' and it is said ''O Judge/Wise, O Well-Informed, O Magnanimous'' and others say ''the Compassionate, the Merciful''', '‘മഹാശക്തനായവനേ, വിധികർത്താവേ / ജ്ഞാനിയായവനേ’ എന്നാണ് അർത്ഥം. ‘വിധികർത്താവേ / ജ്ഞാനിയായവനേ, നന്നായി അറിവുള്ളവനേ, വിശാലമനസ്കനായവനേ’ എന്നും പറയുന്നു. ‘കരുണാനിധി, ദയാലുവായവൻ’ എന്നും മറ്റുചിലർ പറയുന്നു.'),
('5a98ac6e-b328-4814-a425-15d80d6f1cc5'::uuid, 'HNK-MHC-019', '''O Dearly Precious/Grandiose'' and it is said ''O Subsistent'' and others say ''O Clement'' and it is said ''O Judge/Wise'' and some say ''O Sufficient, O Munificent'' and it is said ''Lofty be the Godhead, the Sufficient, the Munificent''', '‘അതിപ്രിയപ്പെട്ടവനേ / മഹാമഹിമയുള്ളവനേ’ എന്നാണ് അർത്ഥം. ‘നിലനിൽക്കുന്നവനേ’ എന്നും പറയുന്നു. ‘സഹനശീലനായവനേ’ എന്നും മറ്റുചിലർ പറയുന്നു; ‘വിധികർത്താവേ / ജ്ഞാനിയായവനേ’ എന്നും പറയുന്നു. ‘മതിയായവനേ, അത്യുദാരനായവനേ’ എന്നും ചിലർ പറയുന്നു; ‘മതിയായതും അത്യുദാരവുമായ ദൈവത്വം ഉന്നതമായിരിക്കട്ടെ’ എന്നും പറയുന്നു.'),
('f3daacd4-d542-4809-8202-23247cfb901b'::uuid, 'HNK-MHC-020', '''O Munificent, O Victorious'' and it is also said ''O Munificent, O Adjudicator/Judge'' and others say ''O Dearly Precious/Grandiose, O Omnipotent''', '‘അത്യുദാരനായവനേ, വിജയശാലിയായവനേ’ എന്നാണ് അർത്ഥം. ‘അത്യുദാരനായവനേ, വിധി നിർണയിക്കുന്നവനേ / വിധികർത്താവേ’ എന്നും പറയുന്നു. ‘അതിപ്രിയപ്പെട്ടവനേ / മഹാമഹിമയുള്ളവനേ, സർവശക്തനായവനേ’ എന്നും മറ്റുചിലർ പറയുന്നു.'),
('3d0ffdd6-dc34-4340-b5fe-90eae1b9b5b0'::uuid, 'HNK-MHC-021', '''The Powerful/Capable, It/He is God'' and it is said ''O Ancient, O Victorious, O Powerful/Capable over all-things'' and some say ''O speedy/swift One''', '‘ശക്തനായവൻ / കഴിവുള്ളവൻ; അത് / അവൻ ദൈവമാണ്’ എന്നാണ് അർത്ഥം. ‘പുരാതനനായവനേ, വിജയശാലിയായവനേ, എല്ലാറ്റിനും ശക്തിയുള്ളവനേ / കഴിവുള്ളവനേ’ എന്നും പറയുന്നു. ‘വേഗതയുള്ളവനേ / അതിവേഗമുള്ളവനേ’ എന്നും ചിലർ പറയുന്നു.'),
('e3a8ede5-eee2-4237-9cd8-6101327e3635'::uuid, 'HNK-MHC-022', '''Elevated art Thou, O High, O Knowing''', '‘ഉന്നതനായവനേ, അറിവുള്ളവനേ, നീ ഉയർന്നവനാകുന്നു’ എന്നാണ് അർത്ഥം.'),
('276e5d4e-57ee-4297-910a-acb6ca07091f'::uuid, 'HNK-MHC-023', '''O Adjudicator/Judge'' and it is said ''O It/he, O It/he'' and others say ''O Lord, O Lord''', '‘വിധി നിർണയിക്കുന്നവനേ / വിധികർത്താവേ’ എന്നാണ് അർത്ഥം. ‘ഹേ അത് / അവൻ, ഹേ അത് / അവൻ (It/he)’ എന്നും പറയുന്നു. ‘നാഥാ, നാഥാ’ എന്നും മറ്റുചിലർ പറയുന്നു.'),
('89f94946-588e-4de1-9dad-656462bc3e36'::uuid, 'HNK-MHC-024', '''O Powerful, O Capable'' and it is said ''O Sufficient, O Dearly Precious/Grandiose, O Omnipotent''', '‘ശക്തനായവനേ, കഴിവുള്ളവനേ’ എന്നാണ് അർത്ഥം. ‘മതിയായവനേ, അതിപ്രിയപ്പെട്ടവനേ / മഹാമഹിമയുള്ളവനേ, സർവശക്തനായവനേ’ എന്നും പറയുന്നു.'),
('ea9f15e2-de5c-4708-942b-928d342cefcf'::uuid, 'HNK-MHC-025', '''O Ancient'' and it is said ''O Constant/Perpetual''', '‘പുരാതനനായവനേ’ എന്നാണ് അർത്ഥം. ‘സ്ഥിരമായവനേ / തുടർച്ചയായി നിലനിൽക്കുന്നവനേ’ എന്നും പറയുന്നു.'),
('4052254a-9357-45ec-9d62-629e74d202d2'::uuid, 'HNK-MHC-026', '''O Capable/Powerful over all-things''', '‘എല്ലാറ്റിനും കഴിവുള്ളവനേ / ശക്തിയുള്ളവനേ’ എന്നാണ് അർത്ഥം.'),
('6288f6c6-9475-4b65-9e37-adb0400a6663'::uuid, 'HNK-MHC-027', '''O Praiseworthy'' and it is said ''It is God, the Munificent''', '‘സ്തുത്യർഹനായവനേ’ എന്നാണ് അർത്ഥം. ‘അത് ദൈവമാണ്, അത്യുദാരനായവൻ’ എന്നും പറയുന്നു.'),
('54d40811-2530-4e5b-ace2-d6f76e6ba246'::uuid, 'HNK-MHC-028', '''O Capable/Powerful, He is God, the Munificent''', '‘കഴിവുള്ളവനേ / ശക്തനായവനേ; അവൻ ദൈവമാണ്, അത്യുദാരനായവൻ’ എന്നാണ് അർത്ഥം.')
), matched as materialized (
select p.id,p.entity,p.data as original,v.malayalam_meaning from public.platform_records p join payload v on p.id=v.id
where p.entity='HolyNameEsotericKnowledge' and p.data->>'name_id'=v.name_id and p.data->>'exact_meaning'=v.expected_meaning
and coalesce(p.data->>'malayalam_meaning','')='' and coalesce(p.data->>'english_meaning','')=''
), backup as (
insert into public.reference_record_backup(record_id,entity,data) select id,entity,original from matched
where (select count(*) from matched)=28 on conflict(record_id) do nothing returning record_id
), updated as (
update public.platform_records p set data=p.data || jsonb_build_object(
'malayalam_meaning',m.malayalam_meaning,
'english_meaning',m.original->>'exact_meaning',
'meaning_translation_metadata',jsonb_build_object('source_field','exact_meaning','source_language','en','target_language','ml','source_verification_status',coalesce(m.original->>'verification_status','unverified'),'translation_date','2026-10-07','scope','Faithful translation of imported English source claims; no independent source verification or new ritual claims.','ambiguous_glosses','Ariser and It/he retained where present.')),
updated_at=now()
from matched m where p.id=m.id and (select count(*) from matched)=28 and (select count(*) from backup)>=0
returning p.id, (p.data - array['malayalam_meaning','english_meaning','meaning_translation_metadata'])=m.original as original_fields_unchanged
)
select (select count(*) from matched) as eligible_rows,count(*) as updated_rows,bool_and(original_fields_unchanged) as original_fields_unchanged from updated;
